### ISSUE TITLE
New Script Idea: Review QW Information - L2500 & L2501

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#181]
Bulk script to assist with quarterly wage matches…

Similar to the bulk script already being created for the POF failure notice worklist…

My vision:  For each case with L2500 Review QW Information or L2501 Review QW Information, display the last three most recent employers’ names and addresses on the left hand side and on the right hand side display the company name and address information for the quarterly wage matches that need review.  Have a check box to mark the wage match reviewed, checkbox to purge the worklist, and a check box to add a free worklist for follow up.

**Comment by RobertFewins-Kalb** [comment]
Like!

**Comment by kellijo81** [comment]
I have a script built for this already, I just need a little help adding an Excel portion to it.

**Comment by levesswe** [comment]
So the uploaded version of the BULK - REVIEW QW INFO.vbs script does not have all the bells and whistles I had envisioned, but will review the worklists to eliminate those whose employers are already in NCID/CPID.  The additional functionality I was thinking of may be a future enhancement.

**Comment by theVKC** [comment]
@levesswe, is there any way you can build instructions for this script? If not, I will plan to do it, but I think it could be helpful if you could.

**Comment by theVKC** [comment]
@levesswe: never heard from you about making instructions for this. Can you please do that?

**Comment by theVKC** [comment]
Reopening this issue per our new process for script releases. Instructions not complete.

@levesswe, your instructions in DHS-SIR did not match the format we use. It looks like you uploaded a OneNote document instead of adapted it using our accessible format. Can you please re-enter the information, but using the "New" dropdown?

Also, _ensure that you use captions when creating instructions._ This is an accessibility guideline and must be followed. Use the "insert caption" options for Word. Thank you!

**Comment by theVKC** [comment]
Also also, I am going to close #469 as I am now re-opening this. This is part of issue re-evaluation and keeping things open until all processes are checked. So, @levesswe, when you fix the loop bug, you can simply tag it onto here!

**Comment by levesswe** [comment]
@theVKC, I wanted to let you know that I have re-worked this script.  It still doesn't have all the bells and whistles I initially imagined, but it uses different logic to resolve the bug that it previously didn't find all matches.  It also now produces spreadsheets for reference so workers can see what the script did.  I would like to do more testing before uploading the revised version, but I can do a pull request now if you want me to.  The training region allows for only minimal testing, so I am waiting on worklists so I can do more testing.

**Comment by levesswe** [comment]
PS.  You should assign this issue to me!

**Comment by theVKC** [comment]
Good deal, thank you @levesswe! Do you have an ETA?

**Comment by levesswe** [comment]
I don't know when I will get more worklists to test with - it could be tomorrow or a week or two.

**Comment by theVKC** [comment]
This is out there! If I'm not mistaken, @levesswe has already written instructions in SIR (pending my approval, which I will be reviewing shortly). Can I get two counties to test it? @MN-Script-Team/prism-scriptwriters?

**Comment by theVKC** [comment]
@levesswe, instructions approved in SIR! Thank you for the quick turnaround!

**Comment by theVKC** [comment]
Can I get feedback on how this one is going @MN-Script-Team/prism-scriptwriters?

**Comment by KallistaImdieke** [comment]
I have used this one multiple times in stearns and it appears to be working great.

Thanks!

**Comment by theVKC** [comment]
Anyone in any other counties? @MN-Script-Team/prism-scott? @MN-Script-Team/prism-wright? @MN-Script-Team/prism-olmsted? Need one other agency to confirm it's working before I mark it as complete.

**Comment by khiestand** [comment]
When I run this, it opens up two excel spreadsheets, one of which is blank?  Otherwise I believe it works.

**Comment by jlmartinone** [comment]
I ran it, it worked fine.   Not sure what the point of the spreadsheet is.  It appears to just list the worklists that did not purge. And it slows the script down.

Just my thoughts

[cid:image001.png@01D27BDC.9BED56D0]Thank you,
Jodi Martin
Child Support Officer
Wright County
763.682.7439
Fax 763.682.8920

How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by theVKC** [comment]
We include the lists for tracking purposes. Many counties may want this. If you don't use it, don't! Perhaps in the future we can include both as a single sheet with multiple sortable options or something.
