### ISSUE TITLE
Returned Mail Notes Script

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#350]
This is a new CAAD note script that will use the R0010, R0011, R0012 caad codes to note the details of returned mail received.  It will state the type of document received and what address is now bad, and date returned mail was received.  If anyone has anything else they want added to this let me know!

**Comment by levesswe** [comment]
Also provide options to update the participant's address with a  forwarding address or set the participant's address to unknown.

**Comment by theVKC** [comment]
@khiestand and @levesswe, can I get an update on this?

**Comment by khiestand** [comment]
@theVKC hoping to work on this tomorrow with you.  I think  we are almost done with it.

@levesswe , was there anything specific we needed to finish?

**Comment by theVKC** [comment]
Good deal, I've self-assigned as well (so that I remember it!).

**Comment by levesswe** [comment]
@khiestand I believe you were going to modify "Source" to have some of the most common values to put in a combo box....  ? 

I think it's good to go for super user testing.

**Comment by theVKC** [comment]
@khiestand and I worked on this a bit yesterday. Looking good so far, but she can tell you more.
