### ISSUE TITLE
E0014 Failure of POF script

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#364]
I just ran this script today. I had 25 work lists total this script purged 7 of them. However there were 10 additional Social Security POF's that were not purged where a payment came in,  they were for the following:

Social Sec Admin St Cloud 
Social Sec Admin Richmond IN
Social Sec Admin Creston IA
Social Sec Admin Minneapolis 
Social Sec Admin Austin. 

Can we do an improvement to include the above Social Sec Admin offices in the script so it would purge theses work lists also??

Thank you!

**Comment by levesswe** [comment]
This is a bug.  I'll take a look at it.

**Comment by theVKC** [comment]
@KallistaImdieke and @levesswe, is this for the script located here? https://github.com/MN-CS-Script-Team/PRISM-Scripts/blob/master/Script%20Files/BULK/BULK%20-%20FAILURE%20POF%20RSDI%20DFAS.vbs  

Also, I don't think this meets critical criteria if it's just skipping some.

**Comment by theVKC** [comment]
Also, can I get an update from one of you on this?

**Comment by KallistaImdieke** [comment]
I wouldn’t say it is critical just something to update or an enhancement

**Comment by levesswe** [comment]
Issue #470 is a duplicate of this issue.
