### ISSUE TITLE
NEW IDEA- default order script

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#383]
Veronica- this one should be assigned to you per our email conversation.

Currently, any county that uses CORD to do their legal actions will need to generate a default order if a party doesn’t request a hearing.  This would only be in cases for modification, establishment and motion to set (paternity cases require a hearing)

The process for doing a default order is to essentially re-create our supporting affidavit in the Order selection in CORD.  In Stearns, the CSO does a ‘cut and paste’ method that is not reliable and is fraught with errors, leading to more staff and county attorney time.  My very efficient cso’s can do a default in about 10 minutes where other staff can take up to an hour to complete this task.

I am proposing the development of a script that can do the ‘copy paste’ that the cso is currently doing, saving time and errors.
I have NO idea if it is even possible, buy you are like the jedi master of scripts, so if it can be done, it is you that can do it!

If this is something you are able to work on at some point and you are working on it when you are in Stearns, I am willing to offer up the technical assistance of one of my staff to walk you through what they do on a default.

I didn’t want to lose this idea!  Could be HUGE in time saving and reliability for the program!

**Comment by theVKC** [comment]
Hi Jannell! I've assigned it to myself. Based on the description and the current label designations, I'm thinking this would be an ACTIONS script. Let me know if it isn't.

**Comment by jannellstearns** [comment]
Definitely an Action script!  Thanks Veronica!!!

**Comment by theVKC** [comment]
I'm taking this off of the initial milestone, but we still have it on the radar. @KallistaImdieke and @TammyStearns are mapping out the process.

**Comment by theVKC** [comment]
Say, @MN-Script-Team/prism-stearns! I don't think I ever got that process map for this one. It's been open a bit, just wondering where that map could be.

**Comment by TammyStearns** [comment]
Kallista and I started mapping this out.  It is very long.  I am not sure that it is completed yet.

**Comment by theVKC** [comment]
Well good deal. But, it's been backlogged for a while now. I'm going to set a timer on it. If we don't have the map for the process in the next couple of weeks (or at least some progress on it), I'll mark the issue as a sleeper and close it. It can be reopened if it becomes a higher priority.

Sleeper timer: 12/12/2016. :)
