### ISSUE TITLE
Actions-Send F0104 Dord Memo enhancement

### ISSUE THREAD

**Issue by wrightcountykaren** [MN-Script-Team/DHS-PRISM-Scripts#386]
Enhancement idea for the DORD memo doc script:
- add a check box for the doc to be printed now
- add a pop-up dialog box that shows up after the script is run if the print now box is checked that says something like "updates to CAAD".  Then the CSO could type a short explanation that could be added to the caad note, for example:  To NCP, re:  DL being suspended, please call.

**Comment by theVKC** [comment]
@wrightcountykaren, think anyone from Wright wants to take this on, or should I mark as "help wanted" for now?

**Comment by levesswe** [comment]
I will offer to take this one if no one from Wright wants it.

**Comment by theVKC** [comment]
At present, you have five assigned issues. I'd prefer to resolve or close those issues before taking anything new on, @levesswe. :)

**Comment by theVKC** [comment]
@jlmartinone has agreed to take this on. Thank you!

**Comment by jlmartinone** [comment]
Rename to Generate Memo (F0104)

**Comment by theVKC** [comment]
@jlmartinone thank you!

**Comment by theVKC** [comment]
Resolved by #520.
