### ISSUE TITLE
New Idea - annual review script

### ISSUE THREAD

**Issue by gretchent74** [MN-Script-Team/DHS-PRISM-Scripts#390]
@KathyMutchler  script is 80% completed.  script guides user through important steps and reminders during annual case reviews, sends needed documents, creates caad and cawt notes.

**Comment by theVKC** [comment]
"Sends needed documents" - correct me if I'm mistaken, but do you think that makes it an "ACTIONS" script?

Also, I presume you're taking it? If you are, make sure to let me know in your issue so that I don't inadvertently mark it as "help wanted". Please and thank you!

**Comment by gretchent74** [comment]
Yes it is action and yes I want to take it.  I am not good at github…. How do assign myself to it?

**Comment by theVKC** [comment]
You don't! Just tell me that you want it and I'll assign it to you! :)

**Comment by theVKC** [comment]
@gretchent74, can I get an update on this one?

**Comment by gretchent74** [comment]
I was out of the office last week.  I hope I will  have a chance to work on it soon.

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
@gretchent74, think it can be done by MFSRC?

**Comment by gretchent74** [comment]
Maybe.  I am trying to catch up on my case work so I can set aside a few days to work on scripts.  I can make the annual review and the 2 issues assigned to me a priority.

**Comment by theVKC** [comment]
@gretchent74, any chance I can get an update on this one from you? If you don't think it can be done by September 30, I might kick it to the following release.

**Comment by gretchent74** [comment]
I plan to work on it 09/26/2016 but I don’t think it will be done by 09/30/2016.

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
Thanks for letting me know. I'll remove it from this release and tie it to the next one. The duedate for new scripts for that release is 10/14/2016.

**Comment by gretchent74** [comment]
I am still working this one but won't be done by 10/14/2016.
