### ISSUE TITLE
new idea - bulk script doc worklist L0103

### ISSUE THREAD

**Issue by gretchent74** [MN-Script-Team/DHS-PRISM-Scripts#391]
A script to review worklist  L0103, record information in caad and alert user with cawt of important info received if needed.    Possibly send appropriate locate documents and updated prism based on information received.

**Comment by theVKC** [comment]
Do you want this one @gretchent74?

**Comment by gretchent74** [comment]
Yes. thank you.

**Comment by theVKC** [comment]
@gretchent74, can I get an update on this one?

**Comment by gretchent74** [comment]
I was out of the office last week.  I hope I will  have a chance to work on it soon.

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
@gretchent74, do you think it's possible to get this one done before MFSRC?

**Comment by gretchent74** [comment]
Nope.

**Comment by gretchent74** [comment]
I almost done with this one.  I have 2 issues I am trying to resolve but mostly completed.  issues with caad note and script is only reviewing the first item in each case instead of all the are not reviewed yet.

**Comment by gretchent74** [comment]
Question:  does any one have an idea what i might be missing if the script is only working the first item that hasn't been reviewed on dolr but I want it to work all items that are not reviewed on that case and then move to the next case with the worklist?

**Comment by theVKC** [comment]
Could be a number of things, @gretchent74. Is something iterating through rows?
