### ISSUE TITLE
BULK - M6529 - correct flaws in process

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#407]
Here are the elements that need addressing (from the old M6529 script):
- [ ] Name of script should be more descriptive - BULK - REVIEW INTEREST SUPPRESSION (M6529)
- [ ] Date range of payments to be based on the last complete month rather than the last 90 calendar days (see #259)
- [ ] Should add M6529 CAAD note with a description that it was reviewed (regenerates 90 days later)
- [ ] Some kind of MsgBox or dialog that tells you what it's about to do
- [ ] Should ask for the worker to evaluate
- [ ] Should send out dord docs if the case no longer meets criteria for suppression (see #402)
- [ ] Needs to be added to the ALL SCRIPTS.vbs

@levesswe will be adding this as a new script. It was formerly assigned to @TammyStearns. Thanks @levesswe!

**Comment by theVKC** [comment]
@TammyStearns, per my notes, @levesswe was going to change the name of the script. However, you are assigned this issue. Am I missing something? @levesswe, were you going to be working on modifying this one? Perhaps I simply wrote the wrong name down and it's been @TammyStearns's this whole time. Just wanting to make sure I'm setting this up correctly.

**Comment by TammyStearns** [comment]
At the script meeting on 8/25/16 in Wright Co, I believe Wendy was going to take care of this instead of me.


Thank you.  Have a nice day!

Tammy Larson
Child Support Specialist
320-656-6237
320-656-6158

**Comment by theVKC** [comment]
@levesswe, can you confirm this with me when you can? That'd be swell (I'll refrain from re-assigning it for the time being).

**Comment by levesswe** [comment]
Yeah, I believe I said I would take this issue.

**Comment by theVKC** [comment]
@levesswe, can I get an update on this issue?

**Comment by theVKC** [comment]
@levesswe I haven't received an update on this in a while. Marking it as a sleeper and closing.
