### ISSUE TITLE
NEW SCRIPT - M1600 PA PROGRAM OPEN/REVIEW

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#409]
This is a new script I am working on to review cases and purge the worklist if it is a close code that we would never look at reopening and leave the worklist out there to review if it is a case that we would need to look into further to see if it should be reopened. 

@theVKC Please assign this issue to me.  Thanks!

**Comment by theVKC** [comment]
Can I get an update on this one @KallistaImdieke? It's marked for the September release, so if it won't be ready by next week we should move it to October. :)

**Comment by KallistaImdieke** [comment]
I will work on it this afternoon and let you know how far I get it was very close to being done just needed some information on which codes we would not automatically keep closed and I have that now.  Thanks!

**Comment by theVKC** [comment]
Good deal, thank you!

**Comment by KallistaImdieke** [comment]
The script is done and I have done a pull request (I hope I did it right)  let me know if you need anything else from me.  Thanks!!

**Comment by KallistaImdieke** [comment]
@theVKC Do I have to resubmit this script since you made the changes to the system or is this still waiting to be pulled in?

**Comment by theVKC** [comment]
Yes, you will have to resubmit. If you don't mind! Thanks for bumping it!

**Comment by KallistaImdieke** [comment]
Created Pull Request to resolve this. Thanks!

**Comment by theVKC** [comment]
Still need testers for this. Can we confirm this is now working? Need two agencies to confirm.

@MN-Script-Team/prism-scriptwriters?

**Comment by theVKC** [comment]
OK, I'm going to start picking on counties. @MN-Script-Team/prism-scott @MN-Script-Team/prism-anoka, can you test this and make sure it's working?

**Comment by levesswe** [comment]
@theVKC, I am not able to test this one at this time.  There are no M1600 worklists to process in the training region, and I don't get that worklist on my caseload very often.  Maybe another county would be able to be of more help?

**Comment by theVKC** [comment]
Can anyone from Anoka test it? I've tapped all of the counties already on other tasks. Surely someone from Anoka County has this.

**Comment by levesswe** [comment]
I found another worker who had 3 M1600 worklists, and the script correctly purged 2 of them and left 1 that didn't meet purge criteria.  Working in Anoka.

**Comment by theVKC** [comment]
Good deal, thank you! Still waiting on @MN-Script-Team/prism-scott or any other non-Stearns agency before wrapping it!

**Comment by theVKC** [comment]
(Also, @KallistaImdieke, please submit instructions for the script via DHS-SIR)

**Comment by theVKC** [comment]
Can anyone else confirm this is working? @MN-Script-Team/prism-scriptwriters?
