### ISSUE TITLE
Starting REAM and sending docs to include employer verifications  (refer-to-mod)

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#419]
I am not a script writer, but would like to see a script that would generate the REAM screen to send out modification documents, send employer verifications to any open employers on the CP/NCP employer screen and transfer the case to the modification prep position number.  I have attempted to write the flow for the potential script, but I may have missed something:

Modification Document Generation Script:

Go to CAAS and modify to correct position number 
• (03, 029) M
• (11,020) Correct team needs to be selected
• (12, 020) correct position needs to be selected
• <transmit>

Go to REAM screen to start modification 
• (03, 029) A
• (04, 035) F1 to select current charging order based on NCOL
• (10, 015) populate with today’s date in format mm/dd/yyyy
• (12, 017) select who is requesting modification (CP/NCP/AGE/OTH)
• (13, 019) Request reason for modification (from list in REAM screen F1)
o   CCC   COUNTY AWARE OF POSSIBLE CHANG
o   CHD   CHILD DISABLED  
o   CIC   CHANGE IN CIRCUMSTANCES  
o   CUR   CHILD CARE SUPPORT NEEDS TO BE
o   DCI   DISTRICT COURT ISSUES  
o   EMC   EMANCIPATION OF CHILD(REN)  
o   INC   NCP INCARCERATED  
o   JOI   NUMBER OF JOINT CHILDREN CHANG 
o   MED   MEDICAL SUPPORT NEEDS TO BE ES 
o   OTH   OTHER REASON - WORKER TO TYPE  
o   PAR   PARENTING TIME CHANGED  
o   PCT   THE EXISTING SUPPORT ORDER IS  
o   PER   FEDERAL LAW REQUIRES PERIODIC  
o   REQ   COURT ORDER REQUIRES REVIEW AN  
o   RPA   NCP RECEIVES PUBLIC ASSISTANCE  
o   SIM   STREAMLINED INCARCERATED MOD 
o   SSA   NCP RECEIVES SSI OR RSDI  
• <transmit>

Go to NCIL
• Send DORD F0405 (employer verification form) for any employers without an End date  -- MCI based document
Go to CPIL
• Send DORD F0405 (employer verification form)  for any employers without an End Date – MCI based document 
Stearns would like to see:
• Word document template for Daycare Provider Financial Statement be generated on each modification request as selected.  We have a non-letterhead version we would be willing to share if other counties see benefit in using this as well.

**Comment by KallistaImdieke** [comment]
I can take this script and work on it - For now I can create this script on its own but thinking it maybe smart to connect this script with the NOTES - MOD CAAD NOTE Client Contact??  Any thoughts on that @jannellstearns , Thinking that if we state that NCP/CP requested an agency review it will automatically start adding the REAM screen.  Not sure if Counties would prefer it be separate for any reasons??  Right now I know not all counties are using the NOTES - MOD CAAD NOTE Client Contact script. 

Also thought it would be nice to try and have the NOTES - MOD CAAD NOTE Client Contact script have some enhancements to update the employer (NCID/CPID), address (CPDD/NCDD) and phone number (NCDE/CPDE), not sure if this is a little bigger then my knowledge at this point but I am willing to attempt to tackle it, May need a little help from @theVKC  at the Hackathon. Should that be added as a separate issue or should I try and combine it with this

**Comment by theVKC** [comment]
@KallistaImdieke, what do you think about this idea? I don't know that we talked about it yesterday, but I'm OK with delaying it until the next release if you'd like.

**Comment by KallistaImdieke** [comment]
@theVKC This is the script I was hoping to work on next (after the one I was working on and finishing the intake script)  not sure if it will make this release or if it will have to be the next one if you are doing the release before conference it may need to be the next one.  Thanks!

**Comment by theVKC** [comment]
@KallistaImdieke: can I get an update on this? It's been marked as "in development" for a while. I'd love to get it out there, or if it'll be a while, I might close it for now.

**Comment by levesswe** [comment]
@KallistaImdieke, are you working on this script?  I just received a request from my supervisors to make a version of this idea for use with some Anoka county specific documents and child care verification in addition sending out EVRs.  Anoka supervisors are still working out all that they want the script to do.  If you haven't started working on this yet, you can steal from me after development!  @theVKC, don't close this issue!

**Comment by KallistaImdieke** [comment]
I am working on this I started it but then was given a different script that was higher priority that I needed to work on this will be the next one I work on again.  If you have ideas of what your office wants from it you can let me know.   Thanks!

**Comment by theVKC** [comment]
@KallistaImdieke and @levesswe, can you discuss a timeline for this as well as who's doing the work on it, and get that discussion back to me this week? Or have it on GitHub, because then I see it in real time. :)

**Comment by levesswe** [comment]
I am actively working on an Anoka County version.  I would say about 75% done.

**Comment by levesswe** [comment]
As I mentioned in the pull request, while this script does not do all that was requested, it is a good first step that can be enhanced.  I intend to post instructions shortly so you can see what it can do.  However, we may want to discuss the mod worker dropdown that is currently hard-coded with Anoka County info and determine if that should be a global variable or some other device.  @MN-Script-Team/prism-scriptwriters

**Comment by levesswe** [comment]
Instructions are uploaded. @MN-Script-Team/prism-scriptwriters

**Comment by KallistaImdieke** [comment]
Has this one been pulled in for testing?

**Comment by theVKC** [comment]
Not yet. It appears to be open. I believe I requested a couple of changes.

**Comment by KallistaImdieke** [comment]
Perfect!  Thanks!

**Comment by levesswe** [comment]
I uploaded a pull request with updates and bug fixes.

**Comment by theVKC** [comment]
@gretchent74 and @heatherallen have volunteered to coordinate some testing of this new script which is working exceptionally well in Anoka County.

**Comment by heatherallen** [comment]
After testing this a little bit this morning just a few things I noticed....
1. When I check to send child care verification, the script opens a word doc to search and find the county specific child care verif, but I get the error message and it stops the script (Script Error at Line 1, Column !; This file could not be found.)
2. The workers drop down has just Anoka County names, so I think we should be able to either type the worker name or worker names should be a part of our global variables.
3. I'm not sure what Special Services Assessment is? is that a Anoka county specific thing?

**Comment by levesswe** [comment]
To answer your questions, yes this is an "Anoka-only" script in its current state.  

The script does make use of Word documents that would need to be saved in your word-documents-for-script-use-folder, and if you don't have the template saved there, it makes sense that you will see an error message.  Also, if your child care verification form has different fields than ours, you may also have error messages.  The Special Services Assessment is an Anoka-specific document.
 
The worker dropdown has Anoka workers hard coded, so we do need to discuss what we want to do with that to make this a more global script.    @MN-Script-Team/prism-scriptwriters, we will need to entertain discussion on what you want to see happen with making this a collaborative script.  

We can replace the hard-coded dropdown with global variables however, if we all are using different Word documents and possibly different dialogs, too (to remove the Anoka-specific Special Services Assessment, for example), maybe the better course of action is to make this a script where if County = Anoka then do this, or if County = Scott, then do this.  This second approach is especially helpful to accommodate situations where counties have very different child care verification forms with different fields of information pulling into them.  

I think we need some more collaborative discussion on what the group would like to see happen - maybe something to discuss at a Hackathon, @theVKC?

**Comment by theVKC** [comment]
@levesswe, I didn't catch that the workers were hard coded. That is unlikely to be possible to accomodate in global variables as some agencies are larger than others, and turnover is often challenging from a coding perspective. In some larger counties keeping a list updated could become a full time job.

Choices from here:
1. Remove the script entirely
2. Remove the part with a specific worker

If you can please in the future indicate that there is county-specific code in your pull request, that'd be great, as I can evaluate that with a different rubric.

**Comment by levesswe** [comment]
@theVKC, in no way did I expect that this script was ready as a collaborative script.  Although I asked for feedback on January 26, 2017, on how we wanted to make this collaborative script, I didn't get any feedback.  I thought this period of testing was the opportunity to solicit the feedback needed to move forward with making this a collaborative script, since people tend to provide better feedback once they try it out.  Sorry if you didn't follow my thought process.  Personally I support option 3, but again, we need to know what that collaborative version would look like for other counties, and I am still awaiting feedback on what other counties would like to see.  We've only heard from Scott County.  Heather proposed using edit fields to put in the worker name and phone - that could work.  Or remove the update worker functionality.  This is really about what the collaborative wants the script to do, and I don't think we have heard enough from other counties to say definitively what would be the best course of action. I am fine with modifying this script to be a collaborative script - but I really need direction here to know how the collaborative would like their version.  We are already using this script locally, so it doesn't really matter to us if you remove it from Github; except that @KallistaImdieke may want it in order to expand it to add enhancements to it.

**Comment by theVKC** [comment]
I like the editbox field option myself. Anoka could work in an "if county = Anoka then replace this with a dropdown" type of thing, and then if other counties get on that they could do the same, but it'd be the type of thing that only scriptwriting counties can do, and not hard-configured for all.

**Comment by theVKC** [comment]
I've moved this back to the feedback list. @levesswe, let me know if you aren't hearing the feedback you need to make a call on this, and I'll close it at that point. I'd like to try and have a decision on it in the next week, in time for the next big release sync.

**Comment by jannellstearns** [comment]
As indicated in the initial post to this issue, Stearns provided some feedback on what they would like to see on the script.  I missed the request for additional feedback -  since this is a very long thread, here is what I initially posted:

I am not a script writer, but would like to see a script that would generate the REAM screen to send out modification documents, send employer verifications to any open employers on the CP/NCP employer screen and transfer the case to the modification prep position number. I have attempted to write the flow for the potential script, but I may have missed something:

Modification Document Generation Script:

Go to CAAS and modify to correct position number
• (03, 029) M
• (11,020) Correct team needs to be selected
• (12, 020) correct position needs to be selected
• 

Go to REAM screen to start modification
• (03, 029) A
• (04, 035) F1 to select current charging order based on NCOL
• (10, 015) populate with today’s date in format mm/dd/yyyy
• (12, 017) select who is requesting modification (CP/NCP/AGE/OTH)
• (13, 019) Request reason for modification (from list in REAM screen F1)
 o CCC COUNTY AWARE OF POSSIBLE CHANG
 o CHD CHILD DISABLED
 o CIC CHANGE IN CIRCUMSTANCES
 o CUR CHILD CARE SUPPORT NEEDS TO BE
 o DCI DISTRICT COURT ISSUES
 o EMC EMANCIPATION OF CHILD(REN)
 o INC NCP INCARCERATED
 o JOI NUMBER OF JOINT CHILDREN CHANG
 o MED MEDICAL SUPPORT NEEDS TO BE ES
 o OTH OTHER REASON - WORKER TO TYPE
 o PAR PARENTING TIME CHANGED
 o PCT THE EXISTING SUPPORT ORDER IS
 o PER FEDERAL LAW REQUIRES PERIODIC
 o REQ COURT ORDER REQUIRES REVIEW AN
 o RPA NCP RECEIVES PUBLIC ASSISTANCE
 o SIM STREAMLINED INCARCERATED MOD
 o SSA NCP RECEIVES SSI OR RSDI
• 

Go to NCIL
• Send DORD F0405 (employer verification form) for any employers without an End date -- MCI based document
 Go to CPIL
• Send DORD F0405 (employer verification form) for any employers without an End Date – MCI based document
 Stearns would like to see:
• Word document template for Daycare Provider Financial Statement be generated on each modification request as selected. We have a non-letterhead version we would be willing to share if other counties see benefit in using this as well.

**Comment by gretchent74** [comment]
I ran the script but received an error.  The date is 4/11/2017 so it is causing the error when adding the cawt note.  (missing the 0, 04/11/2017.

**Comment by levesswe** [comment]
LOL, apparently not!  I will fix that as I work on making this a collaborative script!  Thanks!

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323
