### ISSUE TITLE
New Script Idea -Post Order letters

### ISSUE THREAD

**Issue by Mkreger9** [MN-Script-Team/DHS-PRISM-Scripts#437]
A script that would collect information after the court order has been loaded onto PRISM. This info would be used to create Word letters to be sent to the parties. It would also create an "court order loaded" CAAD note that details the court ordered obligations. 

I would like to be assigned this.

**Comment by theVKC** [comment]
@Mkreger9, you lost your assignment ability because of a glitch from the transfer to the new locale. I know you're assigned this, I'll investigate why this happened and see if I can re-invite you to the organization.

**Comment by theVKC** [comment]
@Mkreger9, can I get an update on this one?

**Comment by theVKC** [comment]
Per @Mkreger9, this will not be done in time for this release. I am removing it for now, I presume we may know more at the next hackathon (Monday at DHS).

**Comment by Mkreger9** [comment]
issue #451 should resolve this

**Comment by theVKC** [comment]
@Mkreger9: this isn't the script you've been working on at hackathon, is it? Are you suggesting the unified intake script will resolve this, so we should be able to close it?

**Comment by theVKC** [comment]
Because I haven't heard back from @Mkreger9, closing backlogged issue.

**Comment by theVKC** [comment]
Assuming it's a duplicate that is tied to #451.
