### ISSUE TITLE
ACTION - UN/UN Docs

### ISSUE THREAD

**Issue by gretchent74** [MN-Script-Team/DHS-PRISM-Scripts#441]
Enhancement to add obligation amount to  jude, ncod, obbd.  I am hoping to work on this in the next few months.  Please assign to me.

**Comment by theVKC** [comment]
@gretchent74, we talked about this on the call, but I'm not sure if you heard this...

We'd like to separate the "sending docs" from the "received docs" part. Can you take that part as well?

**Comment by gretchent74** [comment]
Yes.  Thank you.

**Comment by gretchent74** [comment]
@theVKC  I am wondering if you received my updated pull requests (yesterday) for these 2 scripts and if I did it correctly or not.  Thank you.

**Comment by theVKC** [comment]
Did you see my email this morning? Closing all pull requests until after #563 is resolved.

**Comment by gretchent74** [comment]
So then I will have to try it again when you let us know we can?

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
You will. No worries though, I should have detailed instructions when the time comes!
