### ISSUE TITLE
Idea: DORD blacklist

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#445]
So, after meeting with counties, I've been mapping this out in my head. I think I have enough background knowledge to be comfortable formally discussing it.

I'd like to create an optional DORD blacklist, in conjunction with our Word document generation details. Here's how it will work (in my mind):
1. Scripts that send a notice via DORD continue to do so.
2. If an individual county does not want to use that DORD doc (i.e. they have another document in Word they'd like to use), the county runs a "DORD blacklist" utilities script which adds that DORD doc to a text file (along with a link to the preferred document).
3. FuncLib functions for autofilling DORD docs contain logic to review the blacklist.
4. If the DORD-to-be-blacklisted is present in that document, the DORD document instead loads the Word document.

I believe, based on feedback received during my county meetings, this will be popular. But I'd love to hear from @MN-CS-Script-Team/prism-scriptwriters and @MN-CS-Script-Team/prism-supervisors about it. #FeedbackMakesMeHappyFolks

If this is a go, I'll make a FuncLib issue to address the functions piece, and this issue will address the UTILITIES script to update the blacklist.

**Comment by lisamorrishelm** [comment]
I love this idea Veronica!

**Comment by KallistaImdieke** [comment]
I love this Idea too!!

**Comment by theVKC** [comment]
I don't think this will be possible to complete before the initial release. But, it is possible to complete.

I'm going to prioritize blacklisting for testing during the October release cycle. Removing from v2016.09.
