### ISSUE TITLE
NEW SCRIPT - Case Closing Uncollectable

### ISSUE THREAD

**Issue by jlmartinone** [MN-Script-Team/DHS-PRISM-Scripts#449]
A script that creates a CAAD note when you are closing a case as being uncollectable.  The note would include the date of the last payment (PALC), the date youngest child emancipated, all of the remedies that have been running (ENFL).  If the NCDD has no address it could list that too.  If there is a CTM order on SUOL/SUOD it could list that also and state it was unsuccessful.

**Comment by theVKC** [comment]
Do you want this one @jlmartinone?

**Comment by theVKC** [comment]
@jlmartinone, I think you wanted this one, but now I forgot. I'm going to add you, let me know if I shouldn't add you. :)

**Comment by theVKC** [comment]
@jlmartinone, any chance this can get done before MFSRC?

**Comment by theVKC** [comment]
@jlmartinone, any chance I can get an update on this one from you? If you don't think it can be done by September 30, I might kick it to the following release.

**Comment by theVKC** [comment]
Haven't heard, so I'm removing it from the September release and moving it to October. @jlmartinone, I'm leaving it assigned to you. Let me know if you want me to unassign it or close it.

**Comment by jlmartinone** [comment]
I have started working on this.  Just a FYI.

**Comment by theVKC** [comment]
Good deal. Thank you!!

**Comment by theVKC** [comment]
@jlmartinone: can I get an update on where you're at with this one? You said you started working on it, so I just want to know. It's marked as "backlogged" for now and if you don't have an ETA I'll close it as a "sleeper" (sleepers can be reopened if you get time/interest again).

**Comment by theVKC** [comment]
Per @jlmartinone, we can close this one.
