### ISSUE TITLE
New utilities script: update global variables

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#450]
This is a port of a MAXIS script I was working on, but it will be helpful. Users can update their Power Pads or other global variables settings (like judges and whatnot) with a script instead of using code. This will be very helpful for agencies without scriptwriters.

I will be taking this one and hoping to release it this month.

**Comment by theVKC** [comment]
@CDPotter and I have worked out a deal: I complete the MAXIS web-based script installer in exchange for Charles completing this work. Go Charles!

**Comment by theVKC** [comment]
I'll be jumping in to help with this, as Charles will also be working on the MAXIS form stuff. :)

**Comment by theVKC** [comment]
@CDPotter: is your work for this somewhere on GitHub? A gist or a branch somewhere?

**Comment by CDPotter** [comment]
@theVKC I missed this message entirely. It was not but is now. https://gist.github.com/CDPotter/8f4211ee330804783cd6d7f2ad7f7f59

I haven't made much progress on it as turning it into a function seemed to muck up some of the functionality of it, and I've never been able to get the download of the powerpad to work.
