### ISSUE TITLE
Hackathon subject: one Intake to rule them all

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#451]
We're doing it on Wednesday 09/07/2016. We will be evaluating all of the various "intake" scripts to see if we can consider merging them. :)

**Comment by theVKC** [comment]
The SHARING-IS-CARING intake script can be found here: https://github.com/MN-CS-Script-Team/PRISM-Scripts/blob/v2016.08a/Script%20Files/SHARED-CODE/ACTIONS%20-%20INTAKE.vbs

**Comment by theVKC** [comment]
The following scripts may be involved:

* ACTIONS - EST DORD NPA DOCS
* ACTIONS - ESTB DORD DOCS FOR PA CASE
* ACTIONS - GENERIC ENFORCEMENT INTAKE
* ACTIONS - INTAKE (in SHARING IS CARING)
* NOTES - MES FINANCIAL DOCS
* NOTES - INTAKE DOCS RECEIVED

It will be fun to try and merge these, if we can. At the least, we should evaluate when to use which and for what. :)

**Comment by theVKC** [comment]
ACTIONS - ENFORCEMENT INTAKE has Anoka Word docs in it, and that should be fixed to work with GlobVar.

**Comment by khiestand** [comment]
```vb.net
BeginDialog Establisment_case_initiation_dialog, 0, 0, 381, 395, "Establishment Case Initiation"
  EditBox 80, 25, 90, 15, prism_case_number
  CheckBox 15, 70, 100, 15, "Financial Statement (F0021)", financial_stmt_cp_check
  CheckBox 15, 85, 80, 15, "Cover Letter (*.docx)", Cover_letter_cp_check
  CheckBox 15, 100, 125, 15, "Waiver of Personal Service (F5000)", Waiver_cp_check
  CheckBox 15, 115, 120, 15, "Parenting Time Calendar (*.docx)", calendar_cp_check
  CheckBox 15, 130, 100, 15, "Past Support Form (*.docx)", Past_support_cp_check
  CheckBox 15, 145, 110, 15, "Child Care Expenses (*.docx)", daycare_checkbox
  CheckBox 15, 160, 110, 15, "Medical Opinion Form (*.docx)", Check18
  CheckBox 15, 175, 105, 15, "Statement of Rights (F0022)", Check19
  CheckBox 15, 190, 105, 15, "Your Privacy Rights (F0018)", Check20
  CheckBox 205, 70, 105, 15, "Financial Statement (F0021)", financial_stmt_ncp_check
  CheckBox 205, 85, 80, 15, "Cover Letter (*.docx)", cover_letter_ncp_check
  CheckBox 205, 100, 130, 15, "Waiver of Personal Service (F5000)", waiver_ncp_check
  CheckBox 205, 115, 120, 15, "Parenting Time Calendar (*.docx)", calendar_ncp_check
  CheckBox 205, 130, 100, 15, "Past Support Form (*.docx)", past_support_ncp_check
  CheckBox 205, 145, 110, 15, "Medical Opinion Form (*.docx)", med_opinion_ncp_checkbox
  CheckBox 205, 160, 105, 15, "Statement of Rights (F0022)", stmt_right_ncp_checkbox
  CheckBox 205, 175, 105, 15, "Your Privacy Rights (F0018)", priv_rights_ncp_checkbox
  CheckBox 205, 190, 145, 15, "Authorization to Collect Support (F0100)", auth_collect_ncp_checkbox
  CheckBox 205, 205, 160, 15, "Notice of Parental Liability for Support (F0109)", par_lia_ncp_checkbox
  CheckBox 205, 220, 150, 15, "Notice of Medical Support Liability (F0107)", par_med_liab_ncp_checkbox
  EditBox 105, 340, 65, 15, return_date
  EditBox 105, 360, 65, 15, worker_signature
  ButtonGroup ButtonPressed
    OkButton 255, 370, 50, 15
    CancelButton 315, 370, 50, 15
  GroupBox 195, 55, 170, 185, "Documents Sending to NCP:"
  Text 20, 345, 80, 10, "Requested Return Date:"
  GroupBox 10, 55, 170, 155, "Documents Sending to CP:"
  Text 10, 10, 105, 10, "Establishment - Case Initiation"
  Text 30, 365, 70, 10, "Sign your CAAD Note:"
  Text 10, 30, 70, 10, "Prism Case Number:"
EndDialog
```

**Comment by khiestand** [comment]
That is what I have so far for the dialog

**Comment by KallistaImdieke** [comment]
Hey @khiestand here is my dialog box Thanks!

```VB.net
BeginDialog CS_intake_dialog, 0, 0, 371, 365, "CS intake dialog"
  CheckBox 15, 50, 145, 10, "Case Opening - Welcome Letter", NCP_welcome_ltr_check
  CheckBox 15, 80, 140, 10, "Court Order Summary", ncp_court_order_summary_check
  CheckBox 15, 90, 115, 10, "DORD F0021 Finacial Statement", NCP_Finacial_Statement
  CheckBox 15, 105, 150, 10, "DORD F0924 - Health Insurance Verification", NCP_health_ins_verif_check
  CheckBox 15, 120, 120, 10, "Notice of Arrears Reported", arrears_reported_check
  CheckBox 200, 95, 65, 10, "DORD F0100", dord_F0100_check
  CheckBox 200, 125, 65, 10, "DORD F0109", dord_F0109_check
  CheckBox 200, 150, 60, 10, "DORD F0107", dord_F0107_check
  CheckBox 190, 50, 130, 10, "Case Opening - Welcome Letter", CP_welcome_ltr_check
  CheckBox 190, 65, 120, 10, "DORD F0021 Finacial Statement", NCP_finacial_statement
  CheckBox 15, 65, 130, 10, "Child Care Verification", child_care_verif_check
  EditBox 15, 185, 140, 15, t_30_day_cawd_txt
  EditBox 15, 240, 140, 15, t_60_day_cawd_txt
  EditBox 240, 280, 110, 15, worker_name
  EditBox 240, 300, 110, 15, worker_phone
  EditBox 90, 335, 90, 15, worker_signature
  ButtonGroup ButtonPressed
    OkButton 255, 335, 50, 20
    CancelButton 310, 335, 50, 20
  Text 15, 340, 70, 10, "Sign your CAAD note:"
  Text 195, 85, 30, 10, "NPA"
  Text 195, 110, 95, 10, "MFIP, DWP, CCA"
  Text 195, 140, 35, 10, "MA only"
  Text 185, 305, 50, 10, "Worker phone:"
  Text 185, 290, 50, 10, "Worker name:"
  GroupBox 190, 180, 170, 35, "File Location on CAST"
  GroupBox 185, 35, 170, 135, "Letters to NCP"
  GroupBox 10, 35, 170, 100, "Letters to CP"
  Text 5, 0, 325, 10, "Motion to Set Case Initiation"
  GroupBox 5, 145, 175, 175, "CAWD notes to add"
  EditBox 15, 295, 120, 15, add_caad_txt
  Text 15, 280, 85, 10, "Worklist Text"
  EditBox 205, 195, 65, 15, Edit7
  Text 5, 15, 50, 10, "Case Number"
  EditBox 60, 10, 190, 15, Edit8
  Text 15, 160, 80, 10, "Calendar days until due"
  EditBox 95, 155, 70, 15, Edit9
  Text 15, 175, 55, 10, "Worklist Text"
  Text 15, 210, 80, 10, "Calendar days until due"
  EditBox 100, 205, 60, 15, Edit11
  Text 15, 225, 55, 10, "Worklist Text"
  Text 15, 265, 80, 10, "Calendar day until due"
  EditBox 95, 260, 60, 15, Edit12
EndDialog
```

**Comment by khiestand** [comment]
![capture](https://cloud.githubusercontent.com/assets/10159902/18323011/3508ad4e-74fb-11e6-8849-c373867ef261.PNG)

**Comment by heatherallen** [comment]
![capture](https://cloud.githubusercontent.com/assets/17319472/18323034/541c0be0-74fb-11e6-86c9-58284661cabe.PNG)

**Comment by KallistaImdieke** [comment]
![capture](https://cloud.githubusercontent.com/assets/19214103/18323064/7789b398-74fb-11e6-842c-826882c5184c.PNG)

**Comment by TammyStearns** [comment]
![capture](https://cloud.githubusercontent.com/assets/11429444/18323103/a9e20340-74fb-11e6-807c-8e4e184e55a8.PNG)

**Comment by KallistaImdieke** [comment]
![capture2](https://cloud.githubusercontent.com/assets/19214103/18323446/3f5c3d22-74fd-11e6-9661-e1872096cd4e.PNG)

**Comment by margmac17** [comment]
When I select or drag these over it constantly says "Uploading your files" and it just continually spins so I am not sure if they actually are getting across to here!
[Aff Marriage from Another County.dotx.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/462368/Aff.Marriage.from.Another.County.dotx.docx)
[Day Care Provider Financial Statement.dotx.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/462371/Day.Care.Provider.Financial.Statement.dotx.docx)
[EST - CP Cover Letter for Fin Stmt-Eng.dotx.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/462372/EST.-.CP.Cover.Letter.for.Fin.Stmt-Eng.dotx.docx)
[EST - Paternity Questionnaire ltr.dotx.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/462373/EST.-.Paternity.Questionnaire.ltr.dotx.docx)
[EST - Supplemental Statement CP.dotx.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/462374/EST.-.Supplemental.Statement.CP.dotx.docx)
[Medical Opinion.dotx.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/462375/Medical.Opinion.dotx.docx)
[Paternity Questionnaire 2015.dotx.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/462376/Paternity.Questionnaire.2015.dotx.docx)

**Comment by TammyStearns** [comment]
I can send these to you as attachments to your e-mail if you think that would work.

**Comment by theVKC** [comment]
I can see them @margmac17! :)

Tammy, either way you want to do it is fine by me.

**Comment by margmac17** [comment]
Chris got them by email yesterday and we went through and coded them so I have them in a file on my desktop (the original word docs).  For some reason my computer just kept saying "uploading files" but it must have worked then!

**Comment by TammyStearns** [comment]
Is there a problem with your computer or where/how they were saved?

**Comment by margmac17** [comment]
They were all protected WORD docs so we removed the protection to edit them with coding and then saved them again as a new WORD docs. No difference with the one you just sent (Paternity Form).

**Comment by TammyStearns** [comment]
Hmmm.  Not sure what is happening then.  You may want to check with your IS Dept?

**Comment by margmac17** [comment]
Can you try clicking on the WORD DOCS above to see if they open for you. (You have to click on the open button at the bottom of your computer).  They appear to be there on GitHub in the cloud it says.

**Comment by TammyStearns** [comment]
Hi Margaret – I am having trouble getting into GitHub right now.  I did click on the Word Docs before that you listed and I could open them.

**Comment by theVKC** [comment]
@khiestand: remind me... are we removing ESTB DORD DOCS FOR NPA CASE and ESTB DORD DOCS FOR PA CASE because of our work on one-intake? Doesn't the establishment track cover this?

**Comment by margmac17** [comment]
yes, I thought that was the case that they would be put into the new "intake" script.

**Comment by theVKC** [comment]
I am operating on that assumption based on my notes. However, I just wanted to make sure before I start building and detailing new instructions... :)

**Comment by khiestand** [comment]
Yes agree with Margaret

**Comment by theVKC** [comment]
I put together a document:
[docs the intake script sends.xlsx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/488539/docs.the.intake.script.sends.xlsx)

This shows all documents that the intake script sends. It's a lot!

I've just standardized the variables and document names across all dialogs. Now I just need to import the docs and it's a wrap!

**Comment by KallistaImdieke** [comment]
@theVKC I am looking at this script again to try and finish my section of it but one of the documents that I need to pull information into is the "Welcome Letter" and I do not believe I have a copy of this in order to know what needs to be pulled into it.  Can I get a copy from someone so that I am able to proceed on this script :-)  Thanks!
