### ISSUE TITLE
New script and button for Power Pad: "Quick CAAD"

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#453]
Here's the idea. You can store locally (ala Worker Signature) your favorite CAAD notes, and the script will generate a menu with buttons that automatically update when you indicate new favorites.

On it.

---

Note 08/26: per yesterday's meeting, this means we can retire:
- NOTES - COURT ORDER REQUEST
- NOTES - CSENET INFO
- NOTES - FRAUD REFERRAL
- NOTES - WAIVER OF PERSONAL SERVICE

So, remove those scripts as well! I'm going to try and expedite this one because of the need for a new Power Pad to support it. :)

**Comment by theVKC** [comment]
Also, include searchability feature to enable easy CAAD finding in the script which updates your favorites. CAAD codes change infrequently.

**Comment by theVKC** [comment]
FYI @khiestand, since I know you were going to be using this script: this will be completed today if I'm lucky. I'd love it if you could test it for me!!!

**Comment by theVKC** [comment]
OK folks, I'm reopening this issue per our new guidelines which suggest issues should stay open until documentation is wrapped. Luckily, because there are two enhancements suggested for this, I can close those issues as well to make up for this:

* #503: update setcursor placement
* #504: tie in current scripts

So, closing those two and reopening this one. When these issues get resolved, I'll update instructions and send it on its merry way.

**Comment by khiestand** [comment]
I have a worker who has entered 12, and it cuts off after that. Does the dialog box need to be bigger? Or is there a limit to only 12 "favorites"? Also, she was able to enter one that was already saved. Is there logic that could be coded to have a message box pop up if that caad code is already in their favorites?

**Comment by theVKC** [comment]
I could easily make the dialog bigger, or maybe even dynamic. And logic to check an existing CAAD code shouldn't be too hard.
