### ISSUE TITLE
Enhancement to Find Name on CALI: add search on phone number to NCED

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#458]
@TammyStearns is taking this one. Thank you Tammy!

**Comment by TammyStearns** [comment]
This is going to take longer then expected in looking at the MAXIS script that I am following.  I do not expect to have this ready within coming week.  Thanks.

**Comment by theVKC** [comment]
@TammyStearns: can I get an update on where this is at? It's an old issue. We can either mark it as a sleeper now, or we can move it to "help wanted" and wait a couple of weeks to see if anyone else is interested.

**Comment by TammyStearns** [comment]
Either way is fine with me.  I am ok with marking it as a 'sleeper' for now.  Thanks.

**Comment by theVKC** [comment]
Consider it done!
