### ISSUE TITLE
Enhancement to DDPL Calculator: split custodial parent's separate cases in the calculation

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#459]
@levesswe is taking this one on. Thank you Wendy!

**Comment by theVKC** [comment]
@levesswe, can I get an update on this one?

**Comment by levesswe** [comment]
Haven't even started it.

**Comment by theVKC** [comment]
@levesswe: this has been "on the radar" for a while. We have a couple of choices:

1. I can reassign it as "help wanted" and we can wait a couple of weeks, then if anyone takes it we can close it as a "sleeper".
2. I can mark it as a "sleeper" and close it now, and we can reopen it if there's interest from you later on.

Can you get back to me ASAP? Trying to reduce the issue list overhead.

**Comment by levesswe** [comment]
Sounds good to me.  Either option is fine.
