### ISSUE TITLE
Affidavit of Service by Mail Docs: bug fix

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#463]
The script may have a v6.0 issue with the MsgBox asking the user to select a legal heading. v6 BlueZone users cannot edit the window while MsgBoxes are up. Our solution (as discussed at the 08/25 meeting) is to try to dynamically determine the possible legal headings, then allow that to be selected within a dialog.

@gretchent74 volunteered. Yay!

**Comment by theVKC** [comment]
@gretchent74, can I get an update on this one?

**Comment by theVKC** [comment]
@gretchent74, any chance I can get an update on this one from you? Since this is a bug, I might try and take it if you don't think you can do it by next Friday. I'd like to get the bugs resolved ASAP, for obvious reasons. :)

**Comment by gretchent74** [comment]
My plan was to ask you some questions on this one and the un/un docs that I am almost done with on 09/26/2016 at the meeting.

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
Good deal, thank you!
