### ISSUE TITLE
ANOKA SANCTION: state-ify it with email

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#464]
Here is our idea: instead of the script sending a Word doc which gets emailed, have it just load up an email object using automation. Then the user can just pick who they want to send it to.

@KallistaImdieke has volunteered. This would make the script change names, it'd be "ACTIONS - SANCTION". She'll change the name as well when submitting it.

**Comment by theVKC** [comment]
So @KallistaImdieke, there is a glitch on one of these functions. `send_text_to_DORD` should be renamed as `write_variable_in_DORD`. While you're doing the Outlook work, can you also find-replace that line?

This ties into #489, but I didn't want to do it while you might be working on it (that creates a merge conflict and can mess things up for us).

**Comment by theVKC** [comment]
Hey @KallistaImdieke, do you want me to take this one on? Since you've already got some other Word-doc related issues, perhaps I can take this one (Outlook stuff) off your plate, and then document the process as I go. Eh?

**Comment by KallistaImdieke** [comment]
If you would like go for it!

Thanks!

**Comment by theVKC** [comment]
I've decided to move this over to the bug column since it isn't currently working.
