### ISSUE TITLE
ACTIONS - NON PAY: enhance with extra documents at the end

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#465]
This was discussed at yesterday's event. I believe @levesswe had ideas for what docs she'd like to add. If you can elaborate here on GitHub, that'd be wonderful. :)

**Comment by levesswe** [comment]
Here are Anoka Word Docs used in the Anoka County version of the script:

[Initial Contempt Docs.zip](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/448059/Initial.Contempt.Docs.zip)
