### ISSUE TITLE
Replace current NOTICE OF CONTINUED SERVICE with Ramsey's original vision of it

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#466]
Update 09/29/2016: after hearing from lots of counties, we're moving ahead with switching to Ramsey's version instead of the current version. @heatherallen is spearheading this script, hopefully, live mid-October for the October release.

---

This is an offline conversation I'll have with Heather from Scott County (not sure if she's on GitHub yet).

Ramsey County built a version of this script that Heather says does a lot more. We'll discuss at a separate meeting and consider incorporation of that script into the project. That would retire NOTICE OF CONTINUED SERVICE. I'll work with Heather to get that done. :)

**Comment by theVKC** [comment]
@heatherallen, can we set up a date to go over this one? Preferably sometime in the next couple of weeks.

**Comment by heatherallen** [comment]
@theVKC, I would love to go over this with you.  What days work better for you?

**Comment by theVKC** [comment]
How about the 22nd or 23rd?

**Comment by heatherallen** [comment]
Let's do the 23rd as I have court on the 22nd.  Did you want to meet somewhere or try to do over the phone?

**Comment by theVKC** [comment]
I'd be happy to meet at Scott County, DHS, or anywhere in between. Can we do the afternoon?

I can pretty easily reserve us a room here, but the parking is often challenging. If you don't get reimbursed for parking/mileage, I'm happy to come to you.

**Comment by heatherallen** [comment]
I will check with my supervisor when she gets back tomorrow and we can narrow down the location.

**Comment by heatherallen** [comment]
Veronica and I met today and compared the Ramsey County NOCS script vs. the current NOCS script.  I feel that the Ramsey County one runs with fewer clicks and processes the worklists in bulk instead of going through each individual case.  What are people's thoughts? @MN-Script-Team/prism-scriptwriters

**Comment by TammyStearns** [comment]
If Ramsey County's NOCS script is basically the same (or better) than the one on Bulk Scripts, but runs with fewer clicks and processes more in a 'bulk manner' then we should consider replacing the current script with Ramsey's version.

**Comment by paschell** [comment]
I agree.   The procedure on DHS/Sir is simple - Send the Notice upon getting a PA to NPA Program Change.  I don't believe we need to have all the bells and whistles that were added to the NOCS script we have out there now.  I saw Ramsey's a long time ago and liked it.

**Comment by theVKC** [comment]
@heatherallen, if we go the route of modifying the wonderful Ramsey NOCS script, we'll need to replace the existing standard BlueZone functions with the collaborative-supported FuncLib functions. I'll be happy to assist if we go this route.

Also, for what it's worth, I fully support moving this over to a version with less clicks required per script run. I also think it would be swell to add Excel functionality for logging what was purged. Per Heather, this is working wonderfully without errors in Scott County, has been for a while. She has volunteered to take on the work of migration, I'd just like to get a couple more opinions first before she begins. :)

**Comment by RoberT-1000** [comment]
Yes! Do it. We had to jump through those hoops to get it approved initially (long story) but this script should always have been the Ramsey version.

**Comment by theVKC** [comment]
Well, I think there's pretty broad consensus here. @heatherallen, let's do it!

**Comment by RoberT-1000** [comment]
I was going through the issues list. I thought that @wrightcountykaren had a copy of the original script.

**Comment by wrightcountykaren** [comment]
I’m not sure that I had an original of that script.  Jovann had shared several scripts with us last year, but I just can’t remember if that is one of them, and I can’t find the code anywhere on our network.  Sorry I can’t be of more help Robert.

Karen Popken
Wright County Child Support Supervisor
Phone: 763-682-7403
How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by RoberT-1000** [comment]
No worries! For some reason, I thought you had the source code a while back.

**Comment by heatherallen** [comment]
@RoberT-1000 Scott County has the code and I'm in the process of updating it.

**Comment by theVKC** [comment]
Still need testers for this. Can we confirm this is now working? Need two agencies to confirm.

@MN-Script-Team/prism-scriptwriters?

**Comment by paschell** [comment]
I have used this script - works perfect.  ANOKA gives a thumbs up!

**Comment by theVKC** [comment]
Thanks as always @paschell!

**Comment by heatherallen** [comment]
Scott County workers will most likely be using this at the beginning of December when we get the worklist.  I can report back.

**Comment by theVKC** [comment]
Please do, @heatherallen! Although since you are the "original scriptwriter" (remember you added an Excel function) your test doesn't count (need someone outside your agency).

**Comment by theVKC** [comment]
OK, I'm going to start picking on counties. @MN-Script-Team/prism-wright, can you test this and make sure it's working?

**Comment by theVKC** [comment]
(@wrightcountykaren: Heather's version takes the original Ramsey County code and adds Excel functionality)

**Comment by WCMattAnderson** [comment]
Just an FYI @wrightcountykaren - Wright Co has the following script backups as of today:

6-12-2014
7-15-2014
8-10-2014
1-30-2015
11-14-2016

**Comment by wrightcountykaren** [comment]
I will have a couple people test this script in the beginning of Dec when the worklist will re-appear.  I should be able to respond by next week.

**Comment by theVKC** [comment]
Good deal! Thank you for taking it!

**Comment by theVKC** [comment]
@wrightcountykaren has confirmed this is working. Now, for instructions! @heatherallen, can you modify the instructions that are in SIR to reflect this new version of the script?

**Comment by heatherallen** [comment]
@theVKC yes I will update the instructions hopefully this week.

**Comment by theVKC** [comment]
Beautiful. Thank you!!!!

**Comment by heatherallen** [comment]
@theVKC, I was going to update the instructions but I don't see them on SIR.  Are they hiding somewhere?

**Comment by theVKC** [comment]
Apparently they do not exist. I would presume @RoberT-1000 or @levesswe or @paschell might have a local copy from Anoka. But, it needs to be updated to meet the DHS-SIR Word doc format.

**Comment by heatherallen** [comment]
Ok sounds good! It may just be easier to just start from scratch since the new script is a bit different than the old. Thanks.

**Comment by paschell** [comment]
@heatherallen - I found some instructions on our OneNote.  I would agree that starting from scratch would be far easier than trying to update what we have here.  I don't believe we had or have the Ramsey instructions.

**Comment by heatherallen** [comment]
Instructions complete!

**Comment by theVKC** [comment]
Approved! THANK YOU @heatherallen! You're the heroine of the week! :)
