### ISSUE TITLE
Make one COMPANION CASE FINDER script instead of two

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#467]
It could be a simple prompt to see which one you should use.

@khiestand has volunteered to take this on. Yay!

**Comment by khiestand** [comment]
I have done everything I can on this, the CP companion case finder one is not pulling in.  Robert wrote this script and here is what he says about it:
It definitely doesn’t appear to be making a list of MCI numbers on the CP companion case finder. You can test this one on actual-factual PRISM…it just creates a list in Excel.
 
If you are going to combine them, then go with the NCP script. The only difference should be where the scripts read from – NCCB for the NCP Companion Case Finder and CPCB for the CP Companion Case Finder.

The button still needs to be made for this as well.

**Comment by theVKC** [comment]
I'll be taking it from here. Thanks for your help Kelly!

**Comment by theVKC** [comment]
@jlmartinone is taking this one on.

**Comment by jlmartinone** [comment]
@theVKC  please help! I put what I have on Gist. The CP is not working ...THANK YOU

<script src="https://gist.github.com/jlmartinone/0bede28398a3e174f38cfe67f3f43276.js"></script>

**Comment by theVKC** [comment]
https://gist.github.com/jlmartinone/0bede28398a3e174f38cfe67f3f43276 is this Gist, FYI.

**Comment by theVKC** [comment]
Sounds like a CP or NCP variable isn't being declared correctly, because the CP spreadsheet is blank.
