### ISSUE TITLE
REVW QW INFO - has loop bug that needs resolution

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#469]
Sounds like it doesn't always catch all the matches. @levesswe has volunteered. Thanks Wendy!

**Comment by theVKC** [comment]
@levesswe, can I get an update on this one?

**Comment by theVKC** [comment]
I'm going to take this one to expedite it.

**Comment by theVKC** [comment]
@levesswe, clearly I wasn't able to expedite this. Is there any way you can take a look at it sometime this week? If not, I'll mark as help wanted and throw to the team.

**Comment by levesswe** [comment]
I hope to spend more time on scripts in the next day or two, so you can assign to me.  I have uploaded a version of instructions as the script currently runs so they are out there (See #181), but I intend to do an overhaul, and the instructions will need to be re-written at that time.

**Comment by theVKC** [comment]
Thank you!!!

**Comment by theVKC** [comment]
Closing this issue since #181 is back open, and we don't need two tracking issues. @levesswe, please add #181 to any commits you make to fix this, not this old issue number. Thank you!
