### ISSUE TITLE
MOD CAAD NOTE - CONTACT CHECKLIST: two bugs

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#472]
Two bugs reported:

* `worker_signature` isn't working (UPDATE WORKER SIGNATURE isn't catching it). Variable might be named wrong. @KallistaImdieke is investigating.
* It might need the pass-through command to prevent annoying pop-ups when pressing cancel. Although, that could be in a function instead of in the script itself. I'll investigate that one.

**Comment by theVKC** [comment]
The CANCEL BUTTON SELECTED business was not found, meaning it's likely tied to a function from the old Functions Library (which is being phased out). So, that issue does not need to be addressed here. @KallistaImdieke has resolved the worker_signature business, so we're set!

**Comment by ChrisKast** [comment]
This script appears to still have a bug surrounding worker signature....

**Comment by KallistaImdieke** [comment]
I did just correct this yesterday morning at hackathon. I am not sure if the corrections have been pulled in yet??

**Comment by theVKC** [comment]
@KallistaImdieke, I'm wondering if your commit which added the logic in the dialog loop didn't sync.

**Comment by RoberT-1000** [comment]
The logic in the loop includes the variable `workers_signature` while the rest of the script uses `worker_signature`

**Comment by RoberT-1000** [comment]
![image](https://cloud.githubusercontent.com/assets/22157633/18483497/f1f340b0-79a9-11e6-95b1-39be37c5fcc1.png)

**Comment by KallistaImdieke** [comment]
Thank you I will correct this this afternoon

**Comment by theVKC** [comment]
I watched @KallistaImdieke commit that update though, so I think we didn't sync her branch before I accepted the pull request.

**Comment by KallistaImdieke** [comment]
I did a correction to where i found one more issue with it saying workers_signature I changed that and ran the script and it appears to be working now.
