### ISSUE TITLE
EMPLOYMENT VERIFICATION - Could an "End Date" be added to the Script Dialog Box

### ISSUE THREAD

**Issue by margmac17** [MN-Script-Team/DHS-PRISM-Scripts#484]
When updating CPID or NCID and the Employment Verification comes back as "Termed/No Longer Employed" an end date would be helpful to be added to the dialog.

**Comment by theVKC** [comment]
Great idea! Do you want it @margmac17? If not you, does anyone else want it?

**Comment by margmac17** [comment]
Yes, I can certainly try adding that “End Date” box to the dialog.
Margaret McCabe

**Comment by theVKC** [comment]
It's yours! Good luck! Let me know if you need any help!

**Comment by margmac17** [comment]
Running into a few problems on this one. Adding an "End Date" to the script dialog box is apparently not as easy as I thought it would be. I have been working on it this week and so far I cannot get the script to run properly and would need help to figure this out. I noticed that the "3 letter codes" are not in the script dialog box which means if you do not know the codes off the top of your head, you must go to Prism and F1 on the panel to see what they are and then back to the script to write in the correct code which does not seem like it is being efficient or time saving.

**Comment by theVKC** [comment]
@margmac17, do you think it would be possible to just add a blank "end date" field which simply adds to the note? I'm imagining you could probably get away with not including all of that programming logic for if this then that...

**Comment by margmac17** [comment]
If the CP or NCP no longer works there we have to enter the "end date" for that employer on the Prism panel (CPID or NCID) so just putting it in the note won't be enough. I think when the script was written it was intended for active employees not termed as it is quick and easy to add the term date to the Prism panel.

**Comment by theVKC** [comment]
Well then, I think we should probably work it in so that the script can handle more cases. But, what do you think @margmac17?

If you think we should add it, I'd be happy to set up a remote meeting to discuss the details and work with you on it. Otherwise, you could certainly wait until the next time you're at hackathon (although I don't like waiting). :)

**Comment by jlmartinone** [comment]
I can take this - I was thinking the same thing about an end date. I will update it on Monday 9/12/16.
Thanks!

**Comment by jlmartinone** [comment]
Enhancements done - added end date and term reason
