### ISSUE TITLE
Quick CAAD needs PRISM checking

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#485]
On it.

**Comment by paschell** [comment]
WHOA, this is cool, I tested twice today, will use more tomorrow.  So far I like it.  YAY!!  Haven't found any problems so far.  Did a search on the word "medical" and "drivers license" - I need to check if it pulled up everything.  I have not added frequent CODES  yet-.  Tomorrow.  Great work.  What is the problem/bug?

**Comment by theVKC** [comment]
It needs to check and see if you're in PRISM. I tried it while locked out and it didn't properly error out.
