### ISSUE TITLE
BUG: depreciated functions are persisting with new FuncLib call

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#489]
Error message "Script Error at Line 1, Column 1: Type Mismatch: 'write_new_line_in_PRISM_case_note'" 

Function call will need to be updated since the function was depreciated.

**Comment by KallistaImdieke** [comment]
Stearns county got a similar error message too on a different caad note. the following error message on the Notes- MOD CAAD NOTE – Contact checklist

[cid:image001.png@01D2039D.EB6884D0]

**Comment by theVKC** [comment]
`write_new_line...` is depreciated. It's `write_variable_in_CAAD` now.

**Comment by theVKC** [comment]
Wendy originally saw this on ANOKA SANCTION, but it is likely present in other scripts as well. I will investigate tomorrow morning, first thing.

**Comment by theVKC** [comment]
So, I am seeing the following scripts/functions:

* `write_editbox_in_PRISM_case_note` still exists in:
  * MOD CAAD NOTE - CONTACT CHECKLIST
  * PAY OR REPORT
* `write_new_line_in_PRISM_case_note` still exists in:
  * ANOKA SANCTION
  * COURT PREP WORKSHEET
  * ENFORCEMENT INTAKE
  * GENERIC ENFORCEMENT INTAKE
  * MOD CAAD NOTE - CONTACT CHECKLIST
  * PAY OR REPORT

These will all require updating, and I am hoping to complete it in the next half hour, @levesswe and @KallistaImdieke.

**Comment by levesswe** [comment]
Thanks, my people will be thrilled!  :)
