### ISSUE TITLE
Update to Quick Caad - SetCursor placement update

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#503]
SetCursor to the Caad lines on bottom of screen, it is currently set to the Action button on the top.

I can take this one.

**Comment by theVKC** [comment]
@khiestand, since I have #504, mind if I just take this one too?

**Comment by khiestand** [comment]
Please go right ahead!

**Comment by levesswe** [comment]
I was testing this script and noticed that if you enter the CAAD code with a lower case letter, the dialog doesn't find it.  This is a quick fix you can make while you are in there, @theVKC.  Just Ucase the string the user types in for the comparison.
