### ISSUE TITLE
NOTES-COURT PREP WORKSHEET

### ISSUE THREAD

**Issue by paschell** [MN-Script-Team/DHS-PRISM-Scripts#516]

**Comment by theVKC** [comment]
@paschell, why is this here??? You left no description, I'm a bit thrown off.

**Comment by paschell** [comment]
Whoops forgot the comment - I get a BlueZone Critical Error "Something has gone wrong.  The code stored on GItHub was not able to be reached.  The script has stopped...."

**Comment by theVKC** [comment]
That's probably a configuration issue and not a script issue. Is it happening on any other scripts, and can you confirm that you're on master branch?

**Comment by paschell** [comment]
It is not happening on any other script.  All of Anoka is on the master branch.

**Comment by theVKC** [comment]
Are you using the state supported Power Pad? Or is it a custom Power Pad?

I worry your configuration is set in a way which points back to beta. Perhaps you have super users configured or something. If Anoka is entirely on the master branch, then other master branch agencies should be seeing this issue. Are we seeing it in counties @KallistaImdieke or @khiestand? I know your counties use master branch.

**Comment by paschell** [comment]
That may be it, I believe we have a customized power pad.    I'll check into this and see what we do about it.

**Comment by khiestand** [comment]
I cannot run the Ct Prep Wkst, get an error message.

**Comment by paschell** [comment]
The problem is in the all scripts file. The court prep worksheet is listed as a NOTES type but it lives in the ACTIONS folder.

(This is Robert on Pam's computer)

**Comment by theVKC** [comment]
OK, that's a bug then.

@RobertFewins-Kalb @khiestand @paschell I'll fix it ASAP.

**Comment by theVKC** [comment]
Resolved just now. Should be in ACTIONS now. Let me know if you don't see it.

**Comment by RobertFewins-Kalb** [comment]
All good!


NOTICE: Unless restricted by law, email correspondence to and from Anoka County government offices may be public data subject to the Minnesota Data Practices Act and/or may be disclosed to third parties.

**Comment by theVKC** [comment]
Thanks for diagnosing @RobertFewins-Kalb!
