### ISSUE TITLE
Income Verification Script

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#519]
Maxis has a script like this and they would like us to create one for Prism also where we can pull and print what child support income the CP is getting and have it mailed out to her by pulling the information into a letter and printing DDPL.  

Please assign this to @TammyStearns and me and we will work on it today as we were told this is priority for us. 

thank you!

**Comment by KallistaImdieke** [comment]
@theVKC  is working in Mainframe friendly date updates. I will pull it into another branch.

**Comment by theVKC** [comment]
I'm working on adding mainframe-friendly-date-enhancements, hopefully today. Sorry about the delay, lots of meetings last week. :/

**Comment by theVKC** [comment]
This has been pulled in! Still need testers for this. Can we confirm this is now working? Need two agencies to confirm.

@MN-Script-Team/prism-scriptwriters?

**Comment by theVKC** [comment]
OK, I'm going to start picking on counties. @MN-Script-Team/prism-wright @MN-Script-Team/prism-olmsted, can you test this and make sure it's working?

**Comment by khiestand** [comment]
Is there a word doc we are supposed to have for this script to work?  If so where is it and how can we get it?

**Comment by theVKC** [comment]
[child-support-income-verification-form.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/619423/child-support-income-verification-form.docx)

I believe this is it. I'm working on details to auto-download it if you don't have an overriding document (see https://github.com/MN-Script-Team/BZS-FuncLib/issues/234).

I'll upload the document to the docs folder shortly. But I believe this is what was sent. @KallistaImdieke can likely confirm.

**Comment by KallistaImdieke** [comment]
Yes that is the right form for the script

**Comment by theVKC** [comment]
Is this working OK @MN-Script-Team/prism-scriptwriters?

**Comment by KallistaImdieke** [comment]
[child-support-income-verification-form.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/747967/child-support-income-verification-form.docx)

**Comment by theVKC** [comment]
There aren't. I think there's a button on the main page of this repository for uploading files. Add it to the docs folder and it should start a pull request (fingers crossed, I use GitHub Desktop for this).

**Comment by khiestand** [comment]
@theVKC  This is now working great in Wright Co!

**Comment by KallistaImdieke** [comment]
@theVKC  I went to Upload files and received a note that states that "file uploads require push access to this repository"  (also believe this and #678 issue will be resolved when this document can be uploaded)

**Comment by theVKC** [comment]
Confirmed to be working. Thanks all!
