### ISSUE TITLE
Bug - Bulk Case Transfer Script

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#527]
Does not work in the training region:

1) The "Specify Cases to Transfer" is getting stuck on the CAAS screen, and just loops and loops infinitely.
2) The "Transfer Caseload Top to Bottom" is also not working, getting this type mismatch error:
![image](https://cloud.githubusercontent.com/assets/10159902/18449100/81d1fdbe-78f3-11e6-9537-f1ecf1921a04.png)

I have tried to figure out the fixes but it is beyond me, @RobertFewins-Kalb do you have time to take a peek as the script writer?  If you can't get it done in the next 2 days, Veronica said she will pull the script.

**Comment by RoberT-1000** [comment]
Give me a second. I'll be pulling something soon.

**Comment by khiestand** [comment]
Way to go @RoberT-1000 !!!

**Comment by theVKC** [comment]
@Robert-1000, I cannot assign the issue to you until you join the MN-Script-Team organization. I've sent you an invite.

**Comment by RoberT-1000** [comment]
Should be good to go.
