### ISSUE TITLE
ACTIONS - NON PAY misspelled word 

### ISSUE THREAD

**Issue by paschell** [MN-Script-Team/DHS-PRISM-Scripts#538]
In the Non Pay Ltr  the word arrears is misspelled.  "Your current **arreas** balance ..."

**Comment by theVKC** [comment]
@paschell, would you like to correct it and pull it in? I'd be happy to talk you through it (via phone) this afternoon, probably wouldn't take 10 minutes. :)

**Comment by paschell** [comment]
@VKC,   sure I would !   Do you want me to call you?

**Comment by theVKC** [comment]
Sure! I should be free around 1. Give me a call!

**Comment by paschell** [comment]
I can't find your phone number

**Comment by theVKC** [comment]
651-431-3993
