### ISSUE TITLE
BUG Returned Mail

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#550]
The script may apply address changes on the wrong participant if there is another MCI number in globals.  We will want the script to REGL during the start of the process to eliminate that problem.

This is a significant enough bug that I recommend removing the script from menus until this bug is fixed.

I also have some ideas for enhancements for this script and would be willing to take on this fix if we have the luxury of waiting until I have time to work on scripts.  If this is an issue that needs to be acted on right away, feel free to assign to someone else.

**Comment by margmac17** [comment]
The person here who does our incoming mail told me that if the CP or NCP address is already "unknown" on Prism it duplicates another "unknown" address for the person. So unless you look at the address screen first you will get another "unknown" address put out there (if that makes sense).

**Comment by theVKC** [comment]
A REGL isn't tough. I'll take it and try and knock it out ASAP.

I don't think it meets "critical" status, because a user can manually REGL before starting the script. Even so, I will get it done.
