### ISSUE TITLE
IW Calculator and IW CAAD/CAWT

### ISSUE THREAD

**Issue by Mkreger9** [MN-Script-Team/DHS-PRISM-Scripts#556]
Why are there now 3 scripts for the IW calculator and making CAAD notes/worklists . There are 2 scripts that separate the calculator and for writing CAAD/CAWT. There is one that combines the 2. I think a decision needs to be made if we need to have 3 scripts for this.

**Comment by theVKC** [comment]
Agreed, I think we should discuss it. I see the merits of breaking it out because the calculator is used in different places than the CAAD notes/worklists. But I'm open to feedback from @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors.

**Comment by paschell** [comment]
I thought we discussed this at the meeting in Buffalo and decided to retire the one and keep the two.  But if the issue is reopen again, I agree with @VKC.  That way IF someday we have a button on our power pad for just calculators that would be cool.  (We have 4 now PALC, DDPL, Pro Rate and now IW).  I think there may be more coming as well.

**Comment by theVKC** [comment]
We did discuss it at the Buffalo meeting for sure. We're just discussing it again because of the feedback @Mkreger9 has gathered. :)

**Comment by gretchent74** [comment]
I agree and love the idea for a spot on the power pad for calculators.

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by KallistaImdieke** [comment]
I love the idea of a separate button on the power pads for the calculators!

**Comment by theVKC** [comment]
It seems there's a lot of interest in separate buttons for calculators. Perhaps a new "class" of scripts (CALCULATOR - PALC as an example). Do folks like that? Then the calculator portion of this script could easily be assembled in that direction. :)

**Comment by paschell** [comment]
I think this would work!  The idea behind wanting a 'button' for calculators is the ease in being able to quickly find and use a calculator.  LOVE THIS!!

**Comment by heatherallen** [comment]
I think a separate button would be awesome!

**Comment by theVKC** [comment]
The separate button on the Power Pad has been done for a bit! #563 took care of this. When the new Power Pad is finished and the installer is wrapped up, folks will be able to access the new button!
