### ISSUE TITLE
Returned Mail Script - bug

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#559]
It is not CAAD noting when it is supposed to, around line 197 for the CP and line 255 for NCP.  It does update the address to unknown for both CP and NCP if checked.

It is also not deleting the new address all the way when entering a new forwarding address.  No idea why.

 If I am going to demo this next Wednesday we need to get it fixed ASAP.  I need help, is it an indenting problem??

**Comment by RoberT-1000** [comment]
I'll take a look!

**Comment by khiestand** [comment]
thanks @RoberT-1000!!

**Comment by RoberT-1000** [comment]
One thing I can see is that the script is doing an EMWriteScreen for the activity date, but CAAD will not let you save the note if the date is not a MM/DD/YYYY format. Leading zeroes tend to be removed from date variables. I'm going to go ahead and say that's also the problem on line 258. 

I can't test this (sorry) but, on line 258, replace your EMWriteScreens with `CALL create_mainframe_friendly_date(date_received, 10, 18, "YYYY")`

...and on line 199 `CALL create_mainframe_friendly_date(date_received, 4, 37, "YYYY")`

**Comment by khiestand** [comment]
@RoberT-1000 
I made those changes, however, it updates the address, but still does not CAAD note, and the CAAD note piece should be happening BEFORE the address screen parts.... ????

**Comment by theVKC** [comment]
This didn't just start, did it? I updated it earlier today with a REGL for removing existing case numbers (but only if they conflict with the entered case number).

**Comment by khiestand** [comment]
I haven't had any returned mail on my caseload to use the script since it went on the power pad unfortunately so I am not sure

**Comment by theVKC** [comment]
@khiestand, I do believe I was in the room when you tested it. Do you know if it's working on the specific training case you tested it on?

I just tried it on a couple of cases (training case 01-01 and 16-01). 16-01 didn't CAAD note when updating for a new known address. I'm wondering if there's a missing condition.

As we speak, I'm working on a new writing dates function (it's called `write_date`) which may help resolve the date issue.

**Comment by khiestand** [comment]
I can't remember, I ran it on multiple cases that day.  I'm not sure I can figure out the fix and the deleting issue, for sure not by tomorrow.  I am out Mon-Wed at the conference next week.

**Comment by theVKC** [comment]
Any chance someone else can take it? @RoberT-1000, can you help me out here?

**Comment by RoberT-1000** [comment]
I was in meetings all day yesterday afternoon so I missed this entire conversation.

@khiestand, have you tried putting message boxes every couple lines in the CAAD noting to see where things go wrong? If there is something that PRISM does (or doesn't do) that the script is triggering (or failing to trigger) we should slow the script down to try to catch it.

**Comment by theVKC** [comment]
I'm fairly certain @khiestand is going to be pre-occupied with work due to the conference. As am I. Any chance someone else can investigate this before Wednesday?

**Comment by khiestand** [comment]
@RoberT-1000 @theVKC 
I have no time, I am scrambling to finish/clean up my other work today before heading to the conference Mon-Wed of next week.  Sorry!

**Comment by RoberT-1000** [comment]
Then I'm going to need to get into the training region. Does anyone have access right now? @MN-Script-Team/dhs-scriptwriters

**Comment by khiestand** [comment]
Yep, cicsdt4, pwcst10, sep$2016, QQT5

**Comment by RoberT-1000** [comment]
RAD! Thank you

**Comment by theVKC** [comment]
I think the password might be for October now, FYI. Just got an email this morning. Let me know if it doesn't work.

**Comment by RoberT-1000** [comment]
It's October. I'm in. Thank you!

**Comment by RoberT-1000** [comment]
@khiestand -- When you are testing this in the training region, what date are you entering for the Effective/Verified Date?

**Comment by khiestand** [comment]
I have been using a day or two after the last effective date in Prism.  Could that be the issue?

**Comment by RoberT-1000** [comment]
That's what I'm wondering. PRISM training region seems to be really sensitive about dates. I'll keep poking and prodding.

**Comment by RoberT-1000** [comment]
@khiestand, please let me know about the following...

1. When the user selects an unknown address, the script is not programmed to create a CAAD note.
2. When the user selects a known address, the script will create the CAAD note BEFORE updating the CPDD. PRISM then automatically creates a CAAD for the changes.
3. When the user enters any value into the "Other" editbox, the script will CAAD note that.

Looking through the functionality, and forcing the breaks in the script run, I'm not seeing what the problem is. Maybe additional code needs to be added to the Unknown Address parts of the script to add the Miscellaneous Notes information, if that's what you're getting at.

**Comment by khiestand** [comment]
If we are updating the address to unknown for either party, we want the CAAD note to note, R0010 for NCP and R0011 for the CP.

Will you also check if you are updating to a new address that is shorter than what was previously there, it is only writing over what was there, this leaving some of the old address there which is obviously a problem.  I don't know anything about the erasing logic used, Wendy did that part of the script.

**Comment by RoberT-1000** [comment]
OK, so there's no code to create a CAAD for the CP...
![image](https://cloud.githubusercontent.com/assets/22157633/18999088/71c5cf1a-8701-11e6-9b24-0642fe6a35ed.png)


I'll move the bit that's down by the ELSEIF so it's creating a CAAD note every time...
![image](https://cloud.githubusercontent.com/assets/22157633/18999147/c000df3a-8701-11e6-83a5-d5d4bcb550e1.png)


Then I'll take a look at the address writing gobbins

**Comment by RoberT-1000** [comment]
@khiestand, a recommendation for future coding, please keep an eye on your indentation. It makes the script a little difficult to follow.

**Comment by RoberT-1000** [comment]
One more thing -- the test region won't let you update the address. It keeps saying the database is out of date no matter what address I put in...
![image](https://cloud.githubusercontent.com/assets/22157633/18999494/864bb970-8703-11e6-9d4b-69872f79a79a.png)


I think I made the appropriate changes. I'll submit a pull request. Go ahead and try it in production when you have a chance.
