### ISSUE TITLE
Financial Statement Follow up Request letter

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#564]
We have a Letter we send out to follow up on Financial statements on modification and establishment actions that we would like to create into a DORD to save some time.  

I have already started on a script that will create this letter.  Can you please assign this to me. 

This will create the DORD document, modify the CAAD note that the letter was sent out and create a worklist to follow up. 

Thanks!

**Comment by theVKC** [comment]
Reopening because I want to confirm it's working.

**Comment by theVKC** [comment]
Still need testers for this. Can we confirm this is now working? Need two agencies to confirm.

@MN-Script-Team/prism-scriptwriters?

**Comment by paschell** [comment]
I like this one - working in Anoka just fine and dandy.

**Comment by theVKC** [comment]
Great, thanks Pam! Just need one more separate agency and then it'll be pulled through!

**Comment by theVKC** [comment]
OK, I'm going to start picking on counties. @MN-Script-Team/prism-scott, can you test this and make sure it's working?

**Comment by heatherallen** [comment]
this is working! and thanks for making me test it, I'm going to make sure my coworkers are using it as it is awesome!

**Comment by theVKC** [comment]
Good deal! @KallistaImdieke, can you upload instructions to SIR?

**Comment by heatherallen** [comment]
I lied the "both" option I'm getting an error message on real time PRISM and training region PRISM, "Script Error at Line1, Column 1: Type mismatch 'F3'"

**Comment by theVKC** [comment]
Sounds like an "F3" should be replaced with a "PF3". @KallistaImdieke or @heatherallen, want to take it?

**Comment by KallistaImdieke** [comment]
I can take it.  I have been having Stearns test the “both” option also because it wasn’t working and I have a fix already drafted I just need one of them to test the fix for me so I can pull it in. ☺

**Comment by theVKC** [comment]
Good deal, thank you!!
