### ISSUE TITLE
enhancement request -- client contact -- notes

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#566]
would it be possible to add the following to the client contacts?  Possible mandatory field that the question was at least asked (checkbox)?  Verify address, phone number, employer, MAYBE-- check enfl for DLS ACT and see if payment plan is necessary.

**Comment by theVKC** [comment]
@jannellstearns, what question specifically do you want a mandatory field for?

Checkboxes are hard to make mandatory, because if you force it to be checked, people just check it without thinking about it... If you want something to be suggested to the user, we can consider that. :)

**Comment by jannellstearns** [comment]
Might as well skip the mandatory part and just have it as check box fields that were reviewed.

**Comment by gretchent74** [comment]
Maybe we could have the script to check prism to see if there is no address, phone, or employer and either  add a check box to the dialog or have a separate pop up that will remind worker to ask these things if not on prism?

I also think it would be nice to add something like the bottom 2  checkboxes:
[cid:image001.png@01D223A4.E9ECE1B0]

Just a thought.

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
@gretchent74, your screenshots don't go through on GitHub when you email them. Can you log into GitHub and share again please? Sorry about that!

**Comment by gretchent74** [comment]
Check if you left a generic message returning their call.
Check if you left a message requesting permission to leave a detailed message in the future.
Then this would go in your caad note.

**Comment by TammyStearns** [comment]
I would like to work on the enhancement to this script.  Can you assign this to me, 
Veronica?

**Comment by KallistaImdieke** [comment]
I received another request for an enhancement on this script for the following areas or boxes

Follow up needed: 

Additional notes 

Have option to create a work-list and put in a certain worker’s number to make sure they do the follow up (pull information from the follow up needed part of the script and put into work list)

Tammy I can help with this and explain more about the requests I received. 

Thanks!

**Comment by theVKC** [comment]
I like it! Have we started on it yet, @TammyStearns? It's listed as a backlog item and I'd like to keep it up-to-date.

**Comment by TammyStearns** [comment]
This will be worked on at the hackathon in Wright County on 11/16/16.

**Comment by KallistaImdieke** [comment]
@theVKC can you remove me from this one and add @cmoore502622   She was working on this one.  I have not been.  Thanks!!

**Comment by theVKC** [comment]
We believe this could be resolved with county customizable fields so each county can add their own procedure for how they'd want to verify such info. This will be done with the Python conversion so will be marked as such and closed.
