### ISSUE TITLE
New script idea

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#567]
Is it possible to build a script to check work number to see if the employer is a work number employer?

  It would be nice to run this when adding employers and there is a legal action pending - it would save time and it would be more likely that counties would meet legal action timeframes if we don't use 30 days to send an employer verification out only to have it returned as send to work number.

Maybe it can be a script that runs as part of an employer verification request.  it checks work number and it the employer is registered with work number, it gives a pop up box otherwise it just generates to the active employer.

**Comment by theVKC** [comment]
This is an interesting idea. I'm going to float it here at DHS. :)

**Comment by theVKC** [comment]
I never responded to this element. I've looked into things here and we felt that loading Work Number accurately would be prohibitive from a security standpoint. Closing issue and marking as "wontfix". Note there's a Work Number link on the newest Power Pad. :)
