### ISSUE TITLE
Idea: a text file where a county can add custom pop-ups before or after a script runs

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#568]
Just looking for feedback on this idea. 

As an example, if you want a pop-up box to run before and after the intake script, you can add:

```
before intake: "Please note: our county does not process gas card reimbursements."
after intake: "Remember to update the case status in SharePoint!"
```

If folks like it, I can add it in while I'm updating #563. Thoughts @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors?

**Comment by gretchent74** [comment]
I think that would work great!

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by RoberT-1000** [comment]
I'm going to be Debbie Downer, but I get the impression that this is something staff end up ignoring. We get a lot of interest in having this functionality but I have doubts about the effectiveness.

**Comment by theVKC** [comment]
Fair point. Alternatively, we could maybe include some additional functionality in initial dialogs that would display this info in a sidebar-type format?

**Comment by theVKC** [comment]
(Also, if anyone disagrees with @RoberT-1000's assessment, speak up)

**Comment by RoberT-1000** [comment]
OOO!!! I like the "additional functionality in the initial dialogs"...idea: PushButton for more info that opens MsgBox with this information...we could label it "Agency Info" or something similar.

And don't encourage dissent!! RoberT-1000 has spoken!!

![image](https://cloud.githubusercontent.com/assets/22157633/19281481/1f7da536-8fb0-11e6-8111-b7d02a9a2110.png)

**Comment by theVKC** [comment]
OOOOOO!!! I like the pushbutton idea for that info. Then, if the user doesn't have that pushbutton, I bet we could scan it using a method similar to `run_from_github`, perhaps even when we use `run_from_github`, and return a boolean that can indicate whether-or-not a MsgBox should be used (in place of an "agency specific notes" button).

**Comment by RoberT-1000** [comment]
I likes

**Comment by wrightcountykaren** [comment]
So it appears to me that there are 3 options being discussed
1 – a separate pop-up box that shows up before an/or after a script
2 – the information from the pop-box being included in the dialog box of a script
3 – a separate county specific button being added to the dialog box that can be clicked on to obtain county specific messages

Below are you suggesting a 4th option of having the pop-up box be both customizable and optional depending on each counties preference?

My personal opinion is that a pop-up message box that shows up after a script is run, is less likely to be overlooked than having that information on the dialog box.  I also foresee that many staff would not click on an additional button on the dialog box to get county specific info.  Just my thoughts…..

Karen Popken
Wright County Child Support Supervisor
Phone: 763-682-7403
How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by theVKC** [comment]
I tend to agree that pop-ups that run on startup, when executed sparingly enough not to feel obtrusive, is more likely to be noticed. I'm contemplating throwing a date range on there. Maybe, just maybe, even working out a way to acknowledge that you've seen the pop-up. (Don't ask me how, I'm scheming that, and not coding it yet.)

**Comment by theVKC** [comment]
I think I got good feedback on this one. And I want to work on it at some point. No ETA, but I'm removing the "question" tag.

**Comment by theVKC** [comment]
Closing issue which has been "help wanted" for a long time.
