### ISSUE TITLE
Notes Hearing Notes - ERROR

### ISSUE THREAD

**Issue by gretchent74** [MN-Script-Team/DHS-PRISM-Scripts#573]
Is anyone else getting an error on this script:  Script Error at Line 1, Column 1: Object not a a collection?

**Comment by paschell** [comment]
I just ran the script on both ex pro and judicial hearings with no errors.

**Comment by RoberT-1000** [comment]
The script is looking for an array of magistrates from your Global Variables file and not finding one.

**Comment by RoberT-1000** [comment]
...or attorneys

**Comment by RoberT-1000** [comment]
Sorry: I'm still waiting for the caffeine...

The script is using a function that grabs a list and splits it for a dropdown. Whenever vbscript attempts to split an object that is NOT an array, you get the error message "Object not a collection." In Anoka, we have these lists in our Global Variables file. Lines 42 through 48 of the default Global Variables file shows you an example of what you need to have and how it needs to be formatted...

https://github.com/MN-Script-Team/DHS-PRISM-Scripts/blob/master/Script%20Files/SETTINGS%20-%20GLOBAL%20VARIABLES.vbs

**Comment by theVKC** [comment]
Yes, @gretchent74, I'm going to concur with my colleagues here and say you're missing the list of attorneys/judges/magistrates in your global variables file.

Adding them in manually ought to work. If you need help with it, shoot me an email and I can walk you through it.

**Comment by gretchent74** [comment]
Thank you Robert.  I will try this out.

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by gretchent74** [comment]
Worked.  You are amazing!

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
It's a good group all around. Thanks for jumping in @RoberT-1000!

**Comment by KallistaImdieke** [comment]
@GayS We are having this issue also on our contempt Hearing script and Hearing Notes script.  Is this something that you would need to look into on our end?? I am not sure that I have access to this.   Thanks!
