### ISSUE TITLE
court prep worksheet ERROR

### ISSUE THREAD

**Issue by gretchent74** [MN-Script-Team/DHS-PRISM-Scripts#575]
Any clue why I am getting this error:  Script Error at Line 1, Column 1: Type mismatch: 'go_to'

**Comment by RoberT-1000** [comment]
I wonder if it's an order of operations problem. `Type Mismatch` the default error message when the script is trying to call a function that it doesn't know, but `go_to` is created and defined in the script but AFTER it is called in another custom function.

I have an idea...standby...

**Comment by RoberT-1000** [comment]
Yep...when I moved the creation of `FUNCTION go_to` to the top of the list of custom functions, I don't have that problem. I can submit a pull request to fix this, but I am wondering if we should just change the code. `go_to` does the exact same thing as `write_value_and_transmit` which is already in FuncLib.

@theVKC >> Thoughts? Move the custom function or replace it with `write_value_and_transmit`? My vote is "replace".

**Comment by theVKC** [comment]
Replace with `write_value_and_transmit`. Definitely. :)

**Comment by theVKC** [comment]
Wait!

This file is to be removed because nobody created instructions. See #572. I've removed it from my working branch already. @RoberT-1000 or @gretchent74, care to write instructions?

**Comment by gretchent74** [comment]
Can I do it next week.

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
That would be wonderful. Thank you, @gretchent74!

**Comment by theVKC** [comment]
Then, anyone want to take on this fix? @RoberT-1000?

**Comment by RoberT-1000** [comment]
I can submit a quick fix.

**Comment by RoberT-1000** [comment]
...or quickly submit a fix...

**Comment by RoberT-1000** [comment]
Ready
