### ISSUE TITLE
Notes - Pay or Report looks goofy

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#578]
It has this thing going on:

![image](https://cloud.githubusercontent.com/assets/5701751/19360333/b81d5cb6-9143-11e6-8d77-46556cd26d35.png)

There should be a bit of padding on that first dialog.

Any takers for sometime next week?

**Comment by theVKC** [comment]
I'll take it and try and pound it out. #HopefullyTomorrowIsBugFixDay

**Comment by RoberT-1000** [comment]
I can fix it.

**Comment by theVKC** [comment]
Reopening while I await testing results. My own testing is indicating this worked as expected.

**Comment by theVKC** [comment]
Still need testers for this. Can we confirm this is now working? Need two agencies to confirm.

@MN-Script-Team/prism-scriptwriters?

**Comment by theVKC** [comment]
OK, I'm going to start picking on counties. @MN-Script-Team/prism-stearns @MN-Script-Team/prism-scott, can you test this and make sure it's working?

**Comment by KallistaImdieke** [comment]
I am not sure what this script is suppose to do?  I did not see instructions on DHS-Sir.  Stearns County does not enter County Attorney Case numbers in PRISM and this is a mandatory field.  It did generate a CAAD note when I ran it however like I said don't see instructions that say what this script is supposed to all do?

**Comment by theVKC** [comment]
Shoot! I had the instructions checked out in DHS-SIR. I checked them back in, you should see them now.

Even if you don't use the script, I just need someone to confirm that the initial dialog has padding on all sides and all content is visible.

**Comment by KallistaImdieke** [comment]
Yes the initial dialog box has padding on all sides and all the content is visible.

**Comment by theVKC** [comment]
Boom! Now we just need one more agency to confirm before I close it.

**Comment by heatherallen** [comment]
It appears to be working in Scott County, I'm not a big fan of having the County Attorney case number mandatory as our agency doesn't use this either.  Scott County does not use the pay or report process  but the script seems to be producing the correct CAWT and CAAD.

**Comment by theVKC** [comment]
Well that could be a separate enhancement! In any case, I'm going to close this one, after @RoberT-1000 updates the screenshot in SIR. :)

**Comment by theVKC** [comment]
Never mind, @RoberT-1000. I have a SIR glitch on this document so I'll take care of it. No worries.

**Comment by theVKC** [comment]
Done! In SIR and approved! Thanks all!
