### ISSUE TITLE
Person Search from Excel sheet - new script idea

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#583]
I am not sure if this is even possible --

Stearns County obtains information from our jail about who is currently in our jail.  On the excel spreadsheet we get the name and dates of birth of individuals.  a CSO then needs to go into prism and do a person search to see if there is an active child support case.

Is there a way to grab the name and date of birth information from excel and do a person search and if there is a match put the case number in excel?

This probably doesn't make sense so give me a call if you need more information!

Jannell

**Comment by RoberT-1000** [comment]
This is absolutely do-able. Scripts heart Excel.

**Comment by theVKC** [comment]
It's true. They do heart Excel.

**Comment by gretchent74** [comment]
I would like to do something similar so keep me in the loop with this one!

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
@heatherallen and I are going to take this one!

Heather is going to create a fake Excel sheet, then create the function to person-search each person on the sheet (using training region data for testing, obviously).

I am going to then create/port a function to load an Excel sheet (Krabappel over on the MAXIS side does this).

@jannellstearns, is there any way you can email Heather and I a sample Excel file? Obviously, don't send the client data, just an example of which columns contain what data. That would help tremendously.

**Comment by jannellstearns** [comment]
I forwarded request to Tammy. Hoping she can do today

Sent from my iPhone

On Jan 18, 2017, at 11:48 AM, Veronica Cary <notifications@github.com<mailto:notifications@github.com>> wrote:


@heatherallen<https://github.com/heatherallen> and I are going to take this one!

Heather is going to create a fake Excel sheet, then create the function to person-search each person on the sheet (using training region data for testing, obviously).

I am going to then create/port a function to load an Excel sheet (Krabappel over on the MAXIS side does this).

@jannellstearns<https://github.com/jannellstearns>, is there any way you can email Heather and I a sample Excel file? Obviously, don't send the client data, just an example of which columns contain what data. That would help tremendously.

**Comment by TammyStearns** [comment]
I am sending this to Veronica.Cary@State.MN.us and also Heather Allen.  I am not able to get it to attach here for some reason.  Let me know if you have any questions or issues with it opening.  Thanks.

**Comment by heatherallen** [comment]
@theVKC, I'm working on the person searching from excel to PRISM part of this script.  Do you or any other scriptwriters know how, or if it is possible, to select more than one case that a client may have in PRISM so I can export all their case numbers back to the excel spreadsheet?

**Comment by heatherallen** [comment]
@theVKC is there a way to have 2 do loops in a script?  Currently I have it searching the 1st column, but am trying to get it to run the same way searching the 2nd column.  I'm running into the issue that the script stops after person searching the 1st column.

**Comment by RoberT-1000** [comment]
You can have as many do/loops as you are willing to open and close.

For your issue, consider this...
`FOR column = 1 to 2`
`     excel_row = 2`
`     DO`
`          do stuff`
`          excel_row = excel_row + 1`
`     LOOP UNTIL objExcel.Cells(excel_row, column).Value = ""`
`NEXT`

**Comment by theVKC** [comment]
As long as all of them open and close without overlapping, you should be good. Good indenting is key!

This describes the types you can use: https://www.tutorialspoint.com/vbscript/vbscript_loops.htm

I'm also targeting this for a training soon.

**Comment by heatherallen** [comment]
Thank you both!  I'll see what I can come up with
