### ISSUE TITLE
Bulk DL is Susp - Custom Function- enhancement

### ISSUE THREAD

**Issue by gretchent74** [MN-Script-Team/DHS-PRISM-Scripts#592]
#570 had 2 scripts listed.  pull request done for Bulk Failure POF RSDI DFAS to fix the dialog box to accommodate for longer cso names.

I am creating this separate issue for Review Pay Plan - DL Susp - Custom Function - enhancement.  The issue in the script is in the Custom Function (select_cso_caseload).  I know what needs to be fixed, I just need help on how to do a pull request for a custom function.

**Comment by theVKC** [comment]
I'll take a look at the script and get back to you. :)

**Comment by theVKC** [comment]
Shoot @gretchent74! We didn't get a chance to go over this at hackathon!

If you are up for a WebEx sometime this week, I'd be happy to take a look.

**Comment by gretchent74** [comment]
sure.  I am available today until noon and then  7-3:30 on Thursday and  Friday.

**Comment by theVKC** [comment]
Let's do tomorrow if you don't mind. I'll send you an Outlook invite. :)

**Comment by gretchent74** [comment]
i think i resolved issue with the function to fit long names. https://github.com/MN-Script-Team/BZS-FuncLib/pull/307

**Comment by theVKC** [comment]
Can I get a confirmation from someone running master that this is now working? @RobertFewins-Kalb? @levesswe? Is this working in Anoka now? You-all are running master.

**Comment by theVKC** [comment]
Reopening: we now will leave issues open until they are confirmed as resolved.

**Comment by theVKC** [comment]
Any chance @MN-Script-Team/prism-olmsted can check this one for me? Is this working?

**Comment by margmac17** [comment]
Sorry for taking so long, this is regarding the BULK DL Suspense script I right.... I don't have a case load that I get that type of work list on to really test it but I ran it and it came up with "Success". Other script writer is not available.

**Comment by theVKC** [comment]
Thanks @margmac17! I'm going to call it resolved.
