### ISSUE TITLE
Unreimbursed Uninsured Docs

### ISSUE THREAD

**Issue by gretchent74** [MN-Script-Team/DHS-PRISM-Scripts#598]
@MN-Script-Team/prism-scriptwriters 
I am getting the "something has gone wrong error" for this script.  Is anyone else?  It is because of the pull request i made yesterday to update the script and change the name?  Thanks.

**Comment by paschell** [comment]
Yes getting the same error.

**Comment by theVKC** [comment]
The old one might not have changed names. I'll investigate.

**Comment by theVKC** [comment]
@gretchent74: are you seeing it on the new Power Pad? Or the old one?

**Comment by gretchent74** [comment]
the new one.

**Comment by theVKC** [comment]
Does the old one throw the same error, @gretchent74?

**Comment by gretchent74** [comment]
no @theVKC

**Comment by theVKC** [comment]
OK! @paschell, @RoberT-1000, or @levesswe: are you all using the master branch version? With the new file names and paths and everything?

**Comment by RoberT-1000** [comment]
we be

**Comment by theVKC** [comment]
Fantastic! I think I have enough to start investigating (unless someone else wants to).

**Comment by RoberT-1000** [comment]
The problem is with the Complete List of Scripts file. There is one Un/Un Docs listed and it doesn't match either of the Un/Un scripts...

![image](https://cloud.githubusercontent.com/assets/22157633/19902709/cd5a825c-a039-11e6-99e0-ef31b79129b1.png)

**Comment by theVKC** [comment]
That makes sense. I haven't released it to release yet, and it's likely that it got lost in the move between formats for the files. @RoberT-1000, care to pull a fix to master?

**Comment by RoberT-1000** [comment]
Yarp

**Comment by RoberT-1000** [comment]
@gretchent74 >> Can you please provide a description for these scripts? 

I have no idea what to write other than "this is a script"

**Comment by theVKC** [comment]
@gretchent74, @RoberT-1000 fired off a fix to this. Can you confirm that it's now working? Also @heatherallen, @jlmartinone, or @khiestand may be able to confirm as well, since you're on master.

**Comment by RoberT-1000** [comment]
They are good to go.

**Comment by theVKC** [comment]
Oh, I know you've tested it. I want independent confirmation from more than one source going forward.

**Comment by theVKC** [comment]
Also now on master: @KallistaImdieke and @TammyStearns.

**Comment by heatherallen** [comment]
I tested this and the sending docs works great! When testing the returned docs button, I get an error that states "OBBD information was not added correctly, please re-enter information.  Script Ended".  I tested a few different cases and realized that I do not get this error message when I enter the $$ Amount Requested as a whole number (i.e. 5000) but I get the error when I enter dollars and cents (i.e. 5000.00). Other then that they both seem to be working alright.

**Comment by theVKC** [comment]
That one seems like a separate issue, @heatherallen. @gretchent74, can you email Heather and work with her on identifying that issue? I wonder if it's the same one you pulled in recently.

**Comment by gretchent74** [comment]
sorry for the delayed response.  The script is now working for me.  Thank you. 
instructions have been updated also.

**Comment by gretchent74** [comment]
@heatherallen 
your error is for the unreimbursed uninsured returned documents.  I have tried running the script using 500 and 459.25 and I am not getting an error.  Is there anyway you could email me directly with screen shot and more information so I can try to figure out what is going on?  Thank you.

**Comment by heatherallen** [comment]
@gretchent74 I just tried running the returned docs script for un/un with $123.25 and it seemed to work.  I think we are good to go.  I'll let you know if I run into the same issue again.  Thanks.
