### ISSUE TITLE
Power Pad/New script idea: changelog

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#599]
Basically, a script that scans all of the scripts for an array of changelogs, and reports what's changed in the last week. Maybe a field/button to indicate a date range. Maybe a way to export to Word.

First, we need changelogs. Then we need to build this script for real. For now, I should put a button/redirect on so that folks won't have to update their Power Pads after #584. So for now, a dummy button, with more to come for sure.

I could totally see @RobertFewins-Kalb wanting to work on this with me. Would you be interested in collaborating?

**Comment by RoberT-1000** [comment]
@RobertFewins-Kalb is in a coma and never coming back. RoberT-1000 is game.

**Comment by theVKC** [comment]
Dang! Sorry for bothering you, old Robert. I meant new Robert. Let's do it. I'll do the changelog part (at least the general formatting), then if you can hammer out a dialog that reads back changes as described above, we should be square-as-all-get-out.

**Comment by RoberT-1000** [comment]
Are you thinking dynamic dialog that displays the changelog?

**Comment by theVKC** [comment]
I be!

**Comment by theVKC** [comment]
@RoberT-1000, I know you just built an amazing External Resources script, but I still want to ask for an ETA on this. I might try and push this through before the next expansion round of script users.

**Comment by theVKC** [comment]
Note to self: once this is complete, immediately begin working on #597.

**Comment by theVKC** [comment]
@RoberT-1000: do we have any updates at all on the changelog display elements? That's the only part of this that's missing, the "seek out all changes and display them in a Word doc or maybe a dynamic dialog of some kind" element we spoke about.

If you don't have an ETA on it, I am going to take over on this part to wrap it up. Under some pressure to get it done.

**Comment by theVKC** [comment]
I'm going to be taking the Changelog display elements. My plan: create a JavaScript handler for pulling these into an HTML document, which can be located on the GitHub pages page.

I'm already doing this functionality for FuncLib (see https://github.com/MN-Script-Team/BZS-FuncLib/issues/325).

**Comment by theVKC** [comment]
Minnesota has a new style guide!

https://mn.gov/mmb-stat/branding/style-guide/minnesota-state-brand-style-guide-2016.pdf

I'm going to make sure to apply styleguide-approved changes throughout. Woot!
