### ISSUE TITLE
Adding loads of new links to the Power Pad

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#601]
I've asked @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors to send "commonly used websites". Already received tons of feedback (more is welcome and I'll keep this post updated with totals). Here's what we have:

* Work Number (6 votes) - http://www.theworknumber.com/SocialServices/
* MGA (6 votes) - https://mga.courts.state.mn.us/MNPRODPORTAL/
* DHS-SIR (5 votes)
* IRG (5 votes) - https://www.ssp.childsupport.dhs.state.mn.us/irg/profile.htm
* MN DOC prisoner look up (5 votes) - https://coms.doc.state.mn.us/PublicViewer/Home/Index
* MN CS statutes (4 votes) - https://www.revisor.mn.gov/statutes/?id=518A
* VineLink (3 votes) - https://vinelink.com/#/home
* DL Look ups/DVS home page (3 votes)
* CS forms on DHS (3 votes)
* mn.courts.gov (2 votes)
* Odyssey File and Serve (2 votes)
* RoP on eDocs (1 vote)
* Minnesota CS Online (1 vote)
* TrainLink (1 vote)
* eFile (1 vote)

Would love additional votes. Comment below!! :)

**Comment by KallistaImdieke** [comment]
https://mn.gov/dhs/people-we-serve/children-and-families/services/child-support/resources/forms.jsp

MN child support forms website

**Comment by gretchent74** [comment]
DVS and dl looks up are the same:  https://www.dvsesupport.org/

All the website below are ones I would vote YES.

Thank you,

Gretchen Thornbrugh
Dakota County Child Support
Phone 651-554-5663
Fax 651-450-2631

**Comment by theVKC** [comment]
Thanks for the feedback all!

I present, your new Power Pad:

![image](https://cloud.githubusercontent.com/assets/5701751/19746527/6ebd063a-9b9c-11e6-8f54-61d77edc3849.png)

I'll be sending an email about what comes next. :)

**Comment by ChrisKast** [comment]
This really looks great.

**Comment by KallistaImdieke** [comment]
Love it I can’t wait until it is released and we can use it! ☺

**Comment by heatherallen** [comment]
Looks AMAZING! Can't wait!

**Comment by paschell** [comment]
Yes!  Me too!  Can’t wait…
