### ISSUE TITLE
Robert: building an External Resources script since today and maybe before

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#604]
@RoberT-1000 is working on this today, but I need an issue to tag in a Power Pad pull request, so I am making the issue on his behalf.

He's creating an "External Resources" script which counties can modify, to allow counties to specify county-specific favorite links for staff to have access to.

As I want to pull in changes for #601 as well as the installer changes (which really, really need testing), I am going to quick create dummy redirect files. @RoberT-1000, at your leisure, I'd appreciate you uploading your version to the utilities folder in master. :)

**Comment by RoberT-1000** [comment]
Uploading now.

**Comment by theVKC** [comment]
Reopening: we now will leave issues open until they are confirmed as resolved. This went out for testing this week. Folks need to update their Power Pads to get it all. :)

**Comment by theVKC** [comment]
Can I get some folks to confirm this is working?

**Comment by theVKC** [comment]
@MN-Script-Team/prism-wright? @heatherallen? I believe you've recently (last few hours) updated.

**Comment by heatherallen** [comment]
@theVKC it is working here in Scott County!

**Comment by theVKC** [comment]
Gorgeous! Thank you! Will close the issue now. @RoberT-1000, please submit instructions for the script via our SIR page.

**Comment by theVKC** [comment]
(I will try and hold off on releasing the script statewide until instructions are in there)

**Comment by theVKC** [comment]
I believe Washington County is testing this, but I need another independent test.

Can we try to add some resources @MN-Script-Team/prism-wright?

**Comment by theVKC** [comment]
Shoot. Scratch that Wright County. We tested this. Got my pieces crossed.

**Comment by theVKC** [comment]
(Still need instructions, @RoberT-1000) :)

**Comment by RoberT-1000** [comment]
False

![image](https://cloud.githubusercontent.com/assets/22157633/20484799/86db5d30-afbe-11e6-82f8-b3172f3d2529.png)

**Comment by theVKC** [comment]
Whoa! So apparently my notifier is off. I'll investigate. Sorry bout that!

**Comment by RoberT-1000** [comment]
no worries

**Comment by heatherallen** [comment]
Is there a way to add a "Add New" button?  When we click on the external resources button it shows the ones I have added but to get to add a new one i have to click the "cancel" button, which then asks me "Are you sure you want to cancel the script? Press YES to cancel or Press NO to return to script" where I have to click "No", then it brings me the Manage Resources dialog to add new link.

**Comment by theVKC** [comment]
@heatherallen: as this is a completed script, can you add your comment as a new issue please? :)
