### ISSUE TITLE
QUICK DORD

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#612]
We have workers here in Stearns that LOVE the Quick CAAD and have requested a quick DORD to save DORD documents that they send out a lot.  Thoughts? I personally love this idea because I do not remember the documents numbers all the time and spend a lot of time searching for them.

**Comment by theVKC** [comment]
I like it myself. I'd even thought about adding the function somehow. Space on the Power Pad may be an issue, but if there's demand, I want to provide it.

Feedback time! @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors, start your keyboards! :)

**Comment by heatherallen** [comment]
I really like the QuickDord idea!! If we feel there may be issues with space on the powerpad could we just have a "Quick...." and include the QuickCAAD, QuickDORD, and then we could always add more like QuickCORD (which generates court docs).  Just a thought but I love the QuickDORD!

**Comment by khiestand** [comment]
Love the quick dord idea!!!

**Comment by levesswe** [comment]
There is definitely demand!!!  Great ideas all around!

**Comment by theVKC** [comment]
Agreed. Officially marking as "help wanted". Any takers? Of course, we have a plethora of other things to get done (including instructions, ahem ahem), but if someone wants to get this on the radar for the next few months I think that'd be swell.

**Comment by theVKC** [comment]
I'm taking this one, as it involves a Power Pad change and #636 necessitates that. :)
