### ISSUE TITLE
GlobVar: allow agency-custom to be redirected to another location

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#616]
It will default to the root directory but users can manually move it if they want to restrict access easily.

On it. Necessary to resolve https://github.com/MN-Script-Team/bzs-config-utility/issues/61.

Also, @CDPotter: you may want to evaluate this as well for MAXIS. I imagine your folks will run into issues over there too.

**Comment by theVKC** [comment]
@RobertFewins-Kalb and @levesswe: I know you do a lot of fun work with agency custom scripts. You might like this one.

**Comment by theVKC** [comment]
(Also, I beg of you, please start using the DHS Power Pad if you aren't already so I can get feedback from you)

**Comment by theVKC** [comment]
@RobertFewins-Kalb or @levesswe: can you test and confirm this is working? Try moving agency-custom to another location and testing it using this global variable. If you can't do it, can you let me know so I can reassign testing?

**Comment by theVKC** [comment]
It could be a bit before Anoka can test this. Anyone from @MN-Script-Team/prism-stearns want to test? I know @GayS has used agency custom in the past (at least on the MAXIS side).

**Comment by GayS** [comment]
I will try to update the installer today during the 12-12:30 down-time and test the agency custom.

**Comment by RoberT-1000** [comment]
Full disclosure: After running the installer, I just updated the Agency Custom button to run our old Beta/Anoka menu script because we have some cleaning up to do. 

I don't see any reason why it wouldn't work to simply update the folder path to a different folder. I did some monkeying with the agency custom script a while back to try to create a document generator and it will work just fine if you change the root folder to any other folder. My advice >> Make sure that folder is not full of other .vbs files!!

**Comment by RoberT-1000** [comment]
For anyone interested...

This is a test copy of the repository I downloaded before the install. Line 19 is a folder full of test scripts. I has been commented out. Line 20 is a folder that includes some live scripts (see above RE: clean up). When I run the agency custom script with Line 19 commented out and Line 20 live...
![image](https://cloud.githubusercontent.com/assets/22157633/20063726/e324e706-a4cd-11e6-8a19-7c277a2f391c.png)

...then when I run the Agency Custom script...
![image](https://cloud.githubusercontent.com/assets/22157633/20063797/1dc2423c-a4ce-11e6-9a33-ffe1e5d64284.png)



Now, when I commend out Line 20 and make Line 19 live...
![image](https://cloud.githubusercontent.com/assets/22157633/20063749/f51ec74c-a4cd-11e6-88c4-5c215ba87be5.png)

...and run the Agency Custom script...
![image](https://cloud.githubusercontent.com/assets/22157633/20063775/0630530c-a4ce-11e6-97f5-6a6188daf42f.png)


If you can type a folder path and can update your agency's GlobVar, you can make Agency Custom point anywhere.

**Comment by theVKC** [comment]
Boom! Thank you for testing and confirming it's working, @RoberT-1000! :)

**Comment by GayS** [comment]
Awesome - it works in Stearns too and I don't have to re-run the installer!!! Thanks!
