### ISSUE TITLE
CALCULATORS-Prorate Support Buttons should be switched

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#618]
I think the "Ok" and "Cancel" buttons placement should be switched.  I will update this and submit pull request.

**Comment by theVKC** [comment]
Agreed, and thank you @heatherallen!

**Comment by theVKC** [comment]
Still need testers for this. Can we confirm this is now working? Need two agencies to confirm.

@MN-Script-Team/prism-scriptwriters?

**Comment by paschell** [comment]
It worked in Anoka, tested on 3 cases.  Thanks

**Comment by theVKC** [comment]
Thanks Pam!

**Comment by theVKC** [comment]
(Still need an additional separate agency to confirm before I pull it through and close the issue)

**Comment by theVKC** [comment]
OK, I'm going to start picking on counties. @MN-Script-Team/prism-wright, can you test this and make sure it's working?

**Comment by khiestand** [comment]
This is working in Wright Co!

**Comment by theVKC** [comment]
Boom!!!!!
