### ISSUE TITLE
New Script/Enhancement Request: big search tool

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-PRISM-Scripts#619]
Hows about a worker look up tool that does not require going in to MAXIS and REPT/USER to find out who a worker is, by their X1 number?

PRISM has the USCR screen that lets you search by First Name and Last Name and there is a OSID column that includes the X1 number, HOWEVER, there is no search functionality based on that value.

If there was, we could have a script available to help staff figure out who the financial worker is based on data from MMIS -- because that lists the X1 number, but does not give you the option of finding out who that person is.

**Comment by theVKC** [comment]
Tentatively I like it. However, I wonder if there's a simpler solution out there...

1. Creating a master table (I know, I know, but maybe we can do it)
2. Asking PRISM tech folks to incorporate search functionality (might be easier)

Thoughts? Looking for feedback... go!

@MN-Script-Team/prism-scriptwriters @MN-Script-Team/prism-supervisors

**Comment by RoberT-1000** [comment]
I don't suppose there's anyway we could tap into the REPT/USER API (...I'm being facetious...) to grab that list of X1 and PW numbers dynamically...?

**Comment by theVKC** [comment]
I wonder if I could set up a loopback from SSAM...

**Comment by RoberT-1000** [comment]
By the way, to your original reply, I am interested in option 2. An update USCR would be fantastic.

**Comment by theVKC** [comment]
Consider it requested. I do have an email in about option 1 though. I'll loop that conversation in here if I find out more.

**Comment by theVKC** [comment]
Got word back from SSAM: they echoed the concern about posting this information in a public table (i.e. on GitHub or incorporated directly into our scripts). So, I think that leaves us a couple of options:

1. Create a script that creates a master table that's stored locally (this would allow use across many scripts in many areas, and gets around the concerns about where it's kept, as it can be hidden from general view by county staff using tech magic).
2. Create a financial worker searcher using REPT/USER (pretty much your initial suggestion if I'm understanding correctly).

Thoughts @RoberT-1000?

**Comment by RoberT-1000** [comment]
Thoughts:

1. I like the local spreadsheet option. We could develop a script to update the spreadsheet as needed.
2. Update to USCR? Is that an possibility?

**Comment by RoberT-1000** [comment]
That's right, "an possibility"...I'm not changing that.

**Comment by theVKC** [comment]
I'm guessing you originally said "an option" and then changed it. Flip flopper. :)

The update to the panel isn't a script process, of course. I'm raising that concern outside of this channel and will update you with an answer when I have one. :)

Benefit of a local spreadsheet is it could have wide ranging applications for scripts everywhere. You know what I did with the user lists at Anoka... we could pretty easily implement something similar here (as long as we had crystal clear instructions for how to implement such a thing).

**Comment by RoberT-1000** [comment]
Flip-flopper? No, ma'am...I wear Birkenstocks...ah, thank you very much <rim shot/>

**Comment by RoberT-1000** [comment]
<rim shot/>

**Comment by RoberT-1000** [comment]
![image](https://cloud.githubusercontent.com/assets/22157633/20114254/2191ecaa-a5b9-11e6-8aba-d7937af15103.png)

**Comment by theVKC** [comment]
@RoberT-1000: we didn't get additional feedback, but I really like the local spreadsheet option as indicated above. Would you want to do it? I'm trying to close issues today, so if you don't mind getting back to me either way, that'd be great.

If I don't hear back from anyone interested in doing this, I will close it Monday, December 5th.
