### ISSUE TITLE
New script idea:  Interview Information Sheet

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#620]
A script to produce an information sheet of high-level case and general information that can be used as a resource when meeting with a client in person.  The top half of the sheet is for the worker to use as a reference and to document any updates that need to be made to the case.  The bottom half of the sheet can be given to the client as a resource.  

For greater efficiency, this script makes use of classes.  We may want to consider whether it makes sense to add the classes to the Functions Library.

A functional draft is ready to pull request.  I am attaching the Word template the script uses.
[Interview Information Sheet.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/572461/Interview.Information.Sheet.docx)

**Comment by theVKC** [comment]
Hey @levesswe! Happy to take a look. In the future, can you submit issues via GitHub before you start active development? This is important so that I can try and track an average amount of time from idea -> solution (it's a project management piece).

In any case, documentation such as this should go through policy folks. From my high level it looks great, but I'd love feedback from counties before I forward it on. Thoughts @MN-Script-Team/prism-scriptwriters or @MN-Script-Team/prism-supervisors?

**Comment by levesswe** [comment]
If it is helpful to you, this idea was approved by Anoka supervisors on 5/12/2016.  (Yes, it has taken me 6 months to find the time to do it.)

**Comment by theVKC** [comment]
That is helpful. Please, in the future, post the issue as soon as you have the idea. We can track results in GitHub and that helps me understand internal/external workloads for you all.

**Comment by theVKC** [comment]
Can I please get some feedback on this idea from @MN-Script-Team/prism-scriptwriters or @MN-Script-Team/prism-supervisors? See above for Wendy's sheet (what the script produces).

If feedback is not received by the end of the week, I will be assuming all systems are go for a master-branch release.

**Comment by heatherallen** [comment]
I like this idea and how the information sheet looks.  I'm hoping that the bottom section could be updated so it pulls in each county's info depending on which county opens the script.

**Comment by levesswe** [comment]
My thought was that each county could make their own version of the word document and save it in their word document template directory listed in Global Variables.  I will need to update the file path in the script to reference Global Variables.

**Comment by theVKC** [comment]
For now, @levesswe: that's a great move. But we should ensure we strip out any Anoka-specific data from the source file so that counties can start with an even playing field. Also, you should be able to add the document to the docs directory in your pull (let me know if you can't, I'd be happy to help).

**Comment by theVKC** [comment]
Also, if you're following this one: https://github.com/MN-Script-Team/BZS-FuncLib/issues/234

I am planning on trying to integrate word doc downloading automatically for agencies who haven't created custom versions. So, that might be an option pretty quick.

@levesswe, if you can be a tester for that function, I can try and wrap it today...

**Comment by levesswe** [comment]
I would love to test this function.  Don't hurry on my account, though, because I just got a bunch of new cases added to my caseload.  I don't know when, exactly, I will be able to test.

**Comment by levesswe** [comment]
Attached is a generic version of the interview information sheet Word document that the script uses that agencies can use to make their own version with local resources in the bottom section.  Remember this is the template and agencies will make their own version and save in their document file path per agency global variable settings.  Any feedback/requests for changes for the template?

[interview.information.sheet.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/620367/interview.information.sheet.docx)

**Comment by jannellstearns** [comment]
It appears that this is a document that would be handed out to clients?  If so, I would suggest typing out the cch, ccc, cms, etc into what they would mean to the client:  basic support, child care support, etc.
and hopefully cut down on some phone calls!

**Comment by levesswe** [comment]
The idea is that the worker would fold the document in half, and the client would have the bottom half with the resources, and the worker would have the top half and be able to mark any updates that need to be made to prism on the paper as they meet with the client and hopefully have all the information they need to answer the most common questions.  The worker then can refer to their sheet after the interview to make updates to PRISM.

I don’t mind changing the labels if that makes it easier for people to read.  What do people think?

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment]
I think it should be much more clear on the document that the document is to be torn in half. That wasn't clear, and I'm not sure how convenient that is for everyone.

**Comment by levesswe** [comment]
We intended the sheet to tear it in half, but that isn't to say that all agencies must do so.  If some agencies want to give the whole sheet to the client, I think that is fine.

**Comment by levesswe** [comment]
Here is a new version with the obligations spelled out:
[interview.information.sheet 11-30-16.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/622070/interview.information.sheet.11-30-16.docx)

**Comment by theVKC** [comment]
So I'm looking for feedback on this one as well, @MN-Script-Team/prism-scriptwriters. :)

**Comment by KallistaImdieke** [comment]
We have been attempting to run this in stearns but are receiving an error about being able to find the document I am working with Gay to make sure it is saved in the correct spot and everything is good to go with that and then we will give more feed back ☺

**Comment by KallistaImdieke** [comment]
I just ran this script and it started to work and pull information into the word document all the way up to the Last Payment Information then I received the following error:

![capture](https://cloud.githubusercontent.com/assets/19214103/22525926/e810760e-e88e-11e6-9749-a6fb5fbc68b3.PNG)

I ran it on a case with payments and a case without payments and in both situations i received this error. 

Thanks!

**Comment by theVKC** [comment]
@levesswe, can you look at this issue that @KallistaImdieke is reporting?

**Comment by levesswe** [comment]
I haven't been able to reproduce the error message.  Anyone else having trouble?

**Comment by KallistaImdieke** [comment]
I have run this myself along with another worker here and we are both receiving this error.

**Comment by khiestand** [comment]
@levesswe @theVKC @KallistaImdieke 
We just ran this script here too, and are getting the Format Currency same error Kallista is reporting.  Also, in the docs folder the name of the word doc has "." and not "-" and that was also an issue for us here (we fixed it on our local copy).  Could we also change the variable on the word doc to not be "user"? In Wright Co it pulls our KAH7429 PC log in info, could that variable be changed so it lists the actual CSO's name?

![image](https://cloud.githubusercontent.com/assets/10159902/22792764/6f907b7c-eeb3-11e6-8e26-89dc34b02b2e.png)

**Comment by KallistaImdieke** [comment]
We had that same issue and we fixed it here on our local copy also when we figured it out.

It also pulls a funny name for us could we maybe have it pull from the worker signature?

**Comment by levesswe** [comment]
Hi all, I have also located bugs when participants have pages and pages of cases.  I will also try to fix the other bugs that have been reported while I am there.  While not a bug, since so many people have commented about the user name, i will remove that from the document and replace it with the worker signature.    Hope to have a fix soon!
