### ISSUE TITLE
MAXIS Screen Finder Bug-"Case Number Required"

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#624]
Case number function needs to be changed to "MAXIS_case_number" to correct this error.  The function "navigate_to_screen" was already changed to "navigate_to_MAXIS_screen" previously to correct part of the error.

**Comment by theVKC** [comment]
Still need testers for this. Can we confirm this is now working? Need two agencies to confirm.

@MN-Script-Team/prism-scriptwriters?

**Comment by paschell** [comment]
This is one of my all time fav scripts - I have not encountered any problems using this script of late.  Used 2 times today and several times last week.  Anoka is good to go with MAXIS screen finder.

**Comment by theVKC** [comment]
Thanks Pam! Looking for one more agency before I push it through. This will not require additional documentation because it's a simple bug fix and not a functional enhancement.

**Comment by heatherallen** [comment]
It is still working good in Scott County!

**Comment by theVKC** [comment]
Same as the other one, @heatherallen: that's wonderful AND I need someone from another (non Scott) agency to confirm as well. Two independent agencies, not including the original or DHS. That's my threshold now.

**Comment by theVKC** [comment]
OK, I'm going to start picking on counties. @MN-Script-Team/prism-wright, can you test this and make sure it's working?

**Comment by khiestand** [comment]
This is working in Wright Co!!

**Comment by theVKC** [comment]
Boom! Thank you!
