### ISSUE TITLE
Enhancement to Case Transfer script

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#628]
Auto populate the OFFICE field to always have "001" entered.

I can take this one.

**Comment by theVKC** [comment]
Can I get some feedback @MN-Script-Team/prism-scriptwriters? Looks like Kelly already completed it, just looking for confirmation that it's a good idea before accepting it. :) #democratizingtheprocessabit

**Comment by KallistaImdieke** [comment]
I like this idea

**Comment by khiestand** [comment]
OK, so maybe I can change it to not auto-populate the "001", but instead make it mandatory that three numbers are always typed in that editbox?

**Comment by paschell** [comment]
@khiestand  - I think this will work better!  YAY...

**Comment by theVKC** [comment]
If most counties are "001" and that's it, I don't see that as necessarily problematic. We could autopopulate that and then simply add logic for selections for other counties. Maybe even convert it to a dropdown with just a single option for counties with one office? How does that sound?

**Comment by paschell** [comment]
I think if you are asking users to add  or enter the addresses such as 003 001 CS2 24 why have a drop down for just the 001 part?    I like the idea of a mandatory 3 position value in the edit box.  The County field is 3 positions, the Office is 3 positions the Team is  3 positions and the Position  is 2.    Users are accustom to manually transferring cases that way, it is how PRISM works.   Maybe a message after entering the values and before the actual transfer showing what's been entered so a worker could double check the transfer data. The script also allows you to transfer cases with the 8 digit code too like 003CS028 which you can't manually do in PRISM.

**Comment by khiestand** [comment]
I can make the all of those fields mandatory, would that be better?  That way if there is a typo they will get the msgbox letting them know they are missing a number or letter.  What script/s can I look at to copy this logic? :-)

**Comment by theVKC** [comment]
If folks don't like a dropdown, don't worry about it. Just thinking out loud, quietly, on GitHub! :)

If the fields need to be entered to prevent a PRISM issue, then yes, we should make them mandatory, right?

**Comment by levesswe** [comment]
I like the idea of a dropdown.  I feel like the vast majority of the time, we will want it to be 001, and I think it will be easy enough to use logic to accommodate those few counties who have other values.

**Comment by theVKC** [comment]
@khiestand and @levesswe: do either of you know if there's a way to look up (in real time) the amount of offices a county has? If so, perhaps we could build a function to autofill a droplistbox with choices?

**Comment by paschell** [comment]
@vkc @khiestand @levesswe   Hi - You can look on OFMA enter that on the direct command line in PRISM - It stands for Office Maintenance.   Again I don't like the drop box idea.  I think Robert had some good comments regarding the data validation piece.

**Comment by theVKC** [comment]
@paschell: I'm @theVKC... note the "the" in the name. :)

Would a dropdown that automatically chooses "001" in agencies with only one option accomplish what you're discussing? I'd almost always rather use a dropdown for something with a few finite choices, because it is much easier to introduce data validation.

**Comment by paschell** [comment]
Sorry @theVKC  sometimes my fingers go so fast  I can't catch up.  :-)  I talked to a supervisor (Bill) in Anoka regarding the transfer script.  He wouldn't mind a pop up just asking him to verify so the cases correctly transfer.  He prefers to use the 8 digit user code versus the 11 digit code.  Getting some user feedback.

**Comment by khiestand** [comment]
Per discussion, close issue and leave script as is.

**Comment by theVKC** [comment]
@khiestand has added functionality to ensure the length requirements.

**Comment by theVKC** [comment]
Still need testers for this. Can we confirm this is now working? Need two agencies to confirm.

@MN-Script-Team/prism-scriptwriters?

**Comment by theVKC** [comment]
OK, I'm going to start picking on counties. @MN-Script-Team/prism-dakota @MN-Script-Team/prism-scott, can you test this and make sure it's working?

**Comment by heatherallen** [comment]
the single case transfer seems to be working properly.  i am having issues on the Transfer Caseload Top to Bottom option.  It states that we can put the 8 digit number in there but it appears it is not finding it, but when i put the 11 digit position number in it seems to run correctly.

**Comment by theVKC** [comment]
I was worried about this. @khiestand, you may recall we had a discussion about it. Can the two of you touch base on it?

**Comment by khiestand** [comment]
I think Robert was working on the bulk one, I only worked on the single one.  @RoberT-1000 - thoughts?

**Comment by theVKC** [comment]
Yes, sorry! That function is all @RoberT-1000 all the time.

**Comment by RoberT-1000** [comment]
I'll take a look

**Comment by theVKC** [comment]
I just realized this isn't the same script @khiestand edited. We should really make another issue. Can @heatherallen or @RoberT-1000 make another issue for this if there is, in fact, an issue?

**Comment by khiestand** [comment]
Ok, I think I pulled in my instructions on SIR!

**Comment by theVKC** [comment]
Instructions set, this is safe to close!
