### ISSUE TITLE
Notes: Date of hearing

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#633]
It was just brought to my attention that the drop down for this script under Motion before the court, there is no option for Paternity when you select Expro.  Can we have this added as a drop down option.  In Stearns all our Paternity go before expro first and them may move to judicial court. Thanks!

**Comment by theVKC** [comment]
Do you want it, @KallistaImdieke?

**Comment by KallistaImdieke** [comment]
Sure I can take it

**Comment by theVKC** [comment]
Wonderful. Any ETA on when you can wrap it up?

**Comment by KallistaImdieke** [comment]
Should be able to do it quick at the hackathon on Monday. I believe it should be a quick fix

**Comment by theVKC** [comment]
Beautiful. Thank you!

**Comment by heatherallen** [comment]
I would like to suggest another enhancement to this script....if Expro is selected could we add the option in the drop down of Review Hearing?

**Comment by paschell** [comment]
@heatherallen   I like it - good idea.

**Comment by theVKC** [comment]
@KallistaImdieke, any way you can make that so in your pull?

**Comment by theVKC** [comment]
Reopening for testing!

**Comment by theVKC** [comment]
Still need testers for this. Can we confirm this is now working? Need two agencies to confirm.

@MN-Script-Team/prism-scriptwriters?

**Comment by theVKC** [comment]
OK, I'm going to start picking on counties. @MN-Script-Team/prism-olmsted and @MN-Script-Team/prism-anoka, can you test this and make sure it's working?

**Comment by levesswe** [comment]
Tested and working in Anoka.  When Expro is selected, both "Review Hearing" and "Paternity" are options in the dialog.

**Comment by theVKC** [comment]
Thank you @levesswe! Still need one more county to verify it's working independently. @MN-Script-Team/prism-olmsted, you're up!

**Comment by ChrisKast** [comment]
Looks like it’s working as it should here in Olmsted.

**Comment by theVKC** [comment]
Boom! @KallistaImdieke, can you edit the instructions to say that this happens?

**Comment by theVKC** [comment]
Thanks for testing, folks!

**Comment by theVKC** [comment]
@KallistaImdieke, after reviewing the document, I don't think we need to do any more updates to the instructions. Go team!
