### ISSUE TITLE
New Script Idea -- Service of process by mail  (maybe enhancement to existing?)

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#635]
Here is the idea:

Script will create the affidavits of service by mail on both parties after checking:   GCSC to be sure that neither party has a safety concern and CARE to be sure that neither party currently has an attorney.  If both of these conditions are true, the affidavits of service by mail are created.

This may be something that can be added to the current SEPD script as an enhancement?

**Comment by KallistaImdieke** [comment]
@theVKC can you please assign this to me. Jannell would like me to work on it tomorrow at the wright county hackathon as its a priority for Stearns County with going to case banking. 

thanks!

**Comment by theVKC** [comment]
Can I get feedback on this idea from @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors?

**Comment by KallistaImdieke** [comment]
There is one already out there so we were thinking of doing an enhancement that script that would look at CARE and see if there are any attorneys on the file, look at GSCS and see if there are any safety concerns and pull this information into the dialog box and then add the worker's signature to it,  a check box on if the service was directed by the county attorney and have it make a CAAD note with what was served.  who served it and if the County Attorney was the one who advise who needed to be served.

**Comment by heatherallen** [comment]
I like this idea of having it look at GCSC and CARE to see if there are safety concerns and/or if party's have attorney's.  I'm assuming you are enhancing it so that if a party does have an attorney the affidavit would show a copy was sent to the attorney as well?

**Comment by jannellstearns** [comment]
Also have the script automatically populate the case number instead of having it be entered by the worker.

**Comment by KallistaImdieke** [comment]
Right now you can pick to send it to and one, all or variety of NCP, CP, NCP attorney and CP's attorney. so if you wanted to send to CP and CP's attorney you can select to do that.

**Comment by levesswe** [comment]
So if there are safety concerns on GCSC, what will happen?  Change to Confidential to true? (I love that idea!)

**Comment by theVKC** [comment]
Bump! Can I get a response to @levesswe's question? This will help build a better script. Also, do any scriptwriters want to take this one on?

**Comment by jannellstearns** [comment]
Not having done this piece for a long time, if my interpretation is correct, we would be coding confidential to "Y" in the dord document.  If so -- LOVE it and would definitely want that to happen.

Great idea Wendy!!!

**Comment by theVKC** [comment]
Well, the feedback seems to indicate this is a good idea, so thanks. Any takers? I'm marking it as help wanted and will give it two weeks!

Sleeper timer: 12/12/2016

**Comment by theVKC** [comment]
Wait! Kallista already took it! Belay that last message! @KallistaImdieke, any eta on it? Right now it'll be marked as "backlog" but if you've been working it, I'll throw it into the right bucket!

**Comment by KallistaImdieke** [comment]
I can take this

**Comment by KallistaImdieke** [comment]
I worked on it at the last hackathon but I had started from scratch not knowing this one was out there.  I will combine the two together but not sure if I will get to it until the next hackathon.

Thanks!

**Comment by theVKC** [comment]
@KallistaImdieke: is there a chance there's a duplicate issue? Or were you working on this without a GitHub issue, not knowing there was, in fact, a GitHub issue? :)

**Comment by KallistaImdieke** [comment]
It’s not a duplicate issue just didn’t realize there was a script out there that did a lot of what we wanted. So I will work on updating that one

**Comment by theVKC** [comment]
Good deal. I've updated this to be an "enhancement" instead.

**Comment by KallistaImdieke** [comment]
@theVKC do you know if we have a script out there already that pulls information from Prism into the dialog box that I can look at?

**Comment by KallistaImdieke** [comment]
I have enhanced this script to pull into the dialog box if there is an Attorney or safety concerns on the case.  

We also had it automatically take the address from the affidavit, put it into an excel spreadsheet and then print it that as a cover letter to attach to the documents as a cover letter so we could use the envelopes with windows and our process specialists do not need to write the address on the envelopes.  Not sure if this is something that other counties would be interested in also or if i should upload a version without the extra excel spreadsheet printing with in?  

Let me know your thoughts so I can finish this up and get it submitted 

Thanks!!
