### ISSUE TITLE
Replace NAV scripts with "favorites": create additional secret buttons on the Power Pad so that nav scripts can be auto-mapped along with favorite scripts

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#636]
This is a unique concept. I have an idea for an enhancement and I want to map it out a bit.

1. Create a "favorites" button, that lets you either select a script or indicate a PRISM screen to navigate to.
2. The user can map each favorite to a key combination (Ctrl-F1 through Ctrl-F12), or list them separately on the favorites button.
3. Each "button" for F1-F12 is, in fact, a hidden button on the Power Pad (doesn't show as visible to most users).
4. The favorites are stored as a text file in My Documents.
5. The F1-F12 hidden buttons on the Power Pad are rerouted to redirect scripts which load the F1-F12 functions from My Documents.
6. All screen-based NAV buttons are replaced by this functionality, streamlining the Power Pad significantly.
7. Better ADA compliance as users can now map scripts to specific key combinations, so the mouse is less significant.

Looking for feedback. Today at hackathon, folks are supportive. Looking for feedback from @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors.

**Comment by jlmartinone** [comment]
I love the idea.  There are a handful of scripts I use regularly and it would be awesome to them all just 1 “F” key away!

[cid:image001.png@01D23E60.9C1C2B40]Thank you,
Jodi Martin
Child Support Officer
Wright County
763.682.7439
Fax 763.682.8920

How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by RoberT-1000** [comment]
You mean something like this...that allows users to pick their favorite scripts from a list that updates itself dynamically from the complete list of scripts file?

![image](https://cloud.githubusercontent.com/assets/22157633/20276302/4fce0e08-aa61-11e6-8942-0333de7df28d.png)

**Comment by RoberT-1000** [comment]
...because Anoka FAS love it...and Anoka CSOs are learning to love it...

**Comment by theVKC** [comment]
Yes yes! Except mine can be tied to hotkeys too. :)

**Comment by RoberT-1000** [comment]
Additional info >> what we have saves the text file to the H drive (Anoka-specific mapping...you know about it...and I wouldn't want that to change for Anoka users) so it follows them to different machines...and it excludes UTILITIES and NAV scripts since there are easy access to those on the powerpad.

**Comment by theVKC** [comment]
This is going forward. NAV script retirement is coming, replaced with power hotkeying and a favorites button.

**Comment by theVKC** [comment]
Decision made.

I'm going to pull in the favorites as-is without hotkey generation, then create a second issue that adds hotkeys in. This functionality has been closed to the master branch for far too long.

**Comment by theVKC** [comment]
Hey all!! Can I get some testers for the new favorites script? @MN-Script-Team/prism-scriptwriters? @MN-Script-Team/prism-supervisors?

**Comment by heatherallen** [comment]
I and a couple of my coworkers here in Scott have tested and seems to be working great.  Just one little piece of constructive criticism I received was that county's that are new to scripts or users new to scripts may only use scripts they are more comfortable or familiar with (the one's saved under their Favorites)  instead of trying out different ones that are potentially out there.
But other than that I LOVE IT!!

**Comment by theVKC** [comment]
A bug has been found! When called from the Utilities menu the `cs_script` class is broken, because the class is loaded from within a `run_from_GitHub` function, and that doesn't have persistence past the original list of scripts. In other words: Power Pad yay, Utilities menu nay. This isn't a big deal, except that my Changelog function needs it in the list, and I want it to work, etc..

FuncLib needs to `executeglobal` the code, instead of just `execute`. This is coming shortly.

**Comment by theVKC** [comment]
Confirmed to be working in Wright County (but their Power Pad needs the button connected to a redirect file... long story).

So, this one is good! Thanks folks!
