### ISSUE TITLE
New Idea - County Attorney Referral Note

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#647]
Stearns County has this that we have been using but wanted to share it with the collaborative as others may also want to use it. 

Can you please assign this to me and as soon as I have made the updates with the code changes to the new code then I will submit it.  Thanks!

**Comment by KallistaImdieke** [comment]
@theVKC I have made the changes to the beginning on this script so that it has all the correct language (loading functions from GitHub, and Changelog)  and changed it to pull in the County Attorney's for each county vs just Stearns County Specific. However I am receiving the following error: 

![capture](https://cloud.githubusercontent.com/assets/19214103/22522040/b6cd8b2c-e87f-11e6-9330-0e9467d94f41.PNG)

would this have something to do with adding the following language to the script? 

![capture2](https://cloud.githubusercontent.com/assets/19214103/22522170/4cd77bb4-e880-11e6-8d65-ffa213ec2b83.PNG)

those are the only two things I changed besides formating the name as county-attorney-referral.vbs and the script we have in agency custom works but the one I am trying to update to put out on GitHub is giving an error. 

Thanks!

**Comment by theVKC** [comment]
Is there a chance you don't have a globvar reference? I see that bug when I try running something that's an array defined in global variables. If I were you, I'd copy the line you have in globvar about county attorneys into the top of your script, test it, then remove it before you pull it in.

**Comment by KallistaImdieke** [comment]
@theVKC so the part of the script that is causing the issue is when I try to pull in the County attorneys from what each county puts into their variables.  In other scripts that I know does this & that work it has the following language 
"call convert_array_to_droplist_items(county_attorney_array, county_attorney_list)"
but when I try to use this in my script I get the above error.  If I take this out this script runs but there are no attorneys to select from.  do you know why that is?

**Comment by theVKC** [comment]
Are you calling in Global Variables?

When using scripts in production, the attorneys are stored on the global variables file. If you are not using GitHub Desktop for all of the testing, there's a good chance it isn't pulling up that file.

You can pretty easily get past it by copying the line of code from ~globvar.vbs which contains your county_attorney_list, and pasting it near the top of your script. Test it, then after testing, delete that line before submitting.
