### ISSUE TITLE
Notes - Pay or report is broken

### ISSUE THREAD

**Issue by paschell** [MN-Script-Team/DHS-PRISM-Scripts#649]
When running the script the dropdown asking for the year, shows first_year, second_year as the value.  Should be 2016, 2017.

**Comment by theVKC** [comment]
Hmmm. @RoberT-1000 recently updated this script but as far as I know didn't touch those values. Is he around? Can he take a look?

**Comment by RoberT-1000** [comment]
I'm thinking the dialog editor did that. I can see where the problem is...

**Comment by theVKC** [comment]
Thanks @RoberT-1000! Can you fix it for me?

**Comment by RoberT-1000** [comment]
Yep...AND I'm going to add values to the changelog...which I need to work on...

**Comment by theVKC** [comment]
Boom! Thank you!
