### ISSUE TITLE
Insurance Policy Review M1490 and/or M1491

### ISSUE THREAD

**Issue by TammyStearns** [MN-Script-Team/DHS-PRISM-Scripts#650]
This script would review existing M1490 EMPLYR ENDED-CK INS and
M1491 EMPLOYER ENDED-CK CP 
If ncp or cp's employment is updated with an End Date, worklist M1490 or M1491 are created for worker to review to see if there is active insurance information on NCPD or CPPD with the employer that was ended.  If no insurance information is listed or if all insurance information is ended, this script will automatically purge the M1490 or M1491 worklists.

Kallista and I worked on this script together on 10/19/16 at the Wright County hackathon.  We have worked on it for about 5 hours so far and have the majority of the script written.  
Veronica, please assign this to me and Kallista to continue to work on.  Thank you.

**Comment by theVKC** [comment]
Can I get some feedback on this one @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors?

**Comment by heatherallen** [comment]
I think this is a great idea!! Good work you guys!

**Comment by theVKC** [comment]
@TammyStearns and @KallistaImdieke: can I get an update on where this is at? I know you worked on it, but I want to know an ETA. Is it backlogged or in progress?

**Comment by TammyStearns** [comment]
This one is in progress.  I believe it is close to being done.  I just don't know when I can work on it again before the next hackathon.  Hopefully it will be completed by the end of next month's hackathon.

**Comment by theVKC** [comment]
Good deal, THANK YOU for updating me. I'm going to move it to "backlog" since you don't know when you'll be working on it again, but I won't close it unless we don't have movement for a couple of months.
