### ISSUE TITLE
Quick Caad maximum allowance?

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#670]
I have a worker who has entered 12, and it cuts off after that.  Does the dialog box need to be bigger? Or is there a limit to only 12 "favorites"?  Also, she was able to enter one that was already saved.  Is there logic that could be coded to have a message box pop up if that caad code is already in their favorites?

**Comment by theVKC** [comment]
First off, since this still has an open issue ( #453), I don't think we should be having the discussion here. Could you go to that issue and report your idea?
