### ISSUE TITLE
Bug when using bulk case transfer

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#671]
When using the Transfer Caseload Top to Bottom, there seems to be a bug where the script is not converting the 8 digit position code to the 11 digit position.  Getting error that the 8 digit person is not found.

**Comment by RoberT-1000** [comment]
I'll take a look

**Comment by RoberT-1000** [comment]
What is your 8-digit person number you are using?

**Comment by heatherallen** [comment]
It was one in the training region....could that be why?

**Comment by RoberT-1000** [comment]
If this is just an error in the training region, I'm not going to bother looking.

**Comment by RoberT-1000** [comment]
I had a lot of difficulty getting this script to work in the training region that I have not experienced in production.

**Comment by RoberT-1000** [comment]
By the way, there is a developer mode. You enable it by entering UUDDLRLRBA and then a number in the field where you are asked to enter how many people you are transferring cases to. It will do everything except transfer cases.

**Comment by theVKC** [comment]
Hey folks! Can we confirm that it's working in a production environment as expected? Perhaps one of the @MN-Script-Team/prism-supervisors has used it recently and can report?

**Comment by paschell** [comment]
My supervisor has used it twice in the last month to transfer whole caseloads with no problems reported.  He uses the 8 digit user ID (for example 003CS028).

**Comment by theVKC** [comment]
@heatherallen, are you OK with closing this one since it doesn't appear the issue happens in production?

**Comment by heatherallen** [comment]
yes good to close!
