### ISSUE TITLE
Enhancement to Ct Order Request Notes Script

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#672]
I am going to add a drop down option of E-Filed, as that is now how we have to request orders in Wright (and probably other counties).

I will take this one!

**Comment by theVKC** [comment]
#673 pulled this in. :)

**Comment by theVKC** [comment]
Can I get testers? Two non-Wright agencies to confirm it looks pretty? @MN-Script-Team/prism-scriptwriters?

**Comment by heatherallen** [comment]
it works for me!

**Comment by heatherallen** [comment]
works for me too!

**Comment by levesswe** [comment]
Works for me, too!

**Comment by khiestand** [comment]
You ladies are the best!

**Comment by khiestand** [comment]
@theVKC I think you can close this one!
