### ISSUE TITLE
Enhancement for Arrears Mgmt Review Script

### ISSUE THREAD

**Issue by wrightcountykaren** [MN-Script-Team/DHS-PRISM-Scripts#675]
I would like to have a section added to this script for the supervisors to use to either approve or deny the AMPP request.  My thoughts are to add another small section to the script with the 3 Supervisor CAAD codes, a checkbox with Approved as requested, a checkbox with Approved with modifications-next to that a field to list the changes, a check box with Denied and next to that a Reason field for free flow typing.

**Comment by theVKC** [comment]
Two questions!

1. @wrightcountykaren, do you foresee a need to restrict visibility of this functionality to non-supervisors? Is it OK if CSOs see it?
2. @MN-Script-Team/prism-supervisors, what do you think?

**Comment by wrightcountykaren** [comment]
I don't see a need to restrict visibility of the supervisor section for a CSO.  The CSO is going to see the note once it is made in PRISM anyway.  The note will direct them to take the next action on the case.

**Comment by theVKC** [comment]
Good deal, @wrightcountykaren, because that functionality doesn't exist yet!

**Comment by jlmartinone** [comment]
You can assign this to me...

**Comment by theVKC** [comment]
@jlmartinone has completed this! Can we get some testers? @MN-Script-Team/prism-stearns? @MN-Script-Team/prism-anoka?

**Comment by jannellstearns** [comment]
we try to have arrears management meetings weekly, so we will try this out at our next one!  @KallistaImdieke  @TammyStearns  can you be available to help with this piece so we can test and provide feedback!

**Comment by theVKC** [comment]
Closing this one due to the limited number of available testers. It seems the source county (Wright) is fine with the end result (no new issues on the subject). Can always re-evaluate. :)
