### ISSUE TITLE
Income Verification word doc bug (Actions/Income verification)

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#676]
When I started this script, it popped up to the dialog box where I needed to start the script again.  the script then ran and gave me this error:

Script error at Line 1, column 1:
sorry we couldn't find your file. is it possible it was moved, renamed or deleted?

**Comment by CDPotter** [comment]
Is it happening repeatedly or just once?

Also just so I make sure I'm following:

You clicked Actions
Actions menu opened
clicked income verification
Actions menu opened again?
Clicked income verification
income verification opened and then error-ed out?

**Comment by jannellstearns** [comment]
I tried running the script 3 times and it happened the same way each time.

Your clarification was exactly what happened.
I would add to the last line that the income verification script seemed to run and then error-ed out.  It looked like it might have been at the point where it would generate the word document, but I am not 100% sure.

**Comment by CDPotter** [comment]
Hmm... I'm guessing the script error part is the inability to find the word document as well. Please have someone else @MN-Script-Team/prism-stearns check. You may want to also check your global variables files to make sure the file path is correct. Here is what the script uses for the file path:

word_documents_folder_path & "child-support-income-verification-form.docx"

Check that in Global variables the word_documents_folder_path is correct and that "child-support-income-verification-form.docx" file is named exactly that and stored there. 

As for the other issues of the looping Menu that one is interesting, can you see if it happens on other scripts or with other stearns users we well?

Anyone else hitting this issue? @MN-Script-Team/prism-scriptwriters

**Comment by RoberT-1000** [comment]
I'll take a look. I had the script re-open the Actions menu as well.

**Comment by RoberT-1000** [comment]
We seem to be having a lot of problems with Word documents...

**Comment by RoberT-1000** [comment]
I've found one problem already...

![image](https://cloud.githubusercontent.com/assets/22157633/20805770/c8ded80e-b7bd-11e6-991d-4a5d376dc58d.png)


I'm going to create an issue for this and submit a pull request. I can't see how this script would ever have worked.

**Comment by RoberT-1000** [comment]
OK, I can verify that this script won't work in Anoka County because we don't have a document called "child-support-income-verification-form.docx" in the word_documents_folder_path. @jannellstearns >> Do you have this document?

How do we has?

**Comment by CDPotter** [comment]
Looks like it was added 2 days ago. https://github.com/MN-Script-Team/DHS-PRISM-Scripts/tree/master/docs

**Comment by RoberT-1000** [comment]
Splendid! I will take a look.

**Comment by RoberT-1000** [comment]
Got it working.

**Comment by jannellstearns** [comment]
@RoberT-1000, I will have someone check into the Doc path here -- I thought we had it working previously, but I may be mistaken.

**Comment by RoberT-1000** [comment]
I have submitted a pull request...let's see if those updates make a difference.

**Comment by KallistaImdieke** [comment]
the script was working when I submitted it and I forwarded the word document this script uses to Veronica

**Comment by CDPotter** [comment]
Pull has been merged. @RoberT-1000 @jannellstearns @KallistaImdieke how are things looking now?

**Comment by GayS** [comment]
our global variable file has the correct path however the document "child-support-income-verification-form.docx" does not exist.

**Comment by CDPotter** [comment]
Since it was only published 2 days ago if you didn't download it yet (I'm assuming because Kallista worked on it she had it downloaded locally) it would be causing problems.

**Comment by KallistaImdieke** [comment]
it's entering the date wrong when you select the 3-6-12 months (I selected 3 months and got the following 

![capture](https://cloud.githubusercontent.com/assets/19214103/20808296/aaa8b576-b7c7-11e6-8b79-b3ecd6621683.PNG)

OI know this was language that @theVKC did and added to the script after I submitted it. 

When I used the date range I got the following error, 

![capture2](https://cloud.githubusercontent.com/assets/19214103/20808362/e65ee28e-b7c7-11e6-8ff4-f453b64ac465.PNG)

**Comment by KallistaImdieke** [comment]
yes when I was testing it I have the document saved locally

**Comment by RoberT-1000** [comment]
I'll fix the date write

**Comment by RoberT-1000** [comment]
Otherwise, it's loading now.

**Comment by theVKC** [comment]
This is pulled in to master, can I get confirmations from @KallistaImdieke that it's now working in Stearns?

How about another county to test it? @MN-Script-Team/prism-olmsted? Can you check it as well?

**Comment by theVKC** [comment]
OK, hold up.

I'm closing this issue as it's tied to the word doc which was named locally.

**Comment by KallistaImdieke** [comment]
Jannell and I tested it in Stearns and the word document is working the only thing that wasn't working this morning was the date function when you would pick 3-6-12 months.  I can retest it though to see if that is now working..

**Comment by theVKC** [comment]
Sorry folks. Closing this thread. @KallistaImdieke, please redirect your point about the write_date (which I just pulled in minutes ago) to #678.

**Comment by theVKC** [comment]
(Thread closed to avoid confusion with three issues targeting one script, this issue was resolved by an issue with a saved file at the county level)
