### ISSUE TITLE
Bug - Actions Income Verification Dialog bug

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-PRISM-Scripts#677]
The dialog is not named the same in the build and the call. I'll fix it.

![image](https://cloud.githubusercontent.com/assets/22157633/20805829/f9bbfdc6-b7bd-11e6-9de8-247aceee9c8d.png)

**Comment by theVKC** [comment]
@MN-Script-Team/prism-stearns and @MN-Script-Team/prism-olmsted, can you check that both this AND the write_date functionality for this is working?

**Comment by jannellstearns** [comment]
write date functionality is not working in Stearns. 
at DDPL -  in the dated issued from field it entered:  /12/2/20155

**Comment by theVKC** [comment]
Just pulled in another pull which should address this.

**Comment by theVKC** [comment]
@MN-Script-Team/prism-stearns and @MN-Script-Team/prism-olmsted, can I get some feedback from this one?

**Comment by theVKC** [comment]
Appears resolved by bug.
