### ISSUE TITLE
write date Bug - Actions Income Verification

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-PRISM-Scripts#678]
The script is not writing the dates on PALC correctly.

Assign to me.

**Comment by KallistaImdieke** [comment]
Hey Robert I am not sure if you made this correction yet But Janelle tested it this morning and is still getting the following error when she selects the 3-6-12 month checkbox  (date is not writing in the correct format)

![capture](https://cloud.githubusercontent.com/assets/19214103/20836875/f67c73d0-b866-11e6-9edd-485e5a2125c4.PNG)

Thanks!

**Comment by CDPotter** [comment]
I didn't pull in Robert's fix because I was unsure the status of the WriteDate function. I remember seeing emails recently with reports of it not working for all users. I'd be happy to pull if but could someone bring me up to date on the status of it?

**Comment by KallistaImdieke** [comment]
Ok I will let Jannell know.  I am not sure of what the status of the WriteDate function is.

Thanks!

**Comment by RoberT-1000** [comment]
I tested it yesterday afternoon and found it to be working.

**Comment by RoberT-1000** [comment]
Idea: To get around the issue of agencies not having the correct file in the correct location, the script should start with...

`SET check_for_doc = CreateObject("Scripting.FileSystemObject")`
`doc_location = word_documents_folder_path & "child-support-income-verification-form.docx"`
`IF check_for_doc.FileExists(doc_location) THEN`
`	'the script`
`ELSE`
`	script_end_procedure("Your agency is not properly configured to run this script. A required Word document must exist at " & doc_location & " but it cannot be found. Please contact a scripts administrator to resolve this issue.")`
`END IF`

...that way, the script stops right away and informs the user that the agency is not properly configured to run that particular script. The same could be done for the Court Prep worksheet as well.

**Comment by theVKC** [comment]
All Word Doc issues should be resolved when this issue gets resolved: https://github.com/MN-Script-Team/BZS-FuncLib/issues/234. I could see something like this being worked out within it... IF it's needed (my idea involves downloading the file from GitHub in real time, and I'm testing it as we speak).

The `write_date` bug is related to MAXIS use and not PRISM use per se. It's already a separate issue (https://github.com/MN-Script-Team/BZS-FuncLib/issues/321) and the function is working well in PRISM.

**Comment by KallistaImdieke** [comment]
I tested out this script again, since it looks like you said you pulled in the correction in the other thread. Not sure if it takes a little bit for the change with the writedate to take affect? I didn't get a notice that a change was made to the script. 

As of right now the script runs and creates the word document when I use the "custom date range"  however it does not work when I use the 3-6-12 month field still looks like its adding the date like 6/2/2016 when it needs to be added as 06/02/2016.
  
Thanks!

**Comment by theVKC** [comment]
It can take a minute or two. Sometimes it takes a bit longer. Some folks say closing down and rebooting helps, I don't know if I can vouch for that. Try again in a few minutes?

@RoberT-1000, I know your folks are on master, can you confirm that you're seeing the change?

**Comment by RoberT-1000** [comment]
The changes I made seem to be working. I didn't scan it very thoroughly for how many places I should have added `write_date`

I've stress tested the script now and there are a few other places where `write_date` needs to be added. There is no validation to make sure the script is writing MM/DD/YYYY format on DDPL, I can create a new issue for that and submit another fix.

**Comment by RoberT-1000** [comment]
Actually...I won't create a new issue...this one is already for `write_date`

**Comment by RoberT-1000** [comment]
@KallistaImdieke >> I'm going to do a little house keeping on the script...indentation err_msg handling and the like. It will make the script easier to debug in the future. I'm not doing anything that will change the functionality of the script.

**Comment by KallistaImdieke** [comment]
Ok, thanks!

**Comment by RoberT-1000** [comment]
@theVKC >> I have a tested, working Income Verification to pull in.

**Comment by theVKC** [comment]
Pulled in, looking for testers! :)

**Comment by paschell** [comment]
The general idea behind this script is good.  The WORD document is confusing because I am assuming that the first amount or "The Total amount she received"  was taken from DDPL (those are actual $ CP receives LESS fees)  The second amount "She received $XXX.xx on case number" is taken from PALC which is NOT LESS fees.  So in this particular test the total amount she received on ALL cases was less than what she received on the 1 case.   Confusing.   I think if you are going to do these totals they need to come from the same PRISM screen.  I think there has been talk about displaying the DDPL amounts and separating by cases at that level but that idea was put to rest for some reason.

As is, this script is not workable and provides differing data to the client, which is confusing and would prompt more contact.

**Comment by KallistaImdieke** [comment]
I can change the word document to note that the one is before any fees and the other is after fees to make this less confusing on NPA cases.  Normally our office would use this on a case where they are on assistance because the place is requesting the information.

**Comment by paschell** [comment]
@KallistaImdieke - that would help to add a disclaimer of some sort.  If the reason for utilizing the script is for the purpose of giving payment information to HUD or housing authorities then this script is OK with the disclaimer.  In Anoka, it is our policy not to provide information directly to HUD or housing authorities or even to clients as they can access through child support online.  :-)

**Comment by theVKC** [comment]
Can I get two agencies to test this script @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors?

**Comment by KallistaImdieke** [comment]
I updated the word document to state if the amount withheld is prior to fees or after fees and changed the "her" stated of the document to "obligee" 

[child-support-income-verification-form.docx](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/745816/child-support-income-verification-form.docx)

**Comment by theVKC** [comment]
@KallistaImdieke: any chance you can try and upload this document?

**Comment by theVKC** [comment]
@KallistaImdieke did you get this document uploaded?

**Comment by KallistaImdieke** [comment]
@theVKC how would I do that?? I attached it in the comments above but I am not sure where else to upload it?  Thanks!  As soon as I have this information I will get this taken care of.

**Comment by KallistaImdieke** [comment]
@theVKC I am going to try and upload this document now it looks like this issue and issue #519 are the same thing (at least they are both waiting for this document).  Thanks!
