### ISSUE TITLE
Enhancement for Returned Mail script

### ISSUE THREAD

**Issue by wrightcountykaren** [MN-Script-Team/DHS-PRISM-Scripts#684]
Can an enhancement be made to the returned mail script that makes the script pause after it gets to the NCDD or CPDD screen with a message box that says please review the address, is this the same address you'd like to remove?  With a Ok to continue or Cancel Script button.  The worker would have to click on ok for the script to run and for the address to be removed from those screens.  
Or some wording like that.

**Comment by theVKC** [comment]
Rather than pause it to look at PRISM, I'd rather it display a pop-up with the info (accessibility reasons). I love that idea though. Any takers?

**Comment by wrightcountykaren** [comment]
Oh yes.  I like having the address displayed in that box that even better ☺.

Karen Popken
Wright County Child Support Supervisor
Phone: 763-682-7403
How did I do today? Click here to complete our customer service survey.<https://www.surveymonkey.com/r/WCHHS_CSS>

**Comment by wrightcountykaren** [comment]
Additional enhancement for this script.  There are several CAAD options that can be used when noting returned mail.  Should we have a drop down so the worker could choose which CAAD option would be the most appropriate?

**Comment by levesswe** [comment]
I think that is a  great idea!

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment]
Looking for takers on this one, @MN-Script-Team/prism-scriptwriters!

**Comment by theVKC** [comment]
@khiestand has completed this and it's in master. Can I get testers? Perhaps @MN-Script-Team/prism-stearns and @MN-Script-Team/prism-olmsted would want to check it out?

**Comment by theVKC** [comment]
Still awaiting feedback, folks. @MN-Script-Team/prism-scriptwriters

**Comment by paschell** [comment]
I like the enhancements.  I used this script changing the address to unknown, changing the addr to some other address and also just CAAD noting.  It worked well for those 3 scenarios.  The fact that it has a few more message alerts before completing the action is a  good thing!  Thanks and nice job creating and enhancing this script.

**Comment by theVKC** [comment]
There's one agency confirming, thanks Pam! Can I get another?

**Comment by jannellstearns** [comment]
we have used this script here and the CSO really liked it.  We haven't used the address update feature based on how we process returned mail, but this script is will be leading to an internal discussion about returned mail and possibly changing how this task is performed -- reducing number of handoffs!  LEAN LEAN LEAN!!!  Love it!!!

**Comment by theVKC** [comment]
Boom! Thanks Jannell!
