### ISSUE TITLE
Enhancement for Contempt Hearing Notice script

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#688]
add functionality for CSO to automatically create a worklist if NCP is required to do specific things as part of contempt hearing such as make a payment of a specific $ amount by a specific date.

**Comment by theVKC** [comment]
Any thoughts @MN-Script-Team/prism-scriptwriters or @MN-Script-Team/prism-supervisors?

**Comment by heatherallen** [comment]
I like this idea!

**Comment by jlmartinone** [comment]
I agree - good idea!

**Comment by wrightcountykaren** [comment]
Great idea!

**Comment by KallistaImdieke** [comment]
I like this idea!

**Comment by jannellstearns** [comment]
If this is still floating as a possible enhancement, as we have used this script more -- functionality to allow the next hearing date (if known) be built on the CAHL screen.  Or the option to link to a script that will build a CAHL record.

**Comment by heatherallen** [comment]
I like this idea of creating CAHL record.  and I do think this function could be used for other scripts as well.

**Comment by theVKC** [comment]
@heatherallen has volunteered!
