### ISSUE TITLE
New Script Idea: Convert Proposed CORD orders to a WORD and/or PDF document

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#689]
We were just informed by our court administration that our proposed orders need to be efiled in a WORD doc and PDF doc.  Most of our workers do the proposed order using CORD.  Do we think there is a way to make this possible??? Jannell from Stearns was included in our discussion here in Scott County and she was thinking the scrip could work somewhat along the lines as the Send Memo DORD doc?? Thoughts from other counties?

**Comment by theVKC** [comment]
Any thoughts from @MN-Script-Team/prism-scriptwriters or @MN-Script-Team/prism-supervisors?

**Comment by jannellstearns** [comment]
This could be a great tool to develop!  Documents would still be on PRISM, but might allow for some interesting workflows County Attorney's Offices in a more electronic environment for updating work!

**Comment by wrightcountykaren** [comment]
That is odd that your Court Admin would want it in both formats??  Eventually I would anticipate that they are going to require searchable PDF files, so if we could figure out a way to export the orders from CORD into a PDF, I think that would be a great idea.

**Comment by theVKC** [comment]
PDF is hard because of licensing for Adobe.

Word: not so hard. It's a Microsoft product and they've created a pretty open method of updating it. :)

**Comment by jannellstearns** [comment]
My best guess (not being techie) is that each county would have a way of doing a conversion of WORD documents into a format that would be able to be e-filed.  As far as I know, our attorney's office does the majority of their document formatting in WORD, but I can sure check if that would be helpful.

**Comment by jannellstearns** [comment]
This was just sent to counties today regarding this very idea from courts. The document can be filed as a word document in very specific counties to start and then rolled out throughout the state:

A new document filing option is available in the Minnesota eFile & eServe (eFS) system.  This new option permits filers in specific court locations (see below) to file proposed order documents in a Microsoft Word version in addition to the required PDF version.  This change is a result of the electronic enhancements that are part of the continued efforts of the Minnesota Judicial Branch to move toward a fully electronic case file.  

Please note:   Word documents submitted through the eFS system must have a .docx extension.  Those with a .doc extension cannot be accepted.  Documents created in Microsoft Word 2007 or newer will provide the necessary .docx document extension. 

Locations and dates:
•	Rice County:  January 7, 2016
•	Scott County:  October 21, 2016
•	Morrison County:  October 28, 2016
•	Hennepin County Juvenile Division:  November 3, 2016
•	Ramsey County Civil Division:  November 10, 2016
•	NEW Freeborn County:  January 9, 2017
•	NEW Steele County:  January 9, 2017

This filing option is expected to be made available in additional court locations throughout 2017 as automated workflow is rolled out statewide.

**Comment by levesswe** [comment]
This is a great idea if you can do it!  Interstate would love to send CORD docs by fax without printing everything out!  Also, for efiling, if you can export CORD docs to Word, users with compatible software would be able to convert the Word versions to PDFs themselves.  Also, I have some users who would love to start with a CORD-generated doc and make changes in Word!

**Comment by RoberT-1000** [comment]
I can share what Anoka has worked on for this project. We tried and failed and walked away in favor of a vendored solution (going live April 3)

**Comment by RoberT-1000** [comment]
I'm sorry @levesswe , but I will also share a decision made by Anoka management on this topic as we have worked on a more streamlined document sharing project with Anoka CAO. The PCL software is a part of that project.

- We do not want users making changes to documents that originated in PRISM once they have been extracted from PRISM. To do so would be to effectively maintain two production versions of a document. This would cause unnecessary confusion. PRISM is the system of record and any changes to CORD documents should be made in PRISM.

**Comment by RoberT-1000** [comment]
[ACTIONS - NOTICE TO WORD.txt](https://github.com/MN-Script-Team/DHS-PRISM-Scripts/files/832412/ACTIONS.-.NOTICE.TO.WORD.txt)

**Comment by levesswe** [comment]
That’s a good point, Robert.  Somehow I had forgotten that piece.

Wendy LeVesseur
Child Support Officer

Anoka County Government Center
2100 3rd Avenue, Suite 401
Anoka, MN 55303
763-422-7323

**Comment by theVKC** [comment]
Can I get an update on this one? Keep it open? Closed? @heatherallen?

**Comment by heatherallen** [comment]
Maybe close for now as I'm not sure if it is a high priority at this point.  Here at Scott County I believe we are working on getting a system that could convert a PDF to Word. But I think down the road it may be useful to look at doing a script that could spell check our CORD docs and be converted to a WORD doc to make changes more easily.  Those would be my thoughts.

**Comment by RoberT-1000** [comment]
@heatherallen  if all you're looking to do is spell check documents, check out the script I shared in this thread. We didn't want to use it because it looks crap, but it still grabs all of your text and puts it into Word which will allow you to spell check.

**Comment by theVKC** [comment]
We occasionally hear of problems on the Word spell checking front, I think mostly due to challenges with non-standard installs (like, seriously, some people apparently have portable Word installs or something).

I have a dream to use something like GNU Aspell or some reasonable facsimile to provide spell checking without the need for a second app on the computer. I've successfully worked with web-hosted APIs in other areas to provide spell checking, but this would not work with FTI for obvious reasons. We'd have to host it, causing all the security concerns. So, I keep dreaming of local solutions, and for now, Word is the gold standard.

As you suggested, @heatherallen, let's close it.
