### ISSUE TITLE
List Generator - No Pay   Enhancement request

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#691]
This script is awesome!  In looking at the list that generated, I would have one enhancement idea - Is it possible to add a check of CACL to see if there is an approved case closure record on the case?  This would remove any of the cases that are not fully closed on PRISM, but have been approved for closure and are in the 60 day wait period. (let me know if this doesn't make sense)

**Comment by theVKC** [comment]
Any feedback from @MN-Script-Team/prism-scriptwriters? @MN-Script-Team/prism-supervisors?

**Comment by theVKC** [comment]
Stearns has this but believes it has a county specific variable, which they'll fix before pulling it in Pythonically. Thanks folks!
