### ISSUE TITLE
Worker Signature Missing from NOTES scripts

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#694]
Worker Sig has been DIM'ed in the following notes scripts, it doesn't autofill the worker sig.  Needs to be removed.

Waiver of Personal Service
Case Initiation Docs Rec'd
Ct Order Request
CSENET
Invoices
MES Financial Docs Sent

I will take this one.

**Comment by theVKC** [comment]
Wendy and Heather have agreed to test. Thank you!

**Comment by heatherallen** [comment]
my worker signature is still not populated on the one's listed above as well as the other 2 I was testing yesterday the ACTIONS: Cola and ACTIONS: fee suppression one.

**Comment by theVKC** [comment]
@heatherallen: is there a chance you aren't on master branch there? Is anyone else having the issue at their office computer? @KallistaImdieke, could you try these out and see if worker signature auto-populates?

**Comment by khiestand** [comment]
I did not update actions COLA or Fee Suppression.

**Comment by theVKC** [comment]
Hmmmmmmmmm, maybe there's even more pull requests for you, @khiestand!

**Comment by heatherallen** [comment]
@theVKC, do I want it to show in global variables master branch = false or true?

**Comment by khiestand** [comment]
Ok will work on it tomorrow!  Do I need a separate issue or just reference this one again?

**Comment by khiestand** [comment]
@theVKC
The worker sig is now on the Fee Suppression, but I am getting an error on the COLA script, at line 1 column 1: Expected'

**Comment by theVKC** [comment]
That can't be all it says...

**Comment by khiestand** [comment]
![image](https://cloud.githubusercontent.com/assets/10159902/22484891/0d8fccca-e7c9-11e6-8932-bd5552094bf1.png)

**Comment by khiestand** [comment]
Oh does it need a parentheses?

**Comment by theVKC** [comment]
I'd say so @khiestand!

**Comment by theVKC** [comment]
@khiestand: I'm marking this back as "in development" since you're still working on a bug related to it. Let me know when you have it ready! :)

**Comment by khiestand** [comment]
@theVKC Just pulled the fix in!

**Comment by theVKC** [comment]
Just accepted it! Beautiful. Can I get testers on this?

**Comment by heatherallen** [comment]
the ones I see it not auto populating my worker signature are:
NOTES: IW CAAD CAWT
ACTIONS: COLA-getting error message

Otherwise I think all the rest are working on my end.

**Comment by theVKC** [comment]
Per general discussion and the fact that this is a minor bug, I am closing as this has been tested repeatedly by @heatherallen. :)
