### ISSUE TITLE
Case Transfer 'team' bug

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#701]
The team variable has an extra : in the variable name.  This is causing the do loop to not notify the worker if they are not entering 3 characters for the team.

I will take this one.

**Comment by theVKC** [comment]
Any chance we can get additional testers on this?

@levesswe and @heatherallen? Since you're here and everything?

**Comment by theVKC** [comment]
Confirmed that it's working from both. Thank you!
