### ISSUE TITLE
using powerpads in both maxis and prism

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#709]
Is anyone aware of a way to allow a staff person to use BOTH the maxis and the prism powerpads?  we are running into issues allowing the access to both versions -  

Employee has maxis powerpad loaded and logs into maxis using MDHS
Tried loading prism powerpad when logging in under cicspt4

has anyone else run into this or have any ideas how to resolve?
Thanks!

**Comment by RoberT-1000** [comment]
Totally do-able, but given the way that the powerdays are set up, you would need to change the file paths for the scripts each button runs.

![image](https://cloud.githubusercontent.com/assets/22157633/22341940/6756fe50-e3b8-11e6-8014-d690c702e3b7.png)


You would need to change that to the entire file path for the redirect file.

**Comment by jannellstearns** [comment]
Thanks Robert!  I believe Stearns found a solution! - I'm not sure if I should close this issue or not.

**Comment by theVKC** [comment]
Go ahead and close it. Or I'll do it!

**Comment by WCMattAnderson** [comment]
Just to throw it out there, in Wright we push 3 separate shortcuts, No scripts, Financial, C/S and if users use both pad types they launch the version desired. If users are not in Financial or C/S we delete the shortcuts on deployment.
