### ISSUE TITLE
enchancement request - establish dord docs (pa and npa)

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#710]
is it possible to add options to indicate who the documents should be sent to?  this allows the worker to only send to cp/ncp/relative caretaker - generate the documents only to the parties that we are ready to send them to.  (think paternity/relative caretaker/foster care cases)

**Comment by theVKC** [comment]
Any thoughts @MN-Script-Team/prism-scriptwriters and @MN-Script-Team/prism-supervisors?

**Comment by wrightcountykaren** [comment]
Yes, our establishment workers have said that is one of the reasons that they do not currently use the state script.  We do have a Wright County specific script that they are using.  Maybe at the next hack-a-thon the 2 scripts could be compared and meshed together.

**Comment by jannellstearns** [comment]
@wrightcountykaren - fantastic idea!

**Comment by heatherallen** [comment]
I just had a coworker suggest this same idea for an enhancement on these scripts, so looking for feedback.  Maybe the layout should be the worker should be able to select check boxes of what documents they want to print and to which parties.  This would alleviate printing unwanted documents.  Thoughts @MN-Script-Team/prism-scriptwriters?
