### ISSUE TITLE
Temporarily remove a few buggy/untested scripts for release sync

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#711]
This will be done so that new counties don't see untested stuff while I do a release sync. It shouldn't take long.

Scripts affected:

* ANOKA SANCTION (needs overhaul to use email [see #464], this will be removed entirely for now @levesswe, @paschell, and @RoberT-1000) 
* All intake scripts (they are being replaced with #451 someday soon)
* Interview Information Sheet (#620)
* Income Verification Script (#519)

There could be more. These will all get a goofy end-run in the complete list of scripts after the sync. County master-branch users hopefully won't notice any issues.

**Comment by theVKC** [comment]
@khiestand: can you check your installation to see if you see the above action scripts at all, as well as your e-filed option?

**Comment by khiestand** [comment]
@theVKC There are all there now, however I don't have the word doc placed so that does not open.
