### ISSUE TITLE
Question on Arrays

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#713]
@MN-Script-Team/prism-scriptwriters  I am working on a script for our office that will take all the no pay worklists pull information from all the cases and put that information in a spreadsheet that we can work off of. 

the question i  have is would it be better to do this by using an array (like the QW script) or reviewing each case one at a time (like the notice of continued service script) 

Any thoughts on which would be better?  thanks!

**Comment by KallistaImdieke** [comment]
@theVKC  can you help with the above question?  not sure if I needed to add a tag to you so i thought i would throw one out there.  thanks!

**Comment by theVKC** [comment]
Actually, not sure a GitHub comment is the right way to go about this in general. A couple of things:

1. The issue list should be used for issues/ideas related to specific scripts. Not for asking general scriptwriting questions (email or Slack works pretty well for general questions).
2. Tagging people: do PRISM-scriptwriters if you want community guidance (i.e. lots of people at counties). If you want me, do @theVKC. :)

So here's what I'm going to do: I'm going to close this one and the other one, and shoot you an email. We can start an email chain for it. :)
