### ISSUE TITLE
Question: searching multiple variables options and the last one needs to be selected from multiple CAAD Codes

### ISSUE THREAD

**Issue by KallistaImdieke** [MN-Script-Team/DHS-PRISM-Scripts#714]
@MN-Script-Team/prism-scriptwriters Another question I have is that I am trying to search CAAD the last CAAD note made of one of three codes (T0055, T0056 or T0057) to pull in when the last contact we had with NCP was.  once it finds one of those three codes i need it to grab the date and pull it into the spread sheet. Does anyone know how to set the variable it is looking for to multiple options instead of just one.  I have examples of looking for a specific name but not how to do it with multiple possibilities.  (hope that makes sense)

Thanks in advance.

**Comment by KallistaImdieke** [comment]
@theVKC  can you help with the above question?  not sure if I needed to add a tag to you so i thought i would throw one out there.  thanks!

**Comment by theVKC** [comment]
See #713. :)
