### ISSUE TITLE
Remove all navigation scripts Friday, February 10

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#717]
@MN-Script-Team/prism-scriptwriters: please take note that I'm formally retiring all navigation scripts in favor of the smaller, cleaner, prettier Power Pad, by February 10. So, please update your Power Pads. :)

**Comment by WCMattAnderson** [comment]
At Wright Co we have updated to the new Power Pad. Is there going to be actual file add/removes we need to also update before the 10th? If so, is there a specific list rather than having to run the config utility each update for new files?

**Comment by theVKC** [comment]
Right now, you can simply delete any locally-installed-files prefixed with "nav". Those have been supplanted. Generally speaking, changes don't happen often that require the installer (MAXIS has had three, I believe, since January 2015). When changes are made that do update the files, usually it'll be indicated in a GitHub issue.

If you see value in a locally-installed-files list, I could probably add that to the script list on DHS-SIR.
