### ISSUE TITLE
Enhancement Request - supervisor list in ~globvar

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-PRISM-Scripts#721]
I'm thinking we should add a list of user IDs in globvar that identifies the user as a supervisor. I have a script I'm working on that has two different run modes, one for child support officers and another for supervisory staff (_the script grabs a list of NCP SSNs and checks it against MAXIS to see if the NCP is active on GA or MFIP and the supervisory mode allows the user to run the script on an entire team and to add worklists for cases where the NCP is found active on GA or MFIP_).

Any thoughts on other scripts this type of run mode would be useful?

**Comment by RoberT-1000** [comment]
I have this rolling for Anoka right now if that's halal.

![image](https://cloud.githubusercontent.com/assets/22157633/22946345/c2d44806-f2bc-11e6-9013-6dc7154a7d19.png)

![image](https://cloud.githubusercontent.com/assets/22157633/22946360/ca066104-f2bc-11e6-81a9-b12059c42b38.png)

**Comment by theVKC** [comment]
I think it looks great! Love it!
