### ISSUE TITLE
Bug: Bulk list generator (another) CALI cancel button doesn't work

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-PRISM-Scripts#722]
When trying to select another CALI I hit cancel and the script still ran.

**Comment by RoberT-1000** [comment]
on it

**Comment by RoberT-1000** [comment]
The script should, in the future, be given some data validation around the dialogs.

**Comment by theVKC** [comment]
Per the nature of this minor issue, I'm closing it without requiring two counties to test. It's a cancel-button-related issue that was easy to resolve.
