### ISSUE TITLE
CRITICAL ERROR: ACTIONS - COLA

### ISSUE THREAD

**Issue by RoberT-1000** [MN-Script-Team/DHS-PRISM-Scripts#723]
Users are reporting the COLA script is missing a close parenthesis. It's on Line 49 at the changelog gobbins. 

@theVKC shall I submit a pull request? I know @khiestand submitted a working fix in master. Thoughts?

**Comment by levesswe** [comment]
While you're in there, please correct the spelling of "override" in line 122.  Thanks!

**Comment by theVKC** [comment]
Please feel free for expediting's sake, @RoberT-1000.

**Comment by RoberT-1000** [comment]
Pulling now. I'm not going to update the changelog...this is a syntax error and doesn't have any appreciable changes to the user

**Comment by theVKC** [comment]
@RoberT-1000: is this corrected in release and working for you?
