### ISSUE TITLE
New Notes Script- METS MA interface/referral

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#728]
This is a script that a Income maintenance staff person (who might have CAAD noting ability) or Child Support worker could use to note and create a potential worklist that a METS MA referral was attempted to be sent, but because of known issues with METS software, the referral could not be sent. Script could also have the ability to send an email to the Child support officer letting them know the referral was attempted to be sent but failed.

I will take this one!

**Comment by khiestand** [comment]
Instructions are complete, and on SIR

**Comment by theVKC** [comment]
Instructions are approved but checked out for now to prevent them from being seen (let's get the script uploaded with the email function first).

**Comment by heatherallen** [comment]
I tested this script at Scott County Hackathon and the script is working.

**Comment by khiestand** [comment]
@theVKC I pulled this in at Scott Co hackathon, it is complete and Heather tested it.

**Comment by theVKC** [comment]
Woohoo!

**Comment by theVKC** [comment]
The list of scripts has been updated to include this one. Sorry for the delay. Can I get someone to test it?

**Comment by theVKC** [comment]
@jlmartinone says @khiestand uses it and it works. Woohoo!
