### ISSUE TITLE
Enhancement Request -- Actions Unreimbursed Uninsured Received

### ISSUE THREAD

**Issue by gretchent74** [MN-Script-Team/DHS-PRISM-Scripts#732]
Add the ability to add the county name for the affidavit of service.  
I will take this one.  It is completed but is being tested

**Comment by theVKC** [comment]
Script is being tested locally before submitting to GitHub. Thanks @gretchent74!

**Comment by theVKC** [comment]
Could anyone test this one? Would @MN-Script-Team/prism-stearns be interested in testing this new field? Is it working for you?

One tester ought to do, this is a pretty simple enhancement. :)

**Comment by levesswe** [comment]
I tested this in the training region and it worked just dandy!  Thanks!

**Comment by theVKC** [comment]
Good enough for me. I'm calling it complete. Thanks @levesswe!
