### ISSUE TITLE
Stats blocks - add to PRISM scripts 

### ISSUE THREAD

**Issue by GayS** [MN-Script-Team/DHS-PRISM-Scripts#733]
PRISM scripts are missing out on being able to statistically show value by not updating existing and requiring the stats block as in the MAXIS scripts.

'Required for statistical purposes==========================================================================================
name_of_script = "_______________________.vbs"
start_time = timer
STATS_counter = 1                     	'sets the stats counter at one
STATS_manualtime = 750                	'manual run time in seconds
STATS_denomination = "C"       		'C is for Case; I is for each Item (ie bulk)
'END OF stats block===========

**Comment by GayS** [comment]
@theVKC any update on adding stats to all scripts?

**Comment by theVKC** [comment]
This is at this point a backlogged issue. I'm not marking it as a sleeper, but the time required isn't something I have clearance to commit anytime this month. I'm hoping for May or June, but no promises right now.

**Comment by theVKC** [comment]
(If counties want it and want to coordinate it, I could assist with that and work that through channels here)

**Comment by theVKC** [comment]
I'm going to tag this here: https://github.com/MN-Script-Team/BZS-FuncLib/issues/382

I figured out a method to push SQL queries through our scripts and to a database, *without requiring special software from the county*. This has been a huge hurdle to adoption.

The above issue needs some testing before I can affirm we'd move forward on it, but it's super promising and could change the priority of solving this issue. :)
