### ISSUE TITLE
Enhancement Request - Maintaining county script

### ISSUE THREAD

**Issue by wrightcountykaren** [MN-Script-Team/DHS-PRISM-Scripts#736]
Currently after the note is written in CAAD, the script presses transmit so the note is saved.

I would like to request that after the note is created in CAAD that the script not press transmit.
Reason:  the note is being written into a case that may not be within the county of the person running the script/writing the note.  If a typo is discovered, the note cannot be modified for the typo to be fixed after the note is saved.

**Comment by khiestand** [comment]
I can try to work on this one today!

**Comment by khiestand** [comment]
I completed this today and pulled it in.

**Comment by theVKC** [comment]
Fixed issue @gretchent74 and @heatherallen. Should be pulled through momentarily.
