### ISSUE TITLE
New Script -M6529 90 DAY REVIEW FOR INTEREST SUSPENSION

### ISSUE THREAD

**Issue by jlmartinone** [MN-Script-Team/DHS-PRISM-Scripts#739]
Shows what amount needed to be paid in the past 90 days, then calculates payments for the last 90 days. Then case notes accordingly.

Please assign to me.

Thanks!

**Comment by levesswe** [comment]
@jlmartinone, I had created a script like this a while back that has a few issues yet to be worked out.  I would be happy to share the code if you would like it.

**Comment by theVKC** [comment]
@jlmartinone: can I get an update on this? I'm assuming it's a backlogged issue, please correct me if I'm wrong.
