### ISSUE TITLE
Enhancement: Notes "Hearing Notes"

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#746]
May be helpful to have the option to enter a specific date of when the hearing was in the dialog.  In instances one is making notes a day or so after the hearing.

**Comment by theVKC** [comment]
@heatherallen, do you want this one?

**Comment by heatherallen** [comment]
You can add to my list :)

**Comment by theVKC** [comment]
No worries. I'm backlogging it for now but assigning to you. If you can let me know if/when it moves up on your list, I'll update the tags. Hopefully soon, this is something you yourself can just manage. :)

**Comment by theVKC** [comment]
This has been out there and working for a bit now. Closing.
