### ISSUE TITLE
Enhancement: Actions "COLA"

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#747]
When using the COLA script and it gets to the dialog box of check to see if another amount other than the 20% payback amount is entered.  Is there a better screen to have it take you too?  One of my coworkers suggested maybe CAFS instead of NCOD.

**Comment by gretchent74** [comment]
I agree that the screen the script goes to doesn't make sense.  I was thinking gong to the CAWT screen because that is where the 20% override work list is located.  thoughts?

**Comment by heatherallen** [comment]
@gretchent74 I like the CAWT suggestion because there should be that Override worklist there if the override is in place.

**Comment by gretchent74** [comment]
Please assign to me.  Thank you.

**Comment by theVKC** [comment]
This doesn't require additional testing because it was a simple change of one line and was tested multiple times in training region. :)
