### ISSUE TITLE
New script idea: script for assisting with child care support

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#751]
I am thinking it would be handy to have a script to assist with entering CAAD notes and sending documents to the parties for circumstances where there is a need to suspend or resume child care charging, or verify child care costs are being incurred.

You can assign this to me.

**Comment by levesswe** [comment]
This script contains options to produce CAAD notes and DORD docs as directed in Sir Milo (https://www.dhssir.cty.dhs.state.mn.us/PRISM/User_docs/SIRMILO/Child_Care_Support/Pages/default.aspx) for child care verification, suspension, and/or resumption, and create a follow up worklist.

**Comment by theVKC** [comment]
@levesswe has a working version that other counties want, will close issue and can re-evaluate it once Python conversion has taken place.
