### ISSUE TITLE
DVS Common Links Button hyperlink is incorrect

### ISSUE THREAD

**Issue by khiestand** [MN-Script-Team/DHS-PRISM-Scripts#752]
The correct URL is:
https://www.mndvsesupport.org/

**Comment by theVKC** [comment]
Are you taking this one, @khiestand?

**Comment by khiestand** [comment]
@theVKC 
I can try, if you let me know where the links are located??

**Comment by theVKC** [comment]
If I'm remembering correctly it's on the Power Pad. Shoot. That probably should fall on me shouldn't it.

I'm due out another Power Pad momentarily for a few other tweaks, so I'll take this one and try and get it all done at once.
