### ISSUE TITLE
Enhancement-Notes: Maintaining County

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#759]
Scott County had a few suggestions and/or enhancements:

1.To prevent the CAAD note from being so long maybe combine the worker name and county on the same line in the CAAD note. And could we add a spot for phone numbers?

2.The word "reviewing county" was a little confusing so a suggestion to clear this up is to have the layout in the dialog box look like this and possibly look at changing the word reviewing to responding?:

From: (your name) Requesting County: (your county)
To: (responding worker) Responding/Reviewing County: (responding county)

3.Give the worker an option to create a follow-up worklist on CAWT. Our worker puts a worklist out there that states, "Did so and so from such and such county respond regarding maintaining county?".

**Comment by theVKC** [comment]
Would you want this one, @heatherallen? I'm going to mark it as feedback needed and assign it to you (let me know if you want it added to the help-wanteds instead).

Get your feedback going, @MN-Script-Team/prism-scriptwriters :)

**Comment by gretchent74** [comment]
The script was reviewed by maintaining county worker and is working. We agree that having the worker name, county, and optional phone number on one line in the caad note would be helpful. Also to add an option to add a follow up CAWT note.

**Comment by theVKC** [comment]
Any chance I can get some testers?

**Comment by theVKC** [comment]
Seems to be working!
