### ISSUE TITLE
Interview Information Sheet bug

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#760]
Users reported that the Format Currency error messages were still being received on some cases.  In order to fix this bug, it was necessary to update the properties for some of the class methods used by the script.

**Comment by theVKC** [comment]
@levesswe has pulled in updated code. Can I get any testers? I'd like one for this from another agency other than Anoka. @MN-Script-Team/prism-scriptwriters?

**Comment by khiestand** [comment]
I tried running this for the NCP, and got Script Error at line 1, Column 1: Type Mismatch: 'CCur'

**Comment by theVKC** [comment]
@khiestand: did this happen right away? Any leads @levesswe?

**Comment by levesswe** [comment]
Sorry so long to get back to you on this, @khiestand  and @theVKC .  It took some time to figure out the problem, and I believe the issues may be coming from when the most recent payment is refunded...  Still working on a fix.  Fortunately, this script works like a charm the vast majority of the time.

**Comment by theVKC** [comment]
Seems like it's working now. Closing!
