### ISSUE TITLE
Bug ACTIONS : Send f0104 memo

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-PRISM-Scripts#762]
I was using this script and viewing a phone number for the worker I was sending the memo for using F1 on the worker number. I left the worker info popup window open and the script wasn't able to navigate to writing the memo because it had the extra task of leaving the pop-up.

Line 85 could maybe use some handling to make sure the script made it to DORD?

**Comment by theVKC** [comment]
Any chance you want it? Otherwise I'll mark it as a "help wanted". Just let me know... :)

**Comment by theVKC** [comment]
This is a pretty simple fix, @CDPotter, so I'll forego independent testing on this and #770. But, can you test it to make sure it's working in master?

**Comment by CDPotter** [comment]
I can confirm it is working in Master
