### ISSUE TITLE
Review Pay Plan - DL is Suspended - Enchnacement reqeust

### ISSUE THREAD

**Issue by jannellstearns** [MN-Script-Team/DHS-PRISM-Scripts#764]
The above scripts looks at all cases that have the E4111 RVW DLS PAY PLAN NCP CONTINUTED DELINQ to see if the DL is already suspended.  I would like to suggest that we add in for this version of the script to also look at CAWT to see if the following worklist exists:

E4102  REMOVE P FROM SUDL IF DL NON-COMPLIANT

This E4102 worklist would indicate that we have already sent the DL Non-compliance letter to the NCP and are waiting the appropriate amount of time before requesting suspension of the DL.  By having the script look for this worklist and purge the E4111, this will save CSO's from looking at this case twice for the same issue.  CSO should only need to review when the E4102 Remove P worklist pops up.

If I didn't explain this well, let me know!

Jannell

**Comment by theVKC** [comment]
Any thoughts @MN-Script-Team/prism-scriptwriters? Can we get feedback on this?

**Comment by KyleNelson-Hennepin** [comment]
It makes sense to me!

If a case has an E4111 worklist and an E4102 worklist, that means that the worker has reviewed the case already and determined it was appropriate to send the F0919 DLS PAPD non-compliance notice. Once the F0919 notice has been sent, E4111 worklists are irrelevant, because the worker will need to wait until the E4102 worklist to take any action on the NCP's DL anyway.

So if a case has an E4111 worklist and an E4102 worklist, then it makes sense to me to have the script purge the E4111 worklist.

**Comment by theVKC** [comment]
Excellent feedback, @KyleNelson-Hennepin. :)

Any takers on this one? I'm also going to run the request by my policy expert over here just to be on the up-and-up. :)

**Comment by KallistaImdieke** [comment]
I can take this one

**Comment by heatherallen** [comment]
I think this may tie into issue #468 merging the 2 scripts out there.  I have not been able to finish the merging of the 2 scripts but maybe this enhancement could be added to the already existing issue?

**Comment by theVKC** [comment]
@KallistaImdieke: kind of thinking we should wait on this until @heatherallen finishes her work on #468. Do you have an ETA on that Heather?

**Comment by heatherallen** [comment]
I have it close to complete, I've been wanting to test this on my caseload but have forgotten to test when I get them at the beginning of the month.  I am wondering if anyone out there has this worklist on a few of their cases to test and see if it works alright?  Anyone with E4111 worklists out there?

**Comment by KallistaImdieke** [comment]
We have some E4111 worklists out here but we have already run the bulk scripts that are out there to purge the ones we can so I am not sure if that would be any help?

**Comment by heatherallen** [comment]
Thanks @KallistaImdieke, I was actually able to test on one of my co-workers worklists.  I ran into a couple bugs so trying to work those out hopefully this week.
