### ISSUE TITLE
Favorites: add in "recommended scripts" functionality formally

### ISSUE THREAD

**Issue by theVKC** [MN-Script-Team/DHS-PRISM-Scripts#766]
This would allow an agency to formally create a "recommended scripts" function into the favorites. I'm imagining repurposing the select-a-favorite dialog, but with the option to export the saved scripts to a different file (which can then be located in the locally-installed-files directory).

@RoberT-1000, any chance Anoka already has this created in their implementation? Would you want it?

(BTW: favorites is going live in master momentarily)

**Comment by RoberT-1000** [comment]
I totally have built that functionality for Anoka users (both PA and CS). It also gives us the ability to give specific users additional scripts. I could take it but it's not something I'm going to be able to get to any time soon.
