### ISSUE TITLE
Bug/Enhancement on ACTION: Send DORD Memo Doc

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#770]
When using this script, the script does not give you an error message when you do not have a recipient selected.  So, if you type in your body of the memo and click ok your memo doc is not generated and you loose what you have already typed.

**Comment by theVKC** [comment]
That should definitely be included! Any takers? @MN-Script-Team/prism-scriptwriters?

**Comment by theVKC** [comment]
Accidentally closed because the word "fixes" was there, BTW.

**Comment by CDPotter** [comment]
Oh wow even in the body? Good to know!
