### ISSUE TITLE
New Script Idea: CS calculator to determine if MOD is needed

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-PRISM-Scripts#774]
In processing the data warehouse reports I'm learning that it's extremely tedious to fill in information for the online CS calculator to see if a referral to MOD might be needed. Would it be possible to build a script to pull known data from PRISM and do the calculation itself?

**Comment by CDPotter** [comment]
Brain dump from being unable to sleep Saturday; try to read off of quarterly reviews to get the most recent income figures are ID screens seem to be unreliable. make it clear to end users where income is being pulled from. would need to pull and count kids from CAPS, as well as CAPS other cases from CB functions. where would we find the guts for the CS calculator? 

(I'm totally willing to tackle this at a later point if we wanna back burner it I just wanted to get my thoughts down)

**Comment by theVKC** [comment]
What timeframe are you thinking about it?

**Comment by CDPotter** [comment]
Right now I can't work on scripts in an official capacity, last I heard until I finish probation (Jan 2018)
