### ISSUE TITLE
Other things to clean up on BULK/list-generator---CALI

### ISSUE THREAD

**Issue by KyleNelson-Hennepin** [MN-Script-Team/DHS-PRISM-Scripts#783]
A few other various minor things to clean up on this script...

The script creates a function called refresh_CALI_screen. When you get to the point in the script where the function would be called, the full code from the function is used instead of calling the function. Since the function would only be used once and is specific to this script only, I think it makes sense to just delete the function.

A variable called CAFS_checkbox is declared above the dialog boxes, can be deleted since variables don't need to be declared.

I'd also like to update/add more comments to the script.

This can be assigned to me.

**Comment by RoberT-1000** [comment]
Might I recommend moving the function to FuncLib instead of just deleting it

**Comment by KyleNelson-Hennepin** [comment]
The function checks to see if the user is in the Caseload Position List submenu (accessed from CALI if you F1 on some of the fields there). If so, the script will PF3 (so PRISM will navigate back to CALI). Then the script checks to see if the user is on CALI, and if so, navigates to the main screen.

We could add it to the FuncLib, but do you think it would be helpful for any other scripts? To me it seems specific to this script, so it might not be needed for any other scripts.

The problem the function is trying to solve, I think, is that if the user is F1'd into a PRISM submenu, the navigate_to_PRISM_screen function won't work, because you can't use the Direct Command line while you're in a PRISM submenu. So maybe the navigate_to_PRISM_screen function should be improved to back out of submenus if they're in one?

**Comment by CDPotter** [comment]
You could definitely do that with a check for screen line or two inside the navigate function.

**Comment by KyleNelson-Hennepin** [comment]
Yes, but the problem is that all of PRISM's submenus are sized and positioned differently and cover up different parts of the screen. So it could be challenging figuring out what text to check for, because it's different for each submenu.

Though we could account specifically for the more commonly used submenus. This could include the caseload position list (if you F1 on some of the CALI fields), or the case search help routine (if you F1 on a case # field), or the person search (if you F1 on an MCI # field).

**Comment by KyleNelson-Hennepin** [comment]
A few other things that I thought I added to this issue yesterday but looks like I forgot...

The last payment date column in Excel was partially left-aligned and partially right-aligned. I right-aligned both to improve readability.

The financial info added to Excel from CAFS only displays the digits after the decimal if they aren't 0. I changed their formatting to Number and made it so they'll always display two digits after the decimal.

**Comment by CDPotter** [comment]
I should say I was thinking about it on the back end rather than the front end. 

The rough loop would be for example:

DO
Type CAAD on nav bar
Check to see if we went to CAAD
if we didn't PF3
LOOP until screen_check = nav_screen

**Comment by KyleNelson-Hennepin** [comment]
Ohhh ok. Yeah that seems like it would work!

Are you talking about adding this to the navigate_to_PRISM function? Or to the BULK/list generator-CALI script?

If you think it makes sense to add this to the navigate_to_PRISM function, I can create an issue for this over in the function library.

**Comment by CDPotter** [comment]
I would agree that it would be best suited to be in the function. If you want to make an issue and tackle it that would be fantastic!

**Comment by KyleNelson-Hennepin** [comment]
Done! See FuncLib issue #385

**Comment by theVKC** [comment]
@KyleNelson-Hennepin: I'm just starting to filter through all of this trying to understand it. On the surface, this looks fantastic. I have some testing to do around it, and will. I was out for a significant portion of the last couple of weeks, so forgive me for being off a bit while I get back on this.
