### ISSUE TITLE
Enhancement - Casee Transfer script

### ISSUE THREAD

**Issue by wrightcountykaren** [MN-Script-Team/DHS-PRISM-Scripts#786]
Can a pop up box be added to show up at the very end of the script reminding people to either screen scrape the case, or send the physical file, or other "reminder" language that the collaborative decides on.

**Comment by KyleNelson-Hennepin** [comment]
I haven't heard that term before, what does "screen scrape the case" mean?

The current closing message is "Success! The case has been transferred and CAAD noted." I could see adding some more generic reminder text to the closing message, something like, "Success! The case has been transferred and CAAD noted. Please complete any additional necessary actions per your county's case transfer process."

**Comment by wrightcountykaren** [comment]
"Screen scrape" is a term used with the OnBase EDMS software.  Not every county uses OnBase as their EDMS software, so a generic message would also work as a reminder.

**Comment by jlmartinone** [comment]
please assign this to me....Thanks

**Comment by theVKC** [comment]
Seems like it's working!
