### ISSUE TITLE
Send F0104 Dord Memo Bug

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#791]
Missing check_for_PRISM(false), so users can time out and lose their work.

**Comment by KyleNelson-Hennepin** [comment]
Related to this, I added [issue number 387](https://github.com/MN-Script-Team/BZS-FuncLib/issues/387) to the FuncLib issues for the check_for_PRISM function.

**Comment by theVKC** [comment]
Any chance I can get someone to test this?

**Comment by theVKC** [comment]
@levesswe, any chance you can confirm this is now working as expected in master?

**Comment by theVKC** [comment]
Collaborative says it's working!
