### ISSUE TITLE
Non Pay script error message

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#793]
Error message received regarding write_new_line_in_PRISM_case_note that stops the script from entering the CAAD code if the user elects to send out the CP Initial Contempt Letter.

**Comment by CDPotter** [comment]
I've also noticed a problem in which the script doesn't grab the last pay data properly. In these cases the $ amount was blank and the last pay date was " ata *** " which appears to be the cutoff portion of ***End of Data***. I've seen it happen twice on cases, one case had no payment history, and one did. 

Maybe a bit of safeguarding could be good for this? Something like present the user with an edit box if isdate(last_pay_date) = false same if last pay amount is not a number.

**Comment by theVKC** [comment]
We're out for testing! Any chance I can have someone check it really quick? Shouldn't need much, just check the box and see if it works?

**Comment by levesswe** [comment]
I have tested and the error message I originally created the bug for is resolved, regarding the outdated function.  

@CDPotter 's suggestion is still an possible future enhancement for this script...

**Comment by theVKC** [comment]
Well that future enhancement should be tracked separately. ;)

I'll mark this as ready-for-release. Thanks @levesswe!

**Comment by theVKC** [comment]
Collaborative says it's working!
