### ISSUE TITLE
New Idea: Script that creates Payment Plans

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#795]
I received this idea from one of my coworkers here in Scott Co.  Does anyone else like the idea of creating a script that will create a Payment Plan to Prevent Enforcement Action (DORD F0701)??

**Comment by gretchent74** [comment]
I have one.  if you are interested in modifying it, let me know.

**Comment by heatherallen** [comment]
Gretchen--I would like to take a look at the one you have.  Can you email to me or send across on here by using Gist?  Thanks!

**Comment by gretchent74** [comment]
I think i created a gist called payment agreement.  If it doesn't work let me know.

**Comment by theVKC** [comment]
I don't see any pull requests for this, was it shared?

**Comment by heatherallen** [comment]
@vkc--Gretchen did share her code with me, but I was more looking for a script that actually prints and plugs in the info needed on a dl payment agreement after the NCP has been offered the agreement.  I am working on making a more generic script and using some of Gretchen's code if appropriate.

**Comment by theVKC** [comment]
@heatherallen, any update on this one?

**Comment by heatherallen** [comment]
@theVKC, I actually have completed a script for this a couple weeks ago. I was having my agency test prior to putting it on github.  My script just prints the actual dl payment agreement for now, so if we think I should share to the group now to test, I'd be more than happy to add it.

**Comment by theVKC** [comment]
No worries, @heatherallen! I've put in a request for policy review, once that comes back ready-to-go, please feel free to pull in your code for testing! I'll let you know once I'm ready for it. :)

**Comment by MelissaPHD** [comment]
I don't see any policy issues arising from a script that simply fills in the fields on DORD F0701.

**Comment by theVKC** [comment]
Thanks @MelissaPHD! @heatherallen, feel free to send a pull request into master!

**Comment by heatherallen** [comment]
@theVKC - I did submit pull request for this.  Please let me know if i did it correctly as this is a brand new script with new code.

**Comment by heatherallen** [comment]
@theVKC this one looks like it is complete and may need to be pulled in or maybe you were just waiting on testing.
