### ISSUE TITLE
Help:  Navigation to Maxis

### ISSUE THREAD

**Issue by KathyHowdahl** [MN-Script-Team/DHS-PRISM-Scripts#796]
While using Prism Script "Navigation to Maxis" we are entering the maxis number, we are signed on to maxis on another session, and have entered our passcode.  Prism navigation error reads" Doesn't navigate to Maxis" then locks you out of your script session to select any other commands or process any other cases.  Thank you for your assistance.

I did ask our IT department, they said to refer on to you folks.

**Comment by CDPotter** [comment]
Do you mean MAXIS Screen Finder? I'm fairly new to the world of PRISM scripts but in looking at the MAXIS Screen Finder I don't see any error that contains "Doesn't". Were you getting this error message instead? "You are not currently in MAXIS. Navigate to MAXIS and try again. Make sure you aren't passworded out!"

For MAXIS Screen Finder I do believe you need to start the scripts from the window in which MAXIS is open on. So if you open a new window for MAXIS and start the script from the PRISM window it won't work.

**Comment by KathyHowdahl** [comment]
Perfect! I didn’t have my power pad open on the maxis screen.  I was trying to get “to” maxis from the prism session.  I have it figured it out now.  Thanks so much.

Kathy Howdahl
Child Support Supervisor
Koochiching County Public Health and Human Services
218-283-7000 ext: 1017
This email may contain confidential and privileged material for the sole use of the intended recipient. Any review, use, distribution, or disclosure by others is strictly prohibited. If you are not the intended recipient (or authorized to receive for the recipient), please contact the sender by reply email and delete all copies of this message
