### ISSUE TITLE
BUG: Mod CAAD Note - Contact Checklist

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#798]
There is a minor bug that if the user checks the box that they discussed the child support increasing, decreasing, or staying the same, the CAAD note says "Informed of the online child support calculator." and if the user checks the box for informing them of the online calculator, the CAAD note says "Informed that support could go up, down or remain the same."

**Comment by KallistaImdieke** [comment]
I can take this issue

**Comment by theVKC** [comment]
#814 pulled this in to master. @gretchent74 has volunteered to test. Thank you you two!!

**Comment by gretchent74** [comment]
I have tested this script and the correct note now corresponds with the correct information put into caad.

**Comment by theVKC** [comment]
Woohoo! Thanks @gretchent74!
