### ISSUE TITLE
Enhancement: ACTIONS-Un/Un Returned Docs

### ISSUE THREAD

**Issue by heatherallen** [MN-Script-Team/DHS-PRISM-Scripts#799]
Do other Counties think it would be a good idea to have a field under the "Amount Requested" where user can enter the dates of when this amount was incurred by the client (per client's affidavit)?
If so, could the dates be included in the CAAD note and the comments on OBBD?

**Comment by levesswe** [comment]
Sounds like a good idea to me!

**Comment by theVKC** [comment]
Hackathon thinks it's good to add post conversion.
