### ISSUE TITLE
BUG Actions send f0104 dord memo

### ISSUE THREAD

**Issue by CDPotter** [MN-Script-Team/DHS-PRISM-Scripts#800]
I wrote up a rather verbose DORD memo to both CP and NCP and when I went to finish it I got notification that it was too long and that I had to edit it, The script then looped this a few times but never gave me anything change to actually edit the document. I think the dialog loops need to be reviewed.

**Comment by theVKC** [comment]
Group feels this is a worthy enhancement post Python conversion, but is not considering it critical enough to fix pre-conversion. We'll tag it as an enhancement instead and look at it post-conversion!
