### ISSUE TITLE
Bug - Affidavit of service by mail

### ISSUE THREAD

**Issue by Snickemj** [MN-Script-Team/DHS-PRISM-Scripts#802]
There is a slight error in selecting the documents that were served in the Affidavit of Service By Mail script.  When I select Aff of Default and ID it puts the Case Financial Summary - CAFS on the DORD affidavit.  If I select Case Financial Summary -CAFS it will put on Aff of Default and ID on the DORD document.  It appears that these two buttons need to be switched around since they are currently backwards.  Thanks.

**Comment by heatherallen** [comment]
@theVKC - I got this corrected for you :) and submitted pull request.

**Comment by heatherallen** [comment]
@theVKC this one seems to be completed and may just need to be pulled in.

**Comment by theVKC** [comment]
@gretchent74 is testing!

**Comment by gretchent74** [comment]
I tested the script and Aff of Default and ID it puts the Case Financial Summary are no longer reversed.

**Comment by theVKC** [comment]
Woohoo!
