### ISSUE TITLE
New Script Idea: NCP GA/MFIP look up

### ISSUE THREAD

**Issue by levesswe** [MN-Script-Team/DHS-PRISM-Scripts#804]
Anoka County had created this script as a county-specific bulk script to create a list of NCP's on a case load and obtain information about which NCP's are currently active on MFIP or GA programs.  As other counties have expressed interest in this script, I have adapted it for the collaborative.  Have a session of PRISM and session of MAXIS open when you test this script.

The script was built with 3 possible run modes:  1. Supervisor Mode, Entire Team 2. Supervisor Mode, Single CALI, and CSO mode.

**Comment by theVKC** [comment]
@levesswe, I'm closing #805 because it doesn't follow the proper filename format. Linking to it here because it looks like you were primarily trying to share the script with @wrightcountykaren, which is great. Don't want to lose that info in case she needs it.
