### ISSUE TITLE
Court Prep Sheet

### ISSUE THREAD

**Issue by ajluebbe** [MN-Script-Team/DHS-PRISM-Scripts#93]
Calls up the determined information needed for court from PRISM screens and transfering that information to a WORD document 
ASSIGNED TO ANOKA
HPE

---

VKC update 01/18/2017

Per hackathon today, we are going to redesign the script. We are going to try and make it more usable for all court actions (as opposed to just contempt actions). Wendy is on it and it's no longer backlogged.

**Comment by RobertFewins-Kalb** [comment]
Closing issue #BecauseReasons

**Comment by theVKC** [comment]
This script has been deployed, fyi. @gretchent74 is working on instructions. Using original issue for tracking purposes.

**Comment by theVKC** [comment]
Reopening per new process which states that issues remain open until instructions are in SIR. @gretchent74  has agreed to write instructions but is out for a couple of weeks. Is there any chance AT ALL that anyone else from any other counties could write up instructions for this right quick? @MN-Script-Team/prism-scriptwriters @MN-Script-Team/prism-supervisors?

**Comment by theVKC** [comment]
@heatherallen, since you're testing this right now in your agency, would you mind terribly writing up instructions for it?

**Comment by theVKC** [comment]
(If it survives your testing, that is, we could cut it if it's still error prone)

**Comment by heatherallen** [comment]
sure thing, I will try to get it tested today and if it works I will get some instructions written. :)

**Comment by heatherallen** [comment]
I tested this morning, and as much as I want to say this worked, I'm not having luck with it finding the word doc that I have saved.  I'm getting the error message of Script Error at Line 1, Column 1: This file could not be found.  It is opening Word but not finding the document saved.

**Comment by levesswe** [comment]
I bet it is an issue with the filename.  The script refers to "Court Prep Worksheet.dotx" and the file in DHS-PRISM-SCRIPTS/docs is called "court-prep-worksheet.dotx".  The name needs to be the same in both places...

**Comment by wrightcountykaren** [comment]
I have a few questions now that I have reviewed the Word document.
Is this designed to be for any court hearing or for contempt only?
If it is for any hearing, then it might be nice to have a field to indicate what kind of hearing it is.

Is the PRISM info pulling into the fields from NCOL for Basic Medical and CCC charging?  Those fields would be blank if it is for an establish action then right?  Or are you looking to include the proposed order information in those columns.  

If you are going to court on a mod action, then what data is in those columns – the old order info or the proposed order info

If this is a contempt only worksheet, then I think we should re-name it contempt prep worksheet.  Or we could look into enhancing the script to work for all court prep.
Just my thoughts.

**Comment by levesswe** [comment]
@wrightcountykaren, it was originally designed for a contempt court prep, but I support the idea of making it more useful beyond contempt actions and soliciting ideas on how it can be enhanced.  

You are correct in that the support amounts are pulled from NCOL, so would be blank for establishment cases.  However, the case worker can modify the amounts after the worksheet is generated to reflect a proposed amount.

**Comment by theVKC** [comment]
Well, does someone want to add additional features to it? @levesswe? Perhaps a @MN-Script-Team/prism-wright scriptwriter?

I'm a bit hesitant to call it "completed" with these questions hanging out there. I can remove it temporarily while bugs are worked out if need be, and I'll assume that's the choice if I don't hear back this week. :)

**Comment by levesswe** [comment]
I feel like this is should be the subject of a Hackathon so that we can get more input from people/agencies about what would be most useful.  I have limited experience with court prep for actions other than contempt, so I don't have a clear idea on what the end result should look like if we broadened its scope.  Maybe at a Hackathon we could put some ideas together and come up with an action plan.

**Comment by heatherallen** [comment]
I agree with Wendy! I think this can be altered to more universal.

**Comment by theVKC** [comment]
The next hackathon is scheduled for 01/10/2017 at Stearns. Can all participants plan on being part of the discussion that day? I've got a note on my list to go over this.

**Comment by theVKC** [comment]
Old version removed, and this issue has been kicked to "backlog". Thank you all!

**Comment by heatherallen** [comment]
I unfortunately am only in the office in the morning that day...so I could maybe be available for discussion if its in the morning.

**Comment by KallistaImdieke** [comment]
I will be there.

**Comment by levesswe** [comment]
I have approval to be there, too!!

**Comment by levesswe** [comment]
For those that are interested, the discussion about the Court Prep Worksheet is moved to Hackathon scheduled for Wednesday, January 18, at the Wright County Government Center Training Room in Buffalo.  Hope you can come!

**Comment by theVKC** [comment]
Per @levesswe, this is still being worked on. Thank you!!!!
