### ISSUE TITLE
Non-payment letter to NCP

### ISSUE THREAD

**Issue by wrightcountykaren** [MN-Script-Team/DHS-PRISM-Scripts#98]
This script will pull information out of PRISM and put it into a letter to the NCP regarding non-payment and the possibility of contempt action starting.  Items to pull:  NCP name, addr, MCI #, Monthly obligation, payment amt due which includes the 20%, date of last payment made.

**Comment by RobertFewins-Kalb** [comment]
Anoka County has a Word doc that we use for this. @paschell  and @levesswe  can speak more to this point, but we are also discussing building a worklist scrubber for E0002 worklist items that would load the doc for each case.

**Comment by levesswe** [comment]
We have been working on a very generic non-pay ltr script, which basically done and I will upload to github. It wouldn't be that difficult to modify the generic letter to include the information you list above. 

Also, we have asked the State if they will create a DORD Non-pay letter.  Fingers crossed!

**Comment by RobertFewins-Kalb** [comment]
@paschell, what's the skinny on the non-pay letter? Who's cage do we need to rattle to get this finished?

**Comment by paschell** [comment]
@RobertFewins-Kalb, Good question.  I was told it could take awhile but I will check into it.   Last check around Christmas it was still in the POLICY arena.

**Comment by RobertFewins-Kalb** [comment]
Okum dokes! Thanks, @paschell!!

**Comment by theVKC** [comment]
Can I get an update on this issue? @wrightcountykaren, @RobertFewins-Kalb, @levesswe, or @paschell?

It's been open over a year. If it isn't a priority I'd like to close it and we can re-evaluate it later. If it is a priority, I'd like to find someone who can get it done (even if that's me). :)

**Comment by levesswe** [comment]
We already have a generic (albeit, very generic) non pay letter that is available using the ACTIONS - NONPAY.vbs script, but had greater visions of an actual non pay letter produced in PRISM by DORD.  @paschell sent proposed drafts of non-pay letters to the state, and last we heard they were being reviewed by policy people.  

In one of our meetings, we discussed closing this issue as there is not really much that we can do with this issue, script-wise.  However, counties wanted to keep the issue open for periodic follow up with the state.

**Comment by theVKC** [comment]
We could mark it as a sleeper issue, and when @paschell or someone else gets word about the status, we could reopen it. Alternatively, @paschell, if I knew to whom you sent it, I could check in with them myself.

**Comment by paschell** [comment]
@theVKC  - At last check, Carol Taggert asked who was the CLV group or contact and I probably gave her the wrong person's name and not the policy person.  Because I don't  know if I ever received anything from the POLICY helpdesk  as to who might have been assigned.    So I don't know.  I just keep asking the status through our webmail every couple of months.  :-(     Oh dear....I think this went down the rabbit hole.

**Comment by theVKC** [comment]
Per hackathon 08/08: it would be nice if this could automatically generate and auto-populate existing Word docs. Wright and Stearns both have Word docs already available. I would like to make this into a script which fills out those docs. Pretty straight forward, once #12 is complete (I'm doing that one). 

@KallistaImdieke has volunteered to take this on, pending her other assignments of course. Thank you @KallistaImdieke!

**Comment by theVKC** [comment]
@KallistaImdieke, we have two new functions you can use in your work, courtesy of @RobertFewins-Kalb and @levesswe: **word_doc_open** and  **word_doc_update_field**. You can see details on the v2016.08 FuncLib release notes: https://github.com/MN-Script-Team/Release-Notes/blob/master/FuncLib/FuncLib%20v2016.08%20release%20notes.md

**Comment by theVKC** [comment]
We've decided to simply enhance the non-pay script. Jodi uses that script a lot, so she'll take it. Thanks @jlmartinone!
